### ISSUE TITLE
Send Email After Change Order State

### ISSUE THREAD

**Issue by epp1628** [Bukimedia/PrestaSharp#103]
I am trying to update one of orders status.The process am following is trying to add a new entry in order histories,make a http request in order_histories?sendemail=1 and finally update the status in order status.Below is my code for the new entry in order historues :

OrderHistoryFactory FactoryF = new OrderHistoryFactory(BaseUrl, Account, Password);
                List<long> ids = FactoryF.GetIds();
                Console.WriteLine(ids[ids.Count - 1]);
                Console.WriteLine(ids.Count);
                Bukimedia.PrestaSharp.Entities.order_history ordF = FactoryF.Get(Convert.ToInt32(id));
                Bukimedia.PrestaSharp.Entities.order_history ordFInsrtList = new Bukimedia.PrestaSharp.Entities.order_history();
                long nextID = Convert.ToInt64(ids[ids.Count - 1]+1);
ordFInsrtList.id = nextID;
                ordFInsrtList.id_order = Convert.ToInt64(orderid);
                ordFInsrtList.id_employee = Convert.ToInt64(19);
                ordFInsrtList.id_order_state = Convert.ToInt32(inifile.Read("Prestashop", "SecondState"));
                ordFInsrtList.date_add = DateTime.Now.ToString();
                FactoryF.Add(ordFInsrtList);

I have the privileges : get="true" put="true" post="true"

After severals attempts am getting this error:

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>
</error>
<error>
<message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>
</error>
<error>
<message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>
</error>
<error>
<message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>
</error>
</errors>
</prestashop>
  HttpStatusCode: InternalServerError

**Comment by avperillo** [comment]
Hello,

Have you solved the problem? because I have the same...

This is the error:

1

12345678901234567890123456789012

Basic MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI6

application/json, application/xml, text/json, text/x-json, text/javascript, text/xml

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[127]]></code>
<message><![CDATA[XML error : String could not be parsed as XML
XML length : 337
Original XML : application%2Fxml=%3Cprestashop%3E%0A%3Corder_history%3E%0D%0A%20%20%3Cid_order_state%3E10%3C%2Fid_order_state%3E%0D%0A%20%20%3Cid_order%3E1%3C%2Fid_order%3E%0D%0A%20%20%3Cid_employee%3E0%3C%2Fid_employee%3E%0D%0A%20%20%3Cdate_add%3E2015-01-26%2022%3A41%3A03%3C%2Fdate_add%3E%0D%0A%3C%2Forder_history%3E%0A%3C%2Fprestashop%3E&sendemail=1]]></message>
</error>
</errors>
</prestashop>
  HttpStatusCode: InternalServerError



And this is the serialized value

<prestashop>
<order_history>
  <id_order_state>10</id_order_state>
  <id_order>1</id_order>
  <id_employee>0</id_employee>
  <date_add>2015-01-26 22:41:03</date_add>
</order_history>
</prestashop>

![image](https://cloud.githubusercontent.com/assets/8981123/5909889/e7e16284-a5b4-11e4-97eb-fa2e452c31ed.png)

Thanks !!

**Comment by etokamil** [comment]
Hi,
I've got the same problem and changed function in OrderHistoryFactory.cs

>public Entities.order_history Add(Entities.order_history OrderHistory) 
        {
            long? idAux = OrderHistory.id;
            OrderHistory.id = null;
            List<PrestaSharp.Entities.PrestaShopEntity> Entities = new List<PrestaSharp.Entities.PrestaShopEntity>();
            Entities.Add(OrderHistory);
            RestRequest request = this.RequestForAdd("order_histories&sendemail=1", Entities); //here I kick-off RequestForAddOrderHistory and add "&sendemail=1
            Entities.order_history aux = this.Execute<Entities.order_history>(request);
            OrderHistory.id = idAux;
            return this.Get((long)aux.id);
        }

It works for me :-)

**Comment by EduLeonPavon** [comment]
Thanks :+1:  @etokamil

**Comment by avperillo** [comment]
Hi @etokamil and @EduLeonPavon  ..!!

Sorry but I try your solution and I have the same error.

This is my OrderHistoryFactory.cs now, like you tell me

 public Entities.order_history Add(Entities.order_history OrderHistory)
        {
            long? idAux = OrderHistory.id;
            OrderHistory.id = null;
            List<PrestaSharp.Entities.PrestaShopEntity> Entities = new List<PrestaSharp.Entities.PrestaShopEntity>();
            Entities.Add(OrderHistory);
            RestRequest request = this.RequestForAddOrderHistory("order_histories&sendemail=1", Entities);
            Entities.order_history aux = this.Execute<Entities.order_history>(request);
            OrderHistory.id = idAux;
            return this.Get((long)aux.id);
        }

This is my test code for try to add one order history 

Dim hisFac As New Factories.OrderHistoryFactory(PrestaConfig.WSBaseUrl, PrestaConfig.WSAccount, String.Empty)
        hisFac.Add(New Entities.order_history With {.id = hisFac.GetAll().Max(Function(x) x.id) + 1, .id_employee = 0, .id_order = id_order, .date_add = Now.ToString(), .id_order_state = id_estado})

This is the string serialized 

![image](https://cloud.githubusercontent.com/assets/8981123/9629759/61c5f378-5175-11e5-88d7-8df1a662ee82.png)

And finally, here the error.

![image](https://cloud.githubusercontent.com/assets/8981123/9629814/d2f3efaa-5175-11e5-8143-77f95dc90830.png)

Are you really sure that it work? ...

**Comment by etokamil** [comment]
Hi,

The only difference I see between our codes is that you still use RequestForAddOrderHistory instead RequestForAdd, but you've comment line with AddParameter, so both functions looks pretty much the same.
I use Presta 1.6.0.8 and works for me.
Some said to me that should be ?sendemail=1 instead od &sendemail=1 so you can try.
Another difference is date format. I'm sending yyyy-MM-dd HH:mm:ss but maybe it doesn't matter.

**Comment by avperillo** [comment]
Thanks @etokamil , I can send emails!!!! 

I have two errors, the date format and the use of method RequestForAddOrderHistory.
In this method not have the parameter ParameterType.RequestBody when use addParameter. In RequestForAddOrderHistory is  "request.AddParameter("application/xml", serialized);" but it should be  "request.AddParameter("application/xml", serialized, ParameterType.RequestBody);"  like method RequestForAdd

I put the code.

OrderHistoryFactory.cs

public Entities.order_history Add(Entities.order_history OrderHistory)
        {
            long? idAux = OrderHistory.id;
            OrderHistory.id = null;
            List<PrestaSharp.Entities.PrestaShopEntity> Entities = new List<PrestaSharp.Entities.PrestaShopEntity>();
            Entities.Add(OrderHistory);
            RestRequest request = this.RequestForAdd("order_histories?sendemail=1", Entities);
            Entities.order_history aux = this.Execute<Entities.order_history>(request);
            OrderHistory.id = idAux;
            return this.Get((long)aux.id);
        }

How to add one order history

 ordHistory.id_employee = 0;
         ordHistory.id_order = 2;
            ordHistory.id_order_state = 2;
            ordHistory.date_add = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
           ordHistory = factory.Add(ordHistory);

really thank you very much @etokamil ..!!
