### ISSUE TITLE
Regarding to closed issue #71

### ISSUE THREAD

**Issue by joparsa77** [Bukimedia/PrestaSharp#117]
Hi,

Just in case you don't re-open closed issues I create this regarding to issue #71 ... which is not working for me.

I tried the solution described in that issue, but the order_history add request inovcation is returning me the following error:

![image](https://cloud.githubusercontent.com/assets/7669669/5852485/e73da27a-a217-11e4-8f94-7c730fd9b9df.png)

I even tried to send the 'sendemail' parameter as an URL segment, but it didn't work.
My prestashop version is 1.6.0.9.
And the code of RequestForAddOrderHistory function in my project is (notice some namespaces are renamed, but this is not a problem):

```
    protected RestRequest RequestForAddOrderHistory(string Resource, List<Model.PrestaShop.Entities.PrestaShopEntity> Entities)
    {
        /*
        Parameter paramSendEmail = new Parameter();
        paramSendEmail.Type = ParameterType.UrlSegment;
        paramSendEmail.Name = "SendEmailParam";
        paramSendEmail.Value = "sendemail=1"
        */

        var request = new RestRequest();
        request.Resource = Resource;
        //request.Resource = Resource + "{SendEmailParam}";
        request.Method = Method.POST;
        request.RequestFormat = DataFormat.Xml;
        request.XmlSerializer = new PrestaShopSerializer();
        string serialized = "";
        foreach (Model.PrestaShop.Entities.PrestaShopEntity Entity in Entities)
        {
            serialized += ((PrestaShopSerializer)request.XmlSerializer).PrestaSharpSerialize(Entity);
        }
        serialized = "<prestashop>\n" + serialized + "\n</prestashop>";
        request.AddParameter("xml", serialized);
        request.AddParameter("sendemail", 1);

        //request.AddParameter(paramSendEmail);
        return request;
    }
```

Thanks in advance!

**Comment by xperit** [comment]
Hello,
I made it working but I didn't test email at this time.

In RequestForAddOrderHistory, I've replaced : 
 request.AddParameter("application/xml", serialized);
by
 request.AddParameter("application/xml", serialized, ParameterType.RequestBody);

And this line :
 request.AddParameter("sendemail", 1);
must be commented out or replaced by :
 request.AddParameter("sendemail", 1, ParameterType.QueryString);

I didn't test last assertion.
