### ISSUE TITLE
Can't filter orders by date_add

### ISSUE THREAD

**Issue by InformaticaCreativa** [Bukimedia/PrestaSharp#119]
I'm trying to use the following method
          public List<Entities.order> GetByFilter(Dictionary<string, string> Filter, string Sort, string Limit)
and I want to use filter with date_add field. 

I write the following code but the response is always "BadRequest" as the attached image shows.
            Dictionary<string, string> filters = new Dictionary<string, string>();
            string sort = null;
            string limit = null; 
            string from = string.Format("{0:yyyy-MM-dd HH:mm:ss}", DateTime.Now.AddDays(-2).Date);
            string to = string.Format("{0:yyyy-MM-dd HH:mm:ss}", DateTime.Now.Date);
            filters.Add("date_add", string.Format("[{0},{1}]", from,to));
            List<Bukimedia.PrestaSharp.Entities.order> orderList = OrderFactory.GetByFilter(filters, sort, limit);

Can someone help me, please? What's wrong? 
Thank you 

![img](https://cloud.githubusercontent.com/assets/10862537/6057110/850703ae-ad1a-11e4-8a32-77a6228a1483.png)

**Comment by EduLeonPavon** [comment]
Hello @InformaticaCreativa 
The date fields are not filterable.
Regards.

**Comment by InformaticaCreativa** [comment]
I apologize for the reopening of this issue.
I need to take orders through filters; having ruled out date fields, I'm using the id field but the result is not what I want: 

Dictionary<string, string> filters = new Dictionary<string, string>();
string sort = null;
string limit = null; 
string from = "1";
string to = "4";            
filters.Add("id", string.Format("[{0}|{1}]", from, to));            
List<Bukimedia.PrestaSharp.Entities.order> orderList = OrderFactory.GetByFilter(filters, sort, limit);

I want to get all orders with id field between 1 and 4.
On my site I have order ids from 1 to 4 and this code only returns the order with id 1. 
I tried with 
filters.Add("id", string.Format("[{0},{1}]", from, to));     //range with comma 
but without right results too.

Can you help me, please? If id filed isn't filterable, what can I do?
Tanks

**Comment by EduLeonPavon** [comment]
Hello @InformaticaCreativa 
Have you tried to navigate to the API url?
Sample: URL: (Store URL)/api/customers/?display=[lastname]&filter[id]=[1,10]

Regards.

PS. http://doc.prestashop.com/display/PS14/Chapter+8+-+Advanced+Use

**Comment by InformaticaCreativa** [comment]
Yes I have tried. The result is the same: only order with id filed = 1.

**Comment by EduLeonPavon** [comment]
Hello @InformaticaCreativa again,
Notice that PrestaSharp reads the web service resultset so I recommend redefining the filter options.
Best regards.

**Comment by jagred** [comment]
I have possible solution (workaround) for dates filtering.

In file RestSharpFactory.cs, in function requestForFilter at last line add new parameter
`request.AddParameter("date","1");`
this allows for sorting and filtering by dates fields

**Comment by ToineSeiter** [comment]
I can't see that feature in the last Nuget package (v1.157.0 at this moment). I guess that the nuget package isn't automatically published from Github.
Will there be a new Nuget release including this ?

(if this helps.... https://weblogs.asp.net/bsimser/automatically-publishing-nuget-packages-from-github)
