### ISSUE TITLE
Getting null reference from api when updating stock availability

### ISSUE THREAD

**Issue by iang0ld** [Bukimedia/PrestaSharp#120]
This has been working previously, but not now.

StockAvailableFactory StockAvailableFactory = new StockAvailableFactory(ApiAddress, ApiAccount, ApiSecretKey);

Dictionary<string, string> dtn = new Dictionary<string, string>();
dtn.Add("id_product", product["ExtID"].ToString());
dtn.Add("id_product_attribute", product["ExtGroupID"].ToString());   // id_attribute_id is actually the combinationid

List<stock_available> stock = StockAvailableFactory.GetByFilter(dtn, null, null);

if (stock != null) 
{
   stock.First().quantity = stock.First().quantity + (int)Math.Floor(qtychange);
// DATA IS PERFECT UP TO THIS POINT
   StockAvailableFactory.Update(stock.First());  
}

 public void Update(Entities.stock_available StockAvailable)
{
  RestRequest request = this.RequestForUpdate("stock_availables", StockAvailable.id, StockAvailable);
  // DATA IS PERFECT UP TO THIS POINT

  this.Execute<Entities.stock_available>(request);  // NOW IT FALLS APART AND API RETURNS ERROR NULL REFERENCE.
}

**Comment by EduLeonPavon** [comment]
Hello @iang0ld 
Please, enable display php errors (https://github.com/Bukimedia/PrestaSharp/blob/master/Enable%20display%20errors%20in%20Prestashop.txt)
After that, run your code and paste the error.
Best regards.

**Comment by iang0ld** [comment]
Hi.  We have a problem.  I don’t have access to the site I use for testing.  It is a live site of a customer.

**Comment by guywang** [comment]
Hi 
I have the same issue as @iang0ld experienced (null reference when I tried to update the stock_available), any ideas to fix it?

Thanks
