### ISSUE TITLE
HttpStatusCode: Unauthorized

### ISSUE THREAD

**Issue by mistergiu** [Bukimedia/PrestaSharp#121]
Hi guys,
i get this error, in every case, with 104.4.0.

Also if i try to do this:

string BaseUrl = "http://www.mmm.it/api";
string Account = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
string Password = "";
ProductFactory pf = new ProductFactory(BaseUrl, Account, Password);
var p = pf.Get(446);

Anyone can help me?

MG

**Comment by EduLeonPavon** [comment]
Hello @mistergiu 
Please, enable display php erros.
Thanks.

**Comment by mistergiu** [comment]
Hi Leon,
i tried to enable php errors but without success.

Then I tried using as base url the domain without "www." prefix.
It works!
Maybe is a wrong DNS configuration.

Thanks for the help

MG

**Comment by EduLeonPavon** [comment]
:+1:
