### ISSUE TITLE
Update product

### ISSUE THREAD

**Issue by Tom60** [Bukimedia/PrestaSharp#122]
Hi,

I have got problem. I can't update my product.

response.StatusCode = BadRequest

This is my code:

 string BaseUrl = "http://ctiprestashop.pswebshop.com/api";
                string Account = "77INAJ5EC3A6H587WB1D7RHA7XHCZVDX";
                string Password = "";
                ProductFactory produkty = new ProductFactory(BaseUrl, Account, Password);
               
                product produkt = produkty.Get(3);
               
                produkt.id = 3;
                produkt.id_manufacturer = 1;
                produkt.id_category_default = 2;
                produkt.id_tax_rules_group = 2;
                produkt.id_shop_default = 1;
                produkt.price = 12;
                produkt.unity = "szt";
                produkt.active = 1;
                produkt.available_for_order = 1;
                produkt.show_price = 1;

                produkt.name.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(2, "name"));
                produkt.meta_description.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(2, ""));
                produkt.meta_keywords.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(2, ""));

                produkt.meta_title.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(2, ""));
                produkt.link_rewrite.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(2, ""));
                produkt.description.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(2, ""));
                produkt.description_short.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(2, ""));
                produkt.available_now.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(2, ""));
                produkt.available_later.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(2, ""));

                produkt.associations.categories.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.category((long)12));
                
                produkty.Update(produkt);

update category works normally

Thanks,
Tom

**Comment by EduLeonPavon** [comment]
Hello @Tom60 
Could you enable display errors? 
https://github.com/Bukimedia/PrestaSharp/blob/master/Enable%20display%20errors%20in%20Prestashop.txt

Regards.

**Comment by Tom60** [comment]
Solved :)  If I only update:

ProductFactory produkty = new ProductFactory(BaseUrl, Account, Password);
product produkt = produkty.Get(3);
produkt.price = 12;
produkt.name.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(2, "name"));
produkty.Update(produkt);

it works.
Thanks :)
