### ISSUE TITLE
Add image and download orders

### ISSUE THREAD

**Issue by Tom60** [Bukimedia/PrestaSharp#123]
I use prestasharp. It's great :) I can add and update category and products, but I have two problems.
When I want add Image for product, I have Internal Server Error.
And when I want to get orders I have a error.

ImageFactory obraz = new ImageFactory(BaseUrl, Account, Password);
obraz.AddProductImage((long)7, "D:\\1.png");

OrderFactory orders = new OrderFactory(BaseUrl, Account, Password);
List<order> list = orders.GetAll();

Could you help me?

**Comment by EduLeonPavon** [comment]
Hello @Tom60 
Please, enable display php errors.
Best regards.

**Comment by Tom60** [comment]
This is my errors  (Images)

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[76]]></code>
<message><![CDATA[An error occurred while copying image]]></message>
</error>
</errors>
</prestashop>
  HttpStatusCode: BadRequest

**Comment by EduLeonPavon** [comment]
Hello @Tom60 
I think that you have no permissions to write the images in your server.
Best regards.

**Comment by Tom60** [comment]
Yes, You are right :)
Thank You @EduLeonPavon

**Comment by EduLeonPavon** [comment]
You are welcome :+1:
