### ISSUE TITLE
ProductFeatureValueFactory filter by ID

### ISSUE THREAD

**Issue by mistergiu** [Bukimedia/PrestaSharp#124]
Hi all,
I have to write Product Features, but I can't find the value corresponding to database field id_product.

Here's the code

ProductFeatureValueFactory pfvf = new ProductFeatureValueFactory(BaseUrl, Account, Password); 
Dictionary<string, string> dtn = new Dictionary<string, string>();
dtn.Add("id", "1");
var prodfeat = pfvf.GetByFilter(dtn2, null, null);
foreach (var p  in prodfeat) {
        console.write(p.id.ToString());
}

But p.id is not the product id

How can I list every features filtered by prod id?

MG

**Comment by EduLeonPavon** [comment]
Hello @mistergiu 
You have to add product associations (product->associations->product_features)
Best regards.

**Comment by mistergiu** [comment]
Hello Leon,
can you give me som example on how to add a feature having the feature id, feature value and the prod id?
