### ISSUE TITLE
Description string, how to get it?

### ISSUE THREAD

**Issue by MidnightBolt** [Bukimedia/PrestaSharp#125]
Hello,

Thank you for this library, it is making my life so much easier. I must say I'm a beginner in c# so this may be a dumb question I don't know.

I do not seem te be able to figure out how to get to the name or description string of a product.

`List<Bukimedia.PrestaSharp.Entities.product> productList = productFactory.GetAll();`

this gives me the product list it works. but how do you get to the strings?

I read in an answers from you on another topic this code:
`string name = GetValueFromLanguage(product.name.languages, language);` But I don't seem to find this function `GetValueFromLanguage`

Regards.

**Comment by EduLeonPavon** [comment]
Hello @MidnightBolt 
You can find the name (or description) of a product in the object:
product.name[i].Value
Regards.

**Comment by MidnightBolt** [comment]
Hi,

I did not realize the name property of the product entity was a list of language entities. So I got it working now and also get the idea in regards to other relations of entities.

Again thank you for a wonderful tool that makes life tremendously easier for us integrators. Also many thanks for the very quick response to this (rather trivial) question!

Kind regards.

**Comment by EduLeonPavon** [comment]
You are welcome :+1:
