### ISSUE TITLE
Ability to select display fields

### ISSUE THREAD

**Issue by msp1974** [Bukimedia/PrestaSharp#129]
Hi,

Firstly, this is a fantastic project - well done and thanks!!  It has saved me heaps of time.

I have a shop with about 500 categories and over 11,000 products.  I have developed an application  to improve speed of managing products and adding images/descriptions etc. It was originally developed for a Virtuemart shop but now trying to port to Prestashop.

This tool loads the category tree structure on load.

The problem I have is that when I do a getAll on the categories class to get the list to populate the tree, this also returns all the products associated to each category.  This in itself is not a problem except that it is really slow because of the amount of data it has to return, most of which I don't need.  I have seen it frequently error with a timeout.

I have added to the getByFilter the ability to pass the display fields and now use this to return just the 4 fields I need with no filter applied.  Speed is a step change improvement.  The getAll api then just passes 'full' as the display parameter.

I think this would be a great feature to add into PrestaSharp to ensure the developer can maximise performance of the webservice.

Thanks

**Comment by ak293700** [comment]
Hello in product is it possible to only fetch products.associations.categories ?
I would like not to fetch other products.associations attributes.
