### ISSUE TITLE
Api just working when _PS_MODE_DEV_ is true.

### ISSUE THREAD

**Issue by MesutMercan** [Bukimedia/PrestaSharp#132]
Hi,

Thank you for great api.

I was getting "Object reference not set" error, I changed _PS_MODE_DEV_ to true and now working. when i switch it to false again, I'm getting same error again.

Thank you.

**Comment by EduLeonPavon** [comment]
Hello,
Please, paste here the response message with dev mode enabled.
Thanks.

**Comment by MesutMercan** [comment]
Here is my full response with dev mode enabled.


HTTP/1.1 200 OK
Date: Mon, 16 Mar 2015 13:44:35 GMT
Server: Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips DAV/2 mod_bwlimited/1.4 PHP/5.3.29
X-Powered-By: PrestaShop Webservice
Access-Time: 1426513475
PSWS-Version: 1.6.0.6
Execution-Time: 0.031
Content-Sha1: 7fce31254ca1285d5fc66ed396d3e55a3cd103d6
Content-Length: 7082
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/xml;charset=utf-8

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<products>
<product>
	<id><![CDATA[346]]></id>
	<id_manufacturer><![CDATA[0]]></id_manufacturer>
	<id_supplier><![CDATA[0]]></id_supplier>
	<id_category_default xlink:href="http:///api/categories/6"><![CDATA[6]]></id_category_default>
	<new></new>
	<cache_default_attribute><![CDATA[0]]></cache_default_attribute>
	<id_default_image xlink:href="http:///api/images/products/346/16593" not_filterable="true"><![CDATA[16593]]></id_default_image>
	<id_default_combination not_filterable="true"></id_default_combination>
	<id_tax_rules_group xlink:href="http:///api/tax_rule_groups/1"><![CDATA[1]]></id_tax_rules_group>
	<position_in_category not_filterable="true"><![CDATA[21]]></position_in_category>
	<manufacturer_name not_filterable="true"></manufacturer_name>
	<quantity not_filterable="true"><![CDATA[0]]></quantity>
	<type not_filterable="true"><![CDATA[simple]]></type>
	<id_shop_default><![CDATA[1]]></id_shop_default>
	<reference><![CDATA[bb_G2000102]]></reference>
	<supplier_reference></supplier_reference>
	<location></location>
	<width><![CDATA[0.000000]]></width>
	<height><![CDATA[0.000000]]></height>
	<depth><![CDATA[0.000000]]></depth>
	<weight><![CDATA[0.898000]]></weight>
	<quantity_discount><![CDATA[0]]></quantity_discount>
	<ean13><![CDATA[2011041916333]]></ean13>
	<upc></upc>
	<cache_is_pack><![CDATA[0]]></cache_is_pack>
	<cache_has_attachments><![CDATA[0]]></cache_has_attachments>
	<is_virtual><![CDATA[0]]></is_virtual>
	<on_sale><![CDATA[0]]></on_sale>
	<online_only><![CDATA[0]]></online_only>
	<ecotax><![CDATA[0.000000]]></ecotax>
	<minimal_quantity><![CDATA[1]]></minimal_quantity>
	<price><![CDATA[4.680000]]></price>
	<wholesale_price><![CDATA[3.330000]]></wholesale_price>
	<unity></unity>
	<unit_price_ratio><![CDATA[0.000000]]></unit_price_ratio>
	<additional_shipping_cost><![CDATA[0.00]]></additional_shipping_cost>
	<customizable><![CDATA[0]]></customizable>
	<text_fields><![CDATA[0]]></text_fields>
	<uploadable_files><![CDATA[0]]></uploadable_files>
	<active><![CDATA[1]]></active>
	<redirect_type><![CDATA[404]]></redirect_type>
	<id_product_redirected><![CDATA[0]]></id_product_redirected>
	<available_for_order><![CDATA[1]]></available_for_order>
	<available_date><![CDATA[0000-00-00]]></available_date>
	<condition><![CDATA[new]]></condition>
	<show_price><![CDATA[1]]></show_price>
	<indexed><![CDATA[1]]></indexed>
	<visibility><![CDATA[both]]></visibility>
	<advanced_stock_management><![CDATA[0]]></advanced_stock_management>
	<date_add><![CDATA[2012-05-21 10:27:21]]></date_add>
	<date_upd><![CDATA[2015-02-21 16:45:02]]></date_upd>
	<meta_description><language id="7" xlink:href="http:///api/languages/7"></language></meta_description>
	<meta_keywords><language id="7" xlink:href="http:///api/languages/7"></language></meta_keywords>
	<meta_title><language id="7" xlink:href="http:///api/languages/7"></language></meta_title>
	<link_rewrite><language id="7" xlink:href="http:///api/languages/7"><![CDATA[rocking-weight-tostehantlid-naistele]]></language></link_rewrite>
	<name><language id="7" xlink:href="http:///api/languages/7"><![CDATA[Rocking Weight tõstehantlid naistele]]></language></name>
	<description><language id="7" xlink:href="http:///api/languages/7"><![CDATA[<p><strong>Osta telerist n&auml;htud&nbsp;Rocking Weight t&otilde;stehantlid naistele parima hinnaga.]]></language></description>
	<description_short><language id="7" xlink:href="http:///api/languages/7"></language></description_short>
	<available_now><language id="7" xlink:href="http:///api/languages/7"></language></available_now>
	<available_later><language id="7" xlink:href="http:///api/languages/7"></language></available_later>
<associations>
<categories node_type="category">
	<category xlink:href="http:///api/categories/6">
	<id><![CDATA[6]]></id>
	</category>
	<category xlink:href="http:///api/categories/7">
	<id><![CDATA[7]]></id>
	</category>
	<category xlink:href="http:///api/categories/10">
	<id><![CDATA[10]]></id>
	</category>
	<category xlink:href="http:///api/categories/50">
	<id><![CDATA[50]]></id>
	</category>
	<category xlink:href="http:///api/categories/90">
	<id><![CDATA[90]]></id>
	</category>
	<category xlink:href="http:///api/categories/112">
	<id><![CDATA[112]]></id>
	</category>
	<category xlink:href="http:///api/categories/166">
	<id><![CDATA[166]]></id>
	</category>
</categories>
<images node_type="image">
	<image xlink:href="http:///api/images/products/346/16590">
	<id><![CDATA[16590]]></id>
	</image>
	<image xlink:href="http:///api/images/products/346/16591">
	<id><![CDATA[16591]]></id>
	</image>
	<image xlink:href="http:///api/images/products/346/16592">
	<id><![CDATA[16592]]></id>
	</image>
	<image xlink:href="http:///api/images/products/346/16593">
	<id><![CDATA[16593]]></id>
	</image>
</images>
<combinations node_type="combinations"/>
<product_option_values node_type="product_options_values"/>
<product_features node_type="product_feature"/>
<tags node_type="tag"/>
<stock_availables node_type="stock_available">
	<stock_available xlink:href="http:///api/stock_availables/286">
	<id><![CDATA[286]]></id>
	<id_product_attribute><![CDATA[0]]></id_product_attribute>
	</stock_available>
</stock_availables>
<accessories node_type="product"/>
<product_bundle node_type="products"/>
</associations>
</product>
</products>
</prestashop>

**Comment by MesutMercan** [comment]
Here is my full response with dev mode enabled.

http://pastebin.com/W8fk0t4k

**Comment by GiorgioConte** [comment]
Hi all,
try this http://forge.prestashop.com/browse/PSCSX-4403
