### ISSUE TITLE
Cannot update product quantities

### ISSUE THREAD

**Issue by zetosa** [Bukimedia/PrestaSharp#136]
Simple code:

string BaseUrl = *********************_;
string Account = ***_******************;
string Password = "";
var stockFactory = new Bukimedia.PrestaSharp.Factories.StockAvailableFactory(BaseUrl, Account, Password);
var stock = stockFactory.Get(56);

// Up to this point everything is fine. The stock is downloaded from server.
stock.quantity = 100;
stockFactory.Update(stock);  //!!!!

On Update I have an exception:
http://pastebin.com/TbwAbfS5

What am I doing wrong?

**Comment by neboki** [comment]
Hi, 

I have had the same issue an I have resolved in this way.

prestashopProduct = productFactory.Get(170105); // Get the product
prestashopProduct.unity = "99"; // New Stock
prestashopProduct.associations = null;
productFactory.Update(prestashopProduct); // Update the stock.

Now my problem is that in the database´s the new stock quantity is updated but not in the backoffice.
