### ISSUE TITLE
Prestashop Changes List

### ISSUE THREAD

**Issue by RCallejo2** [Bukimedia/PrestaSharp#142]
Hi,

Sorry, I am very new on "Presta" and maybe my questins are very trivials but...

1.- Is it there a way to have a JUST a list of all the changes performed in prestashop?. I mean product changes, prizes, quantity stocks, new orders,,

So from a .net application I can update our local database just for those changes produced. Should I go table by table checking for updated field?

2.- Is it possible to do massive upload/download of products, customers, etc?

Thanks in advance for your patience.

**Comment by EduLeonPavon** [comment]
Hello @RCallejo2
PrestaSharp is a light proxy of PrestaShop to build more complex sync programs. Advanced features are not considered in this project.
Best regards.
