### ISSUE TITLE
Ability to retrive "Status code" and "error message" when call Add/Update/Delete

### ISSUE THREAD

**Issue by peterskalski** [Bukimedia/PrestaSharp#144]
When calling methods Add / Update / Delete, they could return the status of execution (200 OK 201 Created, 302 Found etc.). These messages can help a lot.

**Comment by EduLeonPavon** [comment]
Hello @peterskalski 
You can get the response status code if PrestaSharpException is thrown. Otherwise, you get the data object. Feel free to rewrite the Execute method for features you need.
Best regards.
