### ISSUE TITLE
Sizes and Colours

### ISSUE THREAD

**Issue by RCallejo2** [Bukimedia/PrestaSharp#146]
Which class deals with Sizes and Colors?. With so many features, atributes and etc, etc this is a little bit conffusing. What are atributes and features? Differences between them?

I want to congratulate all the Prestasharp team. You are doing a good job.
Thanks in advance.

**Comment by EduLeonPavon** [comment]
Hello @RCallejo2 
You have to use combination and stock_available entities.
Best regards.
