### ISSUE TITLE
Add or Update images to product

### ISSUE THREAD

**Issue by fredoche1810** [Bukimedia/PrestaSharp#148]
Hello,

With the included function AddProductImage() I can add an image to a product.
When I create a product I can't find how to define the position, the cover and the legend of that image.
When I want to update the images of my product, how can I know which is in position 1, 2 and so on ? I receive the ID of the image but not the others columns of the table is that right ?

Thanks before for your help

**Comment by EduLeonPavon** [comment]
Hello @fredoche1810 
That´s not possible to do it from the PrestaShop API.
Best regards.
