### ISSUE TITLE
Simple Combination and Association Example (II).

### ISSUE THREAD

**Issue by RCallejo2** [Bukimedia/PrestaSharp#150]
I am very sorry for insisting in this issue but I have already invest more time (and headache..) than I can stand trying to make this work. I would need a simple example of how to implement the next:

1.- Create a combination (Size,Color) and "associate" it to the product.
2.- Create an association (Categories of a product) and how to "associate" it to the product.

I appreciate very much your support.

**Comment by EduLeonPavon** [comment]
Hello @RCallejo2 
First, I think you need to familiarize with the PrestaShop entities. I suggest to discover the properties of each entity to understand the relationships each other. Every object has the "associations" property which links to other entities. Take a look:

http://doc.prestashop.com/display/PS14/Chapter+2+-+Discovery+-+Testing+access+to+the+web+service+with+the+browser

Best regards.
