### ISSUE TITLE
Update Category level_depth not writable

### ISSUE THREAD

**Issue by fredoche1810** [Bukimedia/PrestaSharp#151]
Hello,
I can create a category but when I try to update the category, I've got an error :+1: <![CDATA[parameter "level_depth" not writable. Please remove this attribute of this XML]]>

When I check the schema the level_depth isn't there. In my code, I don't try to give a value to this attribute. 

Bukimedia.PrestaSharp.Entities.category MyCategory = category; //EXISTING CATEGORY ENTITY LOADED BY GET
MyCategory.description.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(1, "description_fr"));
CategoryFactory.Update(MyCategory);

In the complete XML in the error the attributelevel_depth is there.

How can I remove that attribute?

Best regards,

**Comment by EduLeonPavon** [comment]
Hello @fredoche1810 
Please, sync your code.
Thanks a lot.
