### ISSUE TITLE
Error product.get after adding new product

### ISSUE THREAD

**Issue by Briasoft** [Bukimedia/PrestaSharp#152]
I've used Product factory.add to create a new product, everything seems to be ok and the request
of insert works fine. (I can see my product in the catalog on the prestashop backend).
In the product factory cs after the insert the program makes a get with the id of the new product and this throws an exception "Underlying connection closed", from now on if I try to get the product by id or even by filter the error is always the same.
If I try to read and update a product create by backend everything works fine.

Any idea of what can I've missed in the product creation?
Thanks

**Comment by EduLeonPavon** [comment]
Hello @Briasoft 
Could you tell me your PrestaShop version?
Thank you.

**Comment by Briasoft** [comment]
The version is 1.6.0.14
