### ISSUE TITLE
Duplicate Order State when saving back entity

### ISSUE THREAD

**Issue by TOLDOTECHNIK** [Bukimedia/PrestaSharp#153]
Each time we save back an order, the current order state gets duplicated and a new email is generated for the customer. Is this a PrestaShop or a PrestaSharp issue?

Sample Code:
Dim OrderFactory As New OrderFactory(URL, KEY, "")
Dim order As order
order = OrderFactory.Get(1)
order.shipping_number = "123456"
OrderFactory.Update(order)

**Comment by EduLeonPavon** [comment]
Hello @TOLDOTECHNIK 
We are trying to replicate the issue. Maybe, it´s related with PrestaShop but I´m not sure.
Best regards.

**Comment by TOLDOTECHNIK** [comment]
Hi,

We just added the order_invoices factory/entity. Could you please add them
to your github repository?

Regards,
Michael

<http://www.toldotechnik.li>

Michael Toldo | Geschäftsführer
Mobil: +41 (0) 76 393 53 68 | michael.toldo@toldotechnik.li

TOLDO TECHNIK
Im Meierhof 7 | LI - 9495 Triesen
Tel: +423 376 93 45 | info@toldotechnik.li
http://www.toldotechnik.li

2015-07-22 9:31 GMT+02:00 Eduardo León Pavón <notifications@github.com>:

**Comment by EduLeonPavon** [comment]
Hello @TOLDOTECHNIK 
You can do a pull request.
Thank you.

**Comment by TOLDOTECHNIK** [comment]
Need no resolution for this anymore.
