### ISSUE TITLE
Can't get the List of all Orders !

### ISSUE THREAD

**Issue by LuckyPed** [Bukimedia/PrestaSharp#154]
Hello,
I write an extremely simple program just to see if i can get the list of all my Orders, or the last 5 , well neither worked and both gave error , while other factories worked , I copy paste my simple code,

I commented order_history and manufacturer , they both work  ! but Order one not work !
I tried using Filter but still not work 

        private void ConnectButton_Click(object sender, RoutedEventArgs e)
        {
            string BaseUrl = "http://www.MySite.net/api";
            string Account = "MyAPI";
            string Password = "";

            //ManufacturerFactory ManufacturerFactory = new ManufacturerFactory(BaseUrl, Account, Password);

            //List<manufacturer> manufacturers = ManufacturerFactory.GetAll();

            OrderFactory Orders = new OrderFactory(BaseUrl, Account, Password); 
                        
            //Dictionary<string, string> dtn = new Dictionary<string, string>();
            //dtn.Add("name", "Metallica");

            List<order> AllOrders = Orders.GetAll();

            //OrderHistoryFactory OrderHis = new OrderHistoryFactory(BaseUrl, Account, Password);

            //List<order_history> AllOrderHis = OrderHis.GetAll();

        }

The Error is : 

     An unhandled exception of type 'Bukimedia.PrestaSharp.PrestaSharpException' occurred in Bukimedia.PrestaSharp.dll
     Additional information: 
     full
     "MyAPI"
     Basic "SomeCode"
     text/xml
     <?xml version="1.0" encoding="UTF-8"?>
     <prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
     <errors>
     <error>
     <message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>
     </error>
     <error>
     <message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>
     </error>
     <error>
     <message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>
     </error>
     <error>
     <message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>
     </error>
     <error>
     <message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>
     </error>
     </errors>
     </prestashop>
     Object reference not set to an instance of an object. HttpStatusCode: InternalServerError

**Comment by EduLeonPavon** [comment]
Hello @LuckyPed ,
Please, enable display PHP errors.
Thank you.

**Comment by EduLeonPavon** [comment]
Hello again,
Please, update your PrestaShop to PS 1.6.1
It seems a bug of previous versions.
Best regards.

**Comment by kawther201** [comment]
Hello, 
I can't connect to the link of my webservice prestatshop 1.7
I got this error:

"Une tentative d’accès à un socket de manière interdite par ses autorisations d’accès a été tentée Une tentative d’accès à un socket de manière interdite par ses autorisations d’accès a été tentée"

Please help me!
