### ISSUE TITLE
PrestaSharp FrameWork 3.5

### ISSUE THREAD

**Issue by lolkabagm** [Bukimedia/PrestaSharp#155]
Quisiera saber si es posible implementar esta librería en el framework de microsoft 3.5, ya que estoy realizando una conexión con un erp que utiliza 3.5, y da error. 

Actualmente PrestaSharp utiliza la versión 4.5. Hay versión para 3.5 ?

Gracias

**Comment by EduLeonPavon** [comment]
Hello @lolkabagm 
You can make a PrestaSharp version compatible with .net framework 3.5
You will have to remove all references to the namespaces only available in framework 4.5
Best regards.

**Comment by lolkabagm** [comment]
Gracias por responder.

He modificado la version de .net frameWork que utiliza a la 3.5, pero me da muchos errores, supongo que te refieres a esos que tengo que cambiar los espacios de nombres.

Tengo otro error,  utilizo la librería RestSharp , pero cambiando a la versión 3.5 de prestasharp me da error. Hay alguna solución viable?

Gracias!
