### ISSUE TITLE
ExecuteForFilter Doesn't work

### ISSUE THREAD

**Issue by fravezzimattia** [Bukimedia/PrestaSharp#158]
this is my code:
           var categoryFactory = new CategoryFactory(BaseUrl, Account, Password);
           var categories = categoryFactory.GetAll();

But this code return me an error : "System.Windows.pdb not loaded"

Debugging it step by step it's blocking when it call this function:  
this.ExecuteForFilter<List<Entities.manufacturer>>(request)

NB: Doesn't enter in function.

**Comment by EduLeonPavon** [comment]
Hello @fravezzimattia 
What kind of project are you deploying?
Thanks.

**Comment by fravezzimattia** [comment]
Hi @EduLeonPavon 

My project is a PCL,  I add to references PrestaSharp.dll   and RestSharp.dll

**Comment by EduLeonPavon** [comment]
Hello @fravezzimattia 
I can´t replicate the issue. Consider using Get method by id. You can get the whole list of ids.
Regards.

**Comment by mowcixo** [comment]
Hello @fravezzimattiaj, it should work now, as the library is compatible with .NET Standard. Please, try and let us know.
