### ISSUE TITLE
Category.position changes when updated

### ISSUE THREAD

**Issue by RCallejo2** [Bukimedia/PrestaSharp#160]
Hi everybody,
First of all, congratullations to all team for this interface you are developing. It would have been impossible for me to achieve my goals without this unvaluable tool and support.

A couple of questions:
1.- When updating a Category, Category position goes to the end of the list even when forzing value position. I would like to maintain the same position. Is it possible?

2.- I am interested in using LoggerLibrary. I know that Eduardo is the leader/author of this library. Can I have any example of how to implement an instance of it?

Thanks in advance.

**Comment by EduLeonPavon** [comment]
Hello @RCallejo2 
First of all, thanks to you for using PrestaSharp.
1) Could you paste the xml request and the xml response after update the category?
2) I´ll try to make a sample of LoggerLibrary.
Regards.

**Comment by RCallejo2** [comment]
Hi Eduardo,
1) I would do it If I knew how to do it. Could you give me some guidelines?

Thank you

**Comment by EduLeonPavon** [comment]
Hello @RCallejo2 
You´ll have to set a breakpoint in Bukimedia.PrestaSharp.Factories.RestSharpFactory.cs line 38.
Look inside 'Request' and 'response' content.
Regards.

**Comment by RCallejo2** [comment]
Sorry Edu.
I do not find the way to export xml content from watch window. I am using VS2013. Could you tell me how to do it?
Thanks a lot.

**Comment by SirDev** [comment]
See the screenshot:
![image](https://cloud.githubusercontent.com/assets/2150482/10215278/77fbefa0-6820-11e5-8cce-ab225fddd02f.png)

**Comment by IcuScc** [comment]
Hi friends. 
In Prestashop 1.7 i have the same problem. When i update a category i lost the position.

There are a solution?
Thanks :-)

**Comment by johndoe1395** [comment]
> Hi friends.
> In Prestashop 1.7 i have the same problem. When i update a category i lost the position.
> 
> There are a solution?
> Thanks :-)

This is a bug in Presta 1.7.5 (not PrestaSharp). Update to 1.7.6, it is fixed.
