### ISSUE TITLE
Edit image on category don't update and make category 404

### ISSUE THREAD

**Issue by meron1122** [Bukimedia/PrestaSharp#161]
This issue like topic, after
                ```this.ImageFactory.UpdateCategoryImage((long)PrestaCategory.id, BinaryData.Filepath);```

Category always return 404, and image didn't update, what I'm doing wrong?
Imo CateogryFactory don't return nLeft and nRight..
Prestashop 1.6.1.0

**Comment by EduLeonPavon** [comment]
Hello @meron1122 
Have you tried to delete the photography?
Regards.

**Comment by meron1122** [comment]
I workaround this by  check if image exist, remove and add again. This is stupid, imo method update should add image if not exist, or update if exist.

**Comment by EduLeonPavon** [comment]
You are right but this is the only way you can update a photo using the PrestaShop API.
Regards.
