### ISSUE TITLE
Adding new order results in NullReferenceException?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Bukimedia/PrestaSharp#163]
After looking at schema for the `order` to see what fields are required, I entered all required fields and made a cart and a customer and added a proudct to the cart like the following:

```
var productFactory = new ProductFactory(baseUrl, serviceKey, pass);
var product = productFactory.GetAll().First();

var cartFactory = new CartFactory(baseUrl, serviceKey, pass);
var cart = new cart();
cart.id_currency = 2; // euro
cart.id_lang = 1; // english
cart.associations.cart_rows = new List<cart_row>() { new cart_row { id_product = product.id, quantity = 3, id_address_delivery = 1, id_product_attribute = 1 } };
var newCart = cartFactory.Add(cart); // <-- THIS WORKS AS EXPECTED!
```

and now adding the order:

```
var order = new order();
order.id_address_delivery = 1;
order.id_address_invoice = 1;
order.id_cart = addedCart.id;
order.id_currency = 2; // euro
order.id_lang = 1; // english
order.id_customer = 2; // zaid
order.id_carrier = 1; // pick up at store
order.module = "cheque";
order.payment = "Payment by check";
var price = product.price;
order.total_paid = price;
order.total_paid_real = price;
order.total_products = price;
order.total_products_wt = price;
order.valid = 1;
var orderFactory = new OrderFactory(baseUrl, serviceKey, pass);
orderFactory.Add(order); //  <--- I GET THE (NULL) EXCEPTION HERE, NO IDEA WHERE EXACTLY IT ORIGINATED
```

Any help (or small tutorial on how to add a new order) would be appreciated!

**Comment by EduLeonPavon** [comment]
Hello @Zaid-Ajaj 
Please, enable "display PHP errors" in PrestaShop. You must find a more detailed error in the exception.
Thank you for your feedback.

**Comment by jakobt** [comment]
Please see pull request. In theory its bad behaviour on prestashops part but it doesn't hurt to handle it nicely here

**Comment by alescaltro** [comment]
hello, thank for your valuable work.I have the same problem, when i try to add one new order i receive the null exception. 
Fist i read the last order from prestashop server, and i modify only **date_add**, **date_upd**, **reference**, **secure_key** and **cart_id**.
The **cart_id** refer to a new cart created in the same manner of the order: i read the cart list and i copy the last cart updating the **date_add** and **date_upd**.
Can'you help me?

**Comment by alescaltro** [comment]
Hi the server response is:

<![CDATA[97]]></code>\n<message><![CDATA[[SQL Error] You can't specify target table 'ps_order_invoice' for update in FROM clause. From OrderCore->setLastInvoiceNumber() Query was : UPDATE `ps_order_invoice` SET number =(SELECT new_number FROM (SELECT (MAX(`number`) + 1) AS new_number\n\t\t\tFROM `ps_order_invoice`) AS result) WHERE `id_order_invoice` = 16]]></message>\n</error>\n</errors>\n</prestashop>\n  HttpStatusCode: InternalServerError"

What can i do to solve this problem?

**Comment by EduLeonPavon** [comment]
Hello,
Please, check these links:
https://www.prestashop.com/forums/topic/493410-error-on-order-status-change/
https://github.com/PrestaShop/PrestaShop/commit/34ad2f5f45e8b02ce7c3174d94644d6114399746
Regards.

**Comment by alescaltro** [comment]
Thanks,

for your’s reply but I solved the problem adding a waiting time (>60 sec) between the creation of the cart and creation of the order.

 

Regards

 

Alessandro

 

 

Da: Eduardo León Pavón [mailto:notifications@github.com] 
Inviato: venerdì 16 settembre 2016 16:39
A: Bukimedia/PrestaSharp <PrestaSharp@noreply.github.com>
Cc: alescaltro <alessandro.scaltritti@oroplatino.eu>; Comment <comment@noreply.github.com>
Oggetto: Re: [Bukimedia/PrestaSharp] Adding new order results in NullReferenceException? (#163)

 

Hello,
Please, check these links:
https://www.prestashop.com/forums/topic/493410-error-on-order-status-change/
PrestaShop/PrestaShop@ <https://github.com/PrestaShop/PrestaShop/commit/34ad2f5f45e8b02ce7c3174d94644d6114399746> 34ad2f5
Regards.

**Comment by amysticool** [comment]
Hello all,

I have exactly the same problem. iused the same code for performing an order but unable to Add an order. I'm not a specialist so here is the server response if anyone know what's happening Thanks a lot.

> System.Exception : 'Prestashop failed to serve XML response instead got text: 
Fatal error: Uncaught exception 'PrestaShopException' with message 'Fatal error' in /opt/bitnami/apps/prestashop/htdocs/classes/Tools.php:964
Stack trace:
#0 /opt/bitnami/apps/prestashop/htdocs/classes/PaymentModule.php(236): ToolsCore::displayError()
#1 /opt/bitnami/apps/prestashop/htdocs/classes/order/Order.php(1628): PaymentModuleCore->validateOrder('26', '11', '50', 'Ch\xC3\xA8que', NULL, Array, NULL, false, '75be46b4cb3404c...')
#2 /opt/bitnami/apps/prestashop/htdocs/classes/webservice/WebserviceRequest.php(1485): OrderCore->addWs()
#3 /opt/bitnami/apps/prestashop/htdocs/classes/webservice/WebserviceRequest.php(1299): WebserviceRequestCore->saveEntityFromXml(201)
#4 /opt/bitnami/apps/prestashop/htdocs/classes/webservice/WebserviceRequest.php(526): WebserviceRequestCore->executeEntityPost()
#5 /opt/bitnami/apps/prestashop/htdocs/webservice/dispatcher.php(87): WebserviceRequestCore->fetch('3QA69NFF4AI8FKI...', 'POST', 'orders', Array, false, '<prestashop>\n<o...')
#6 {main}
  thrown in /opt/bitnami/apps/prestashop/htdocs/classes/Tools.php on line 964

**Comment by mauriziozito** [comment]
i have the same error

System.Exception
  HResult=0x80131500
  Messaggio=Prestashop failed to serve XML response instead got text: 
Fatal error: Uncaught PrestaShopException: Errore fatale in /home/luxuryp6/public_html/luxurypetshop.eu/classes/Tools.php:1109
Stack trace:
#0 /home/luxuryp6/public_html/luxurypetshop.eu/classes/PaymentModule.php(254): ToolsCore::displayError()
#1 /home/luxuryp6/public_html/luxurypetshop.eu/classes/order/Order.php(1687): PaymentModuleCore->validateOrder('32', '11', '54.000000', 'Contrassegno', NULL, Array, NULL, false, 'f0c818714fe02d8...')
#2 /home/luxuryp6/public_html/luxurypetshop.eu/classes/webservice/WebserviceRequest.php(1566): OrderCore->addWs()
#3 /home/luxuryp6/public_html/luxurypetshop.eu/classes/webservice/WebserviceRequest.php(1370): WebserviceRequestCore->saveEntityFromXml(201)
#4 /home/luxuryp6/public_html/luxurypetshop.eu/classes/webservice/WebserviceRequest.php(565): WebserviceRequestCore->executeEntityPost()
#5 /home/luxuryp6/public_html/luxurypetshop.eu/webservice/dispatcher.php(87): WebserviceRequestCore->fetch('ZD4VAMTN2UQR99G...', 'POST', 'orders', Array, false, '<prestashop>\n<o...')
#6 {main}
  thro in /home/luxuryp6/public_html/luxurypetshop.eu/classes/Tools.php on line 1109

  Origine=Bukimedia.PrestaSharp
  Analisi dello stack:
   in Bukimedia.PrestaSharp.Deserializers.PrestaSharpTextErrorDeserializer.Deserialize[T](IRestResponse response) in C:\Users\mauri\Downloads\PrestaSharp-master\PrestaSharp-master\Deserializers\PrestaSharpTextErrorDeserializer.cs: riga 11
   in RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)

**Comment by mowcixo** [comment]
Hello @mauriziozito, it seems to be an error with your version of PrestaShop, not with PrestaSharp, see the comment below:

> Hello,
> Please, check these links:
> https://www.prestashop.com/forums/topic/493410-error-on-order-status-change/
> [PrestaShop/PrestaShop@34ad2f5](https://github.com/PrestaShop/PrestaShop/commit/34ad2f5f45e8b02ce7c3174d94644d6114399746)
> Regards.

I recommend you to upgrade your prestashop version if you can.
