### ISSUE TITLE
New product feature doesn't add entry for "Layered Navigation Block" module

### ISSUE THREAD

**Issue by radodr** [Bukimedia/PrestaSharp#164]
Hi,
I have PS 1.6.0.14 version.
When I add new feature with your API  call, then "Layered Navigation Block" module doesn't add this feature to filter. I can see only manually added features.
Is it bug, or should I use some other API calls if I want to have these features present in my filters?

Thank you.

**Comment by EduLeonPavon** [comment]
Hello @radodr 
It looks a PrestaShop API bug.
Regards.

**Comment by radodr** [comment]
Thank you for quick answer.
Where should I post it?

**Comment by EduLeonPavon** [comment]
Ok, try with the official PrestaShop forum.
