### ISSUE TITLE
Query products of third party

### ISSUE THREAD

**Issue by IgnacioMen** [Bukimedia/PrestaSharp#166]
hi,
I am interested in developing a program that accesses the full catalog of certain shops in PrestaShop. Is it possible or the authentication of PrestaSharp is valid only for own companies to access their catalogues?
I wonder if there is a centralised service of PrestaShop that allows to query catalogues of companies by using provided credentials for it.

Thanks

**Comment by EduLeonPavon** [comment]
Hello @IgnacioMen 
To access to the PrestaShop API you have to use a secret key so you have to be authorized to query the shop.
Regards.
