### ISSUE TITLE
Watermark 

### ISSUE THREAD

**Issue by fredoche1810** [Bukimedia/PrestaSharp#167]
Hello,
When I upload a picture, the module watermark doesn't have any effect.
The developer of the module test it in php with image factory and tell it's working.
When I add a picture from the back office it works also. I want to get it working with the webservive in c#.

I also tried the official module watermark that you have by default in prestashop but I've got the same result. It's working from the back office but not when I use the c# code and the web service. 

I also check that the module is in the hook watermark.

Can you try it out and let me know. I'm use prestashop 1.6.1.1

Thanks before,

**Comment by EduLeonPavon** [comment]
Hello @fredoche1810 
This issue is due to PrestaShop. Consider to post this issue in the PrestaShop forum.
Regards.
