### ISSUE TITLE
Prestasharp exception thrown when updating an enitity

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Bukimedia/PrestaSharp#170]
trying to do simply the following (in F#):

```
let factory =  OrderFactory(url, key, "")
let order = factory.Get(120L) 
order.current_state <- System.Nullable<int64>(1003L)
factory.Update(order)
```

results in some parsing exception from RestSharpFactory:

```
'=' is an unexpected token. The expected token is ';'. Line 133, position 65. HttpStatusCode: NotFound ---> System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 133, position 65.
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
at System.Xml.XmlTextReaderImpl.FinishPartialValue()
at System.Xml.XmlTextReaderImpl.get_Value()
at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
at RestSharp.Deserializers.XmlDeserializer.Deserialize[T](IRestResponse response)
at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)
--- End of inner exception stack trace ---
at Bukimedia.PrestaSharp.Factories.RestSharpFactory.Execute[T](RestRequest Request)
at Bukimedia.PrestaSharp.Factories.OrderFactory.Update(order Order)
```

how to fix this?

**Comment by EduLeonPavon** [comment]
Hello @Zaid-Ajaj 
First of all, thank you for using PrestaSharp. I would like to take a look to the "order" object.
Could you paste a screenshot with the content of the order object?
Thanks.

**Comment by Zaid-Ajaj** [comment]
Thank you for your replay! using Fiddler, I was able to get the PUT request data as follows:

    PUT http://bezorg.p495.nl/api/orders HTTP/1.1
    Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXX
    Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
    User-Agent: RestSharp/105.0.1.0
    Content-Type: application/xml
    Host: bezorg.p495.nl
    Content-Length: 3306
    Accept-Encoding: gzip, deflate

    <?xml version="1.0" encoding="utf-8"?>
    <prestashop>
    <order>
      <id xmlns="">430</id>
      <id_address_delivery xmlns="">538</id_address_delivery>
      <id_address_invoice xmlns="">538</id_address_invoice>
      <id_cart xmlns="">938</id_cart>
      <id_currency xmlns="">1</id_currency>
      <id_lang xmlns="">1</id_lang>
      <id_customer xmlns="">215</id_customer>
      <id_carrier xmlns="">39</id_carrier>
      <current_state xmlns="">1003</current_state>
      <module xmlns="">idealcheckoutideal</module>
      <invoice_number xmlns="">399</invoice_number>
      <invoice_date xmlns="">2015-09-15 18:20:36</invoice_date>
      <delivery_number xmlns="">0</delivery_number>
      <delivery_date xmlns="">0000-00-00 00:00:00</delivery_date>
      <valid xmlns="">1</valid>
      <date_add xmlns="">2015-09-15 18:19:31</date_add>
      <date_upd xmlns="">2015-09-15 18:20:37</date_upd>
      <id_shop_group xmlns="">1</id_shop_group>
      <id_shop xmlns="">1</id_shop>
      <secure_key xmlns="">8945990b6ab81a714dbc5056a143b2bb</secure_key>
      <payment xmlns="">iDeal</payment>
      <recyclable xmlns="">0</recyclable>
      <gift xmlns="">0</gift>
      <gift_message xmlns="" />
      <mobile_theme xmlns="">0</mobile_theme>
      <total_discounts xmlns="">0.000000</total_discounts>
      <total_discounts_tax_incl xmlns="">0.000000</total_discounts_tax_incl>
      <total_discounts_tax_excl xmlns="">0.000000</total_discounts_tax_excl>
      <total_paid xmlns="">19.900000</total_paid>
      <total_paid_tax_incl xmlns="">19.900000</total_paid_tax_incl>
      <total_paid_tax_excl xmlns="">18.770000</total_paid_tax_excl>
      <total_paid_real xmlns="">19.900000</total_paid_real>
      <total_products xmlns="">18.770000</total_products>
      <total_products_wt xmlns="">19.900000</total_products_wt>
      <total_shipping xmlns="">0.000000</total_shipping>
      <total_shipping_tax_incl xmlns="">0.000000</total_shipping_tax_incl>
      <total_shipping_tax_excl xmlns="">0.000000</total_shipping_tax_excl>
      <carrier_tax_rate xmlns="">21.000</carrier_tax_rate>
      <total_wrapping xmlns="">0.000000</total_wrapping>
      <total_wrapping_tax_incl xmlns="">0.000000</total_wrapping_tax_incl>
      <total_wrapping_tax_excl xmlns="">0.000000</total_wrapping_tax_excl>
      <shipping_number xmlns="" />
      <conversion_rate xmlns="">1.000000</conversion_rate>
      <reference xmlns="">ZVLCYQOHS</reference>
      <associations xmlns="">
        <order_rows xmlns="">
          <order_row>
            <id xmlns="">1004</id>
            <product_id xmlns="">172</product_id>
            <product_attribute_id xmlns="">17564</product_attribute_id>
            <product_quantity xmlns="">2</product_quantity>
            <product_name xmlns="">510. Burger menu - &lt;b&gt;Brood:&lt;/b&gt; Bun (Hamburger brood)&lt;br /&gt;&lt;b&gt;Burger menu:&lt;/b&gt; Cheese Burger&lt;br /&gt;&lt;b&gt;Burger grote:&lt;/b&gt; 250 gram&lt;br /&gt;&lt;b&gt;Drinken menu:&lt;/b&gt; Aa-drink&lt;br /&gt;&lt;b&gt;Fingerfood menu:&lt;/b&gt; Friet</product_name>
            <product_reference xmlns="" />
            <product_ean13 xmlns="" />
            <product_upc xmlns="" />
            <product_price xmlns="">9.386792</product_price>
            <unit_price_tax_incl xmlns="">9.950000</unit_price_tax_incl>
            <unit_price_tax_excl xmlns="">9.390000</unit_price_tax_excl>
          </order_row>
        </order_rows>
      </associations>
    </order>
    </prestashop>

I also tried to rewrite this functionality using RestSharp along with an Http module and XmlProvider (F# type providers) like the following:

    let update (orderId:int) stateId (cred:AuthInfo) = 
        let client = RestClient()
        client.Authenticator <- HttpBasicAuthenticator(cred.Key, "")
        let auth = BasicAuth cred.Key ""
        let orderApi = cred.Api + "orders/" + orderId.ToString();
        let orderAsXml = Http.RequestString(orderApi, httpMethod = "GET", headers = [auth])
        let xml = Order.Parse(orderAsXml).XElement // Order (xml type provider) provides statically typed access for an xml data source
        xml.Element(XName.Get("order")).Element(XName.Get("current_state")).SetValue(stateId)
        let xmlData = xml.ToString()    
        let request = RestRequest(cred.Api + "orders", Method.PUT);
        request.AddParameter("xml", xmlData, ParameterType.RequestBody) |> ignore;
        client.Execute(request);

and then call the function: `update 430 10 cred` which returns an `IRestResponse` with `ErrorException = System.ArgumentNullException: Value cannot be null.` I am not sure what exactly is null

Any help here would be appreciated.
