### ISSUE TITLE
Multitienda. Problema con las categories

### ISSUE THREAD

**Issue by juanmitr** [Bukimedia/PrestaSharp#173]
Hola:
¿Está Prestasharp preparado para trabajar con multitienda? ¿El servicio web de Prestashop lo permite? Lo digo porque había empezado con las categories y me las duplica en todas las tiendas, cuando yo sólo quiero que me la inserte en una concreta.
Si el servicio web lo permite y Prestasharp ahora no, me ofrezco para dejarlo preparado para que funcione bien, probado en una tienda real. Pero el problema es que no sé que debería hacer.
Muchas gracias.

**Comment by EduLeonPavon** [comment]
Hello @juanmitr 
You have to set the id_shop_default field in order to associate the shop to the category.
Regards.
