### ISSUE TITLE
ProductFactory.Update Error

### ISSUE THREAD

**Issue by StephanKoops** [Bukimedia/PrestaSharp#174]
I keep getting this error. Please advise.

<code><?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[97]]></code>
<message><![CDATA[[SQL Error] Duplicate entry '104-1-0' for key 'id_product'. From ProductCore->setCoverWs() Query was : UPDATE `ps_image_shop` image_shop, `ps_image` i
			SET image_shop.`cover` = 0
			WHERE i.`id_product` = 104 AND i.id_image = image_shop.id_image
			AND image_shop.id_shop=1]]></message>
</error>
</errors>
</prestashop></code>

**Comment by EduLeonPavon** [comment]
Hello @StephanKoops 
Please, take a look to this issue http://forge.prestashop.com/browse/PSCSX-6461
Regards.

**Comment by StephanKoops** [comment]
Thanks but, I do not like a "core" update. Now I first delete all images.
