### ISSUE TITLE
Add Carrier

### ISSUE THREAD

**Issue by techjp** [Bukimedia/PrestaSharp#175]
I can see that I can add a carrier to PrestaShop with the PrestaSharp Carrier Factory. However I can't see if it is possible to add a full carrier definition with multiple weight ranges and shipping costs. Is this possible to do? Am I missing something?

**Comment by EduLeonPavon** [comment]
Hello @techjp 
You need weight_ranges and zones entities. I invite you to create the needed factories and entities.
Best regards.

**Comment by techjp** [comment]
Eduardo, thank you for your reply.

I would be more than happy to work on this but I have not had any luck finding a way to add carrier pricing. Weight ranges seem quite doable, and I can see the call details for that. However for the life of me I can't find where prices are assigned for a given carrier+weight range+zone combination. As best I can tell this functionality is not yet supported by the PrestaShop API but I'm hoping to confirm this one way or another.

**Comment by techjp** [comment]
@EduLeonPavon 

I have figured out the API calls and am working on implementation. If I get it working I'll be happy to contribute the code.

**Comment by EduLeonPavon** [comment]
Hi @techjp 
Thanks in advance for your effort.
Best regards.
