### ISSUE TITLE
Auth problems

### ISSUE THREAD

**Issue by Shemes** [Bukimedia/PrestaSharp#178]
Just like #177 I was having troubles accessing the api over https, so I removed basic auth and included the ws_key token on the url. Here is my fork, I didn't know if a pull request would be useful, as it changes the way auth works, and maybe it's an prestashop API bug, that may be fixed in the future.

Anyway, If someone has any other ideas or want to use the file.

https://github.com/Bukimedia/PrestaSharp/compare/master...Shemes:patch-1?expand=1

**Comment by DoubleDim** [comment]
can you post the exact url please?
