### ISSUE TITLE
Associate a product with product_option_value

### ISSUE THREAD

**Issue by LitMB** [Bukimedia/PrestaSharp#185]
Hello,
my problem is how to associate an existing product (with given id_product) with one or more existing product_option_value (with given id_option_value).
I tried creating a new Combination and adding it with a CombinationFactory , but no success.

Can you please give some sample code line?

Thanks

**Comment by mulflar** [comment]
Try this
1.- With the product_factory use the Get(long ProductId) to download the product from prestashop
2.- For each id_option_value generate a AuxEntities.product_option_value and asign the id_option_value 
3.- Add all of this AuxEntities.product_option_value objects to product.associations.product_option_values
4.- Update the product to prestashop
