### ISSUE TITLE
Send Urlbase, acccount, password falure !

### ISSUE THREAD

**Issue by manhuyetxa** [Bukimedia/PrestaSharp#187]
I have installed nuget Bukimedia.PrestaSharp
I test web services with client.
with code:
Bukimedia.PrestaSharp.Entities.manufacturer Manufacturer = ManufacturerFactory.Get(0);
            Manufacturer.name = "Iron Maiden";
            Manufacturer.active = 1;
            ManufacturerFactory.Add(Manufacturer);
            ManufacturerFactory.Update(Manufacturer);
            ManufacturerFactory.Delete(Manufacturer);
error:
An unhandled exception of type 'Bukimedia.PrestaSharp.PrestaSharpException' occurred in Bukimedia.PrestaSharp.dll

**Comment by EduLeonPavon** [comment]
Hello,
I need more info about this.
Regards.

**Comment by manhuyetxa** [comment]
thank you for support. 
I done it.
