### ISSUE TITLE
Get orders through Date.add

### ISSUE THREAD

**Issue by 91Abdullah** [Bukimedia/PrestaSharp#189]
Can we use GetByFilter to retrieve only current date's orders?

**Comment by jagred** [comment]
check out this question (last post)
https://github.com/Bukimedia/PrestaSharp/issues/119

and then use filter like this

`   string dFrom = string.Format("{0:yyyy-MM-dd HH:mm:ss}", fromTime);
            string dTo = string.Format("{0:yyyy-MM-dd HH:mm:ss}", toTime);
            filter.Add("date_add", "[" + dFrom + "," + dTo + "]");`

**Comment by 91Abdullah** [comment]
Thanks jagred you saved life :)
