### ISSUE TITLE
Pull Sales Orders without Invoice Date

### ISSUE THREAD

**Issue by jmawebtech** [Bukimedia/PrestaSharp#190]
Hi,

Is it possible to pull sales orders before the invoice date has been assigned? I tried this code, but it fails and says there is no filter for date_add:

        public List<Entities.order> GetOrdersByDateRange(DateTime beginDate, DateTime endDate)
        {
            Dictionary<string, string> dtn = new Dictionary<string, string>();
            dtn.Add("date_add", MakeBrackets(beginDate.ToString("yyyy-MM-dd HH:mm:ss"), endDate.ToString("yyyy-MM-dd HH:mm:ss")));
            return GetByFilter(dtn, null, null);
        }

**Comment by EduLeonPavon** [comment]
Hello @jmawebtech 
It´s not possible with the PrestaShop API.
Best regards.
