### ISSUE TITLE
[SOLVED]Price with taxes on combinations 

### ISSUE THREAD

**Issue by mulflar** [Bukimedia/PrestaSharp#192]
When you upload a combination you can just send the price, and it goes directy as a increment of price without tax.
There is any way to upload a price with taxes?

**Comment by mulflar** [comment]
I solved by myself doing `price = priceRaw / (decimal)1.21;" for a tax of  21%`
Then you have to round to 6 `decimal.Round(precio, 4);` less can fail to calculate with acuracy and more can make the webservice crash.

**Comment by EduLeonPavon** [comment]
Nice :+1:
