### ISSUE TITLE
Example Create Item 

### ISSUE THREAD

**Issue by epp1628** [Bukimedia/PrestaSharp#193]
Hi,
is there any axample how to create an item with multilanguage fields.I haven't understand how to use AuxEntities.Thank's.

**Comment by mulflar** [comment]
You should do something like this:
`Bukimedia.PrestaSharp.Entities.AuxEntities.language key = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(1, Auxiliar.normalize(item));
                psarticulo.meta_keywords.Add(key);
                Bukimedia.PrestaSharp.Entities.AuxEntities.language key_es = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(3, Auxiliar.normalize(item));
                psarticulo.meta_keywords.Add(key_es);

            Bukimedia.PrestaSharp.Entities.AuxEntities.language link_rw = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(1, Auxiliar.normalizeLink(nombre));
            psarticulo.AddLinkRewrite(link_rw);
            Bukimedia.PrestaSharp.Entities.AuxEntities.language link_rw_ES = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(3, Auxiliar.normalizeLink(nombre));
            psarticulo.AddLinkRewrite(link_rw_ES);

            Bukimedia.PrestaSharp.Entities.AuxEntities.language name_sing = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(1, nombre.Trim());
            psarticulo.AddName(name_sing);
            Bukimedia.PrestaSharp.Entities.AuxEntities.language name_sing_ES = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(3, nombre.Trim());
            psarticulo.AddName(name_sing_ES);

            Bukimedia.PrestaSharp.Entities.AuxEntities.language desc_long = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(1, nombre.Trim());
            psarticulo.description.Add(desc_long);
            Bukimedia.PrestaSharp.Entities.AuxEntities.language desc_long_es = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(3, nombre.Trim());
            psarticulo.description.Add(desc_long_es);

            Bukimedia.PrestaSharp.Entities.AuxEntities.language desc_short = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(1, nombre.Trim());
            psarticulo.description_short.Add(desc_short);
            Bukimedia.PrestaSharp.Entities.AuxEntities.language desc_short_es = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(3, nombre.Trim());
            psarticulo.description_short.Add(desc_short_es);`

**Comment by epp1628** [comment]
Thank you very much . I tried this code:
` string BaseUrl = Properties.Resources.BaseUrl;
                string Account = Properties.Resources.Account;
                string Password = "";
                ProductFactory Factory = new ProductFactory(BaseUrl, Account, Password);
                Bukimedia.PrestaSharp.Entities.product itemToAdd = new Bukimedia.PrestaSharp.Entities.product();
                itemToAdd.active = 1;
                itemToAdd.available_for_order = 1;
                itemToAdd.id_shop_default = 1;
                itemToAdd.reference = Convert.ToString(row["GXDESCRIPTION"]);

                List<Bukimedia.PrestaSharp.Entities.AuxEntities.language> listNameLang = new List<Bukimedia.PrestaSharp.Entities.AuxEntities.language>();
                Bukimedia.PrestaSharp.Entities.AuxEntities.language name_gr = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(2, Convert.ToString(row["GXDESCRIPTION"]));
                Bukimedia.PrestaSharp.Entities.AuxEntities.language name_uk = new Bukimedia.PrestaSharp.Entities.AuxEntities.language(1, Convert.ToString(row["GXDESCRIPTION"]));
                listNameLang.Add(name_gr);
                listNameLang.Add(name_uk);

                itemToAdd.name = listNameLang;
                Factory.Add(itemToAdd);`

But it throws this excepetion:
`
<prestashop>
<product>
  <id_shop_default>1</id_shop_default>
  <on_sale>0</on_sale>
  <online_only>0</online_only>
  <ecotax>0</ecotax>
  <minimal_quantity>0</minimal_quantity>
  <price>0</price>
  <wholesale_price>0</wholesale_price>
  <unit_price_ratio>0</unit_price_ratio>
  <additional_shipping_cost>0</additional_shipping_cost>
  <reference>Σακίδιο Deuter Guide 45+ Backpack </reference>
  <width>0</width>
  <height>0</height>
  <depth>0</depth>
  <weight>0</weight>
  <customizable>0</customizable>
  <uploadable_files>0</uploadable_files>
  <text_fields>0</text_fields>
  <active>1</active>
  <id_product_redirected>0</id_product_redirected>
  <available_for_order>1</available_for_order>
  <show_price>0</show_price>
  <indexed>0</indexed>
  <cache_is_pack>0</cache_is_pack>
  <cache_has_attachments>0</cache_has_attachments>
  <is_virtual>0</is_virtual>
  <advanced_stock_management>0</advanced_stock_management>
  <meta_description />
  <meta_keywords />
  <meta_title />
  <link_rewrite />
  <name>
    <language id="2">Σακίδιο Deuter Guide 45+ Backpack </language>
    <language id="1">Σακίδιο Deuter Guide 45+ Backpack </language>
  </name>
  <description />
  <description_short />
  <available_now />
  <available_later />
  <associations>
    <categories />
    <images />
    <combinations />
    <product_option_values />
    <product_features />
    <tags />
    <stock_availables />
    <product_bundle />
    <accessories />
  </associations>
</product>
</prestashop>

3UJNUISGARZJX4YJKFD6FQ9UAXSYB6A3

Basic M1VKTlVJU0dBUlpKWDRZSktGRDZGUTlVQVhTWUI2QTM6

application/json, application/xml, text/json, text/x-json, text/javascript, text/xml

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>
</error>
</errors>
</prestashop>
  HttpStatusCode: BadRequest`

**Comment by mulflar** [comment]
Activate errors on prestashop to verify, but most sure is that prestashops need you to send him most of the fields

**Comment by epp1628** [comment]
Thank you very much for your help
