### ISSUE TITLE
how edit record of ps_product_attribute table

### ISSUE THREAD

**Issue by t3nano** [Bukimedia/PrestaSharp#197]
Hello
thank you for your work
i want select and edit records of ps_product_attribute table But I think that by default not any web service to access this table! is it right?
how can access to ps_product_attribute table values?
have  a good time

**Comment by EduLeonPavon** [comment]
Hello @t3nano 
Try with...
- Product Features
- Product Feature Values
- Product Options
- Product Option Values
Regards.

**Comment by t3nano** [comment]
thank you EduLeonPavon
Actually i want select all products with all attributes
for example :
Blouse | white | S | ps_product_reference | ps_product_attribute_reference
Blouse | black | S | ps_product_reference | ps_product_attribute_reference
Blouse | white | M | ps_product_reference | ps_product_attribute_reference
Blouse | black | M | ps_product_reference | ps_product_attribute_reference
Printed Dress | white | M | ...

can you help me?
thanks you

**Comment by t3nano** [comment]
No one to guide me?
I  need your help very much, please help me
thanks
