### ISSUE TITLE
Visual Studio 2010 no reconoce Referencia

### ISSUE THREAD

**Issue by Namauyoky** [Bukimedia/PrestaSharp#198]
Buena tarde, antes que nada agradecer por el desarrollo de la librería, soy nuevo utilizando el CMS Prestashop, y necesito por medio de mi ERP, registrar los clientes(customer) consumiendo el WebService, y en este caso por medio de su librería.
El problema que se me presenta es que agrego el paquete por medio de Consola del Administrador de Paquetes y me carga bien las referencias, y las puedo llamar desde código , el problema es cuando compilo el código no me hace referencia a la librería Agregada Bukimedia.PrestaSharp.

`//  
                            txtAfiliado.Text = NegocioHealthy.CDatosAlmacen.intMaxAfiliado.ToString();
                            ImprimirRegistro();

```
                        //Crear Cliente en PrestaShop usando Librería PrestaSharp


                        string BaseUrl = "http://tiendavirtual.com";
                        string Account = "QTM";
                        string Password = "";


                        Bukimedia.PrestaSharp.Factories.CustomerFactory CustomerFactory = new Bukimedia.PrestaSharp.Factories.CustomerFactory(BaseUrl, Account, Password);
                        List<Bukimedia.PrestaSharp.Entities.customer> ListClient = CustomerFactory.GetAll();
                        Bukimedia.PrestaSharp.Entities.customer Client = new Bukimedia.PrestaSharp.Entities.customer();

                        foreach (Bukimedia.PrestaSharp.Entities.customer tmpclient in ListClient)
                        {`
```

![bukimedia](https://cloud.githubusercontent.com/assets/18337837/14368920/786e8f46-fce6-11e5-99c2-6ca3ef1e3ee0.png)

Espero me puedan orientar y el haber escrito en español no sea una limitante, Gracias.

**Comment by mulflar** [comment]
¿Has probado con otro visual studio mas reciente?
