### ISSUE TITLE
Error al codificar filtros y añadir nuevos productos

### ISSUE THREAD

**Issue by txtxo** [Bukimedia/PrestaSharp#210]
He detectado que al buscar un producto con un filtro devuelve todos los resultados en vez de el que se ha solicitado.

Esta llamada se hace en la línea 93 de Factories/RestSharpFactory.cs
`var response = client.Execute<T>(Request);`

El valor de response.ResponseUri es: 

> https://dominio/api/products?display=full&filter%255Breference%255D=REFERENCIA&date=1&ws_key=xxxx

Ya que al estar mal codificado el corchete devuelve todos los productos en lugar de filtrar
Debería ser:

> https://dominio/api/products?display=full&filter[reference]=REFERENCIA&date=1&ws_key=xxxx

Al añadir productos supongo que el error será parecido ya que el ResponseUri es:

> https://dominio/api/products?ws_key=xxxx

**Comment by mulflar** [comment]
Buenas
A mi tambien me ha pasado.
La cosa es que el filtrado iba bien, pero tenia muchos problemas con un modulo del servidor (el mod_evasive), al pedir a hosting que me lo desactivaran es cuando he empezado a tener este problema con los filtros

**Comment by DorianCaup** [comment]
Hello,
This strongly looks like a url re-encoding.
The filter in the URL that you sent is encoded in UTF-8 and the server re-encodes it again.

Exemple :
http://yourapi.com/api/products?filter[id]=1
If you use UTF-8 you send : http://yourapi.com/api/products?filter%5bid%5d=1 to the server.
If the server has a redirection rule (http -> https), and if that rule encode again in UTF-8 :

http://yourapi.com/api/products?filter%255bid%255d=1 => Doesn't exist, replaced by  http://yourapi.com/api/products

Please, check if the web server has redirection rules.
