### ISSUE TITLE
Error running with new version of RestSharp

### ISSUE THREAD

**Issue by RCallejo2** [Bukimedia/PrestaSharp#212]
I have a solution working properly with restsharp version 105.1.0

I have updated RestSharp via nutget services to restsharp 105.2.3. When I compile, there is not any errors shown. But when running I get execution errors. Is it prestasharp compatible with last versión of RestSharp?

Thanks again for all.

**Comment by EduLeonPavon** [comment]
Hi @RCallejo2,
We are testing PrestaSharp with RestSharp 105.2.3.0 and we couldn´t throw any exception.
Could you give us more details? 
Regards.

**Comment by ToineSeiter** [comment]
Same issue :
`Could not load type 'RestSharp.HttpBasicAuthenticator' from assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null'.`

**Comment by annemartijn0** [comment]
Same issue: `2016-11-25T19:56:30.293 System.TypeLoadException: Could not load type 'RestSharp.HttpBasicAuthenticator' from assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null'.
   at Bukimedia.PrestaSharp.Factories.RestSharpFactory.ExecuteForFilter[T](RestRequest Request)
   at Bukimedia.PrestaSharp.Factories.ProductFactory.GetByFilter(Dictionary2 Filter, String Sort, String Limit)`

using Prestasharp 1.157 and RestSharp 105.2.3

**Comment by ToineSeiter** [comment]
The nuget package is outdated. Download the latest source of the repository and you won't have the issue anymore.

**Comment by annemartijn0** [comment]
I've created a nuget package that's published from commit a125b450098f0616f24e1d60c96ec50c22076085.
https://www.nuget.org/packages/Prestasharp-fork/1.0.0

**Comment by mowcixo** [comment]
We just released official NuGet package in release https://github.com/Bukimedia/PrestaSharp/releases/tag/1.0.0
