### ISSUE TITLE
Prestashop 1.6.1.5 Property Category->name is empty

### ISSUE THREAD

**Issue by cbamultimedia** [Bukimedia/PrestaSharp#216]
Cuando intentas insertar una categoria en prestashop 1.6.1.5 da error: Property Category->name is empty, en otras versiones de presta inserta bien
< prestashop>
< category>
  < id_parent>2< /id_parent>
  < id_shop_default>1< /id_shop_default>
  < nleft>0< /nleft>
  < nright>0< /nright>
  < active>0< /active>
  < position>0< /position>
  < is_root_category>0< /is_root_category>
  < name>
    < language id="1">VARIOS< /language>
    < language id="2">VARIOS< /language>
    < language id="3">VARIOS< /language>
    < language id="4">VARIOS< /language>
  < /name >
  < link_rewrite >
    < language id="1">1-VARIOS< /language>
    < language id="2">1-VARIOS< /language>
    < language id="3">1-VARIOS< /language>
    < language id="4">1-VARIOS< /language>
  < /link_rewrite >
  < description >
    < language id="1">VARIOS< /language>
    < language id="2">VARIOS< /language>
    < language id="3">VARIOS< /language>
    < language id="4">VARIOS< /language>
  < /description >
  < meta_title > 
    < language id="1">VARIOS< /language>
    < language id="2">VARIOS< /language>
    < language id="3">VARIOS< /language>
    < language id="4">VARIOS< /language>
  </meta_title >
  < meta_description >
    < language id="1">VARIOS< /language>
    < language id="2">VARIOS< /language>
    < language id="3">VARIOS< /language>
    < language id="4">VARIOS< /language>
  < /meta_description >
  < meta_keywords >
    < language id="1">1,VARIOS< /language>
    < language id="2">1,VARIOS< /language>
    < language id="3">1,VARIOS< /language>
    < language id="4">1,VARIOS< /language>
  < /meta_keywords >
  < associations >
    < categories />
    < products />
  < /associations>
< /category>
< /prestashop>

L4HLKQPUGGGRRHZG613EH6QEQ1GEHVB

application/json, application/xml, text/json, text/x-json, text/javascript, text/xml, text/html

< ?xml` version="1.0" encoding="UTF-8"?>
< prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
< errors>
< error>
< code><![CDATA[84]]></code>
< message><![CDATA[Validation error: "Property Category->name is empty"]]></message>
< /error>
< /errors>
< /prestashop>
  HttpStatusCode: BadRequest

**Comment by carlosptt** [comment]
I have the same error a ineed your help its urgent

**Comment by carlosptt** [comment]
I have the same error i need you help

**Comment by carlosptt** [comment]
<prestashop>
<category>
  <id_parent>2</id_parent>
  <id_shop_default>0</id_shop_default>
  <nleft>0</nleft>
  <nright>0</nright>
  <active>1</active>
  <position>0</position>
  <is_root_category>0</is_root_category>
  <name>
    <language id="1">COCINA</language>
  </name>
  <link_rewrite>
    <language id="1">cocina</language>
  </link_rewrite>
  <description>
    <language id="1">COCINA</language>
  </description>
  <meta_title />
  <meta_description />
  <meta_keywords />
  <associations>
    <categories />
    <products />
  </associations>
</category>
</prestashop>

9QSKFWGFG1YGIN198HNNS2ZF4EY31DP4

application/json, application/xml, text/json, text/x-json, text/javascript, text/xml, text/html

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[84]]></code>
<message><![CDATA[Validation error: "Property Category->name is empty"]]></message>
</error>
</errors>
</prestashop>
  HttpStatusCode: BadRequest

**Comment by cbamultimedia** [comment]
I have not solved the problem and that is why I use another communication API
