### ISSUE TITLE
Return products by category

### ISSUE THREAD

**Issue by MrViSiOn** [Bukimedia/PrestaSharp#218]
Hi!

Is there any function to retrieve all products by specific category id?

Thank you!

**Comment by avperillo** [comment]
Hi,

You should to use the method ProductFactory.GetByFilter.

In this example you obtain the product list of id category default is equal to 2.

Dictionary<string, string> filter = new Dictionary<string, string>();
filter.Add("id_category_default", "2");
ProductFactory productFactory = new ProductFactory(baseUrl, wsAccount, string.Empty);
List<product> productListIdCategory2 = productFactory .GetByFilter(filter, null, null);
