### ISSUE TITLE
Getting product image

### ISSUE THREAD

**Issue by StudioTOB** [Bukimedia/PrestaSharp#224]
Hi,
Can anyone help with getting a product image ?
I have the following code which seems to work but I have no idea how to build the url for the actual image from that.

public byte[] getImages(long id, long img)
        {
            ImageFactory imgfactory = new ImageFactory(BaseUrl, Account, Password);
            byte[] images = imgfactory.GetProductImage(id, img);
            return images;
        }

I hope someone can get me into the right direction.

Thanks

**Comment by mulflar** [comment]
This code is not giving you the url image, instead is downloading the full image in byte[] format.
You can convert it to bitmap or Image and then use ir wherever you want.

**Comment by Crapper** [comment]
Ah, ok.... Thank you for your explanation.
I've found another way to construct the url with the product_id which gives met a large_default image and/or small_default image and so on.
