### ISSUE TITLE
Prestasharp in Xamarin APP

### ISSUE THREAD

**Issue by esanzpe** [Bukimedia/PrestaSharp#232]
Can I use Prestasharp in a a Xamarin APP??

it appears as a package but I can't install it

**Comment by SirDev** [comment]
Prestasharp uses restsharp that might not be compatible with xamarin PCLs. Are you targetting a specific Xamarin version? Xamarin.Android, Xamarin.iOS or Xamarin.Forms?

Your best best would be to rewrite this into a .NET standard library and use the HttpClient to make these requests.
