### ISSUE TITLE
Deleting a product does not work!

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Bukimedia/PrestaSharp#233]
Fails with status code `404` to be exact 

```csharp
var api = "http://www.myendpoint.com/api";
var token = "topsecretsequenceofcharacters";
var products = new ProductFactory(api, token, ,"");
var product = products.Get(8); // an existing product
products.Delete(product); // THIS FAILS with 404
```

Any suggestions? 
thanks in advance

**Comment by ldellacherie** [comment]
Hello,

Did you resolve your problem ?

can you check your factory initialization ? 
ProductFactory(Api_BaseUrl, Api_Account, Api_Password);

**Comment by Zaid-Ajaj** [comment]
@ldellacherie Sorry havn't tried it, don't need anymore either so I am closing
