### ISSUE TITLE
Get Products by reference

### ISSUE THREAD

**Issue by DoubleDim** [Bukimedia/PrestaSharp#236]
Is it possible to get products by their reference? instead of ids for example. Thank you.

**Comment by ldellacherie** [comment]
Hello,

yes, by filter

Dictionary<string, string> dsearch = new Dictionary<string, string>();
dsearch.Add("reference", "abcde");
List<product> list_products_web = this.engine.ProductFactory.GetByFilter(dsearch, null, null);

**Comment by DoubleDim** [comment]
Hello and thanks for your reply, actually i had used this one when i was testing it but i wasn't working
![ref](https://cloud.githubusercontent.com/assets/23503889/21384255/7321fa30-c772-11e6-8107-390de63d17d8.jpg)

**Comment by DoubleDim** [comment]
Problem Solved, Thanks.
