### ISSUE TITLE
Products hidden in Back office

### ISSUE THREAD

**Issue by AlessioEnvi** [Bukimedia/PrestaSharp#243]
Hi, 

I added 3 products with PrestaSharp but i do not see them in the product list in the back office.
The products are perfectly visible in the store.
Then I added a new product from the back office and I went to check the differences in the table _ps-product_.
As you can see below the 'state' field of the last inserted product it is 1, while those inserted using PrestaSharp are 0.
![ps_product](https://cloud.githubusercontent.com/assets/8004395/22600788/60ff7336-ea3c-11e6-81c6-0d7b61eaa69a.jpg)

If I change manualy the 'state' field from 0 to 1, it works.

How can I change the 'state' field in PrestaSharp to see the products in the back office?

Regards

**Comment by AlessioEnvi** [comment]
PrestaShop version 1.7

**Comment by mulflar** [comment]
I think the prestasharp api currently don't suports PrestaShop 1.7

**Comment by EduLeonPavon** [comment]
Hello,
Please, update PrestaSharp. Now supports PrestaShop 1.7
Regards.

**Comment by AlessioEnvi** [comment]
I updated the dll but I still have the same problem.

Regards.
