### ISSUE TITLE
Error adding a new product. version 1.7

### ISSUE THREAD

**Issue by markinhok2** [Bukimedia/PrestaSharp#244]
Product does not appear in Prestashop.
The columns "advanced_stock_management", "pack_stock_type" and "state" are worthless.
![image](https://cloud.githubusercontent.com/assets/13909408/22643921/a6aa119a-ec47-11e6-805b-666b5caafebe.png)

**Comment by mulflar** [comment]
I think the prestasharp api currently don't suports PrestaShop 1.7

**Comment by zbroinx** [comment]
I have the same problem.
Any workarround?

**Comment by EduLeonPavon** [comment]
Hi @markinhok2 
Please, update PrestaSharp.
Regards.

**Comment by markinhok2** [comment]
Hi @EduLeonPavon!
Thank you for your update..
Regards. =)
