### ISSUE TITLE
Add new product

### ISSUE THREAD

**Issue by zbroinx** [Bukimedia/PrestaSharp#246]
Hi,
I'm trying to create new products.
In prestashop back-office, the new product doesn't appear, but it exists in the DB.
I try to compare the columns with other products, and I notice that the only diference is the column 'state'. If I update manually this column, the new products shows up in prestashop back-office.

How can I resolve this with code?
Thanks in advance.

Here is my code:
```C#
DsArtigos dsArt = Artigos.GetList();
ProductFactory productLink = new ProductFactory(psUrl, psUser, psPass);

foreach (DataRow dr in dsArt.Tables[0].Rows)
{                
	product newPrdPS = new product();
	newPrdPS.active = Convert.ToInt32(dr["activo"]);
	newPrdPS.reference = dr["codigo"].ToString();
	newPrdPS.available_for_order = Convert.ToInt32(dr["activo"]);
	newPrdPS.condition = "new";
	newPrdPS.date_add = DateNow();
	newPrdPS.date_upd = DateNow();
	newPrdPS.price = Convert.ToDecimal(dr["preco"].ToString());
	newPrdPS.show_price = 1;
	newPrdPS.visibility = "both";
	newPrdPS.minimal_quantity = 1;
	newPrdPS.id_category_default = 33;
	newPrdPS.available_for_order = 1;
	newPrdPS.id_category_default = 12;
	newPrdPS.id_tax_rules_group = 1;
	newPrdPS.redirect_type = "404";
	newPrdPS.name.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language((long)1, dr["nome"].ToString()));
	newPrdPS.meta_title.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language((long)1, dr["nome"].ToString()));
	newPrdPS.meta_keywords.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language((long)1, dr["nome"].ToString()));
	newPrdPS.description.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language((long)1, "<p>" + dr["notas"].ToString() + "</p>"));
	newPrdPS.meta_description.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language((long)1,dr["notas"].ToString()));
	newPrdPS.description_short.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language((long)1, "<p>" + dr["notas"].ToString() + "</p>"));
	newPrdPS.associations.categories.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.category((long)12));
	
	productLink.Add(newPrdPS);
}
```

**Comment by zbroinx** [comment]
Same problem #244 and #243.

**Comment by jgonzal1873** [comment]
I'm trying to insert a product using the latest prestasharp version to a prestashop version 1.6.1.17.
Some how when I add the product, it returns the id_product of a product that is already created in the database. I doesn't apply auto_increment, and as a result the product is not created.

I put the code

           var product = new Bukimedia.PrestaSharp.Entities.product();
            product.id = 10007;
            product.active = 1;
            product.reference = "10007";
            product.name.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language(4, "Test 2"));
            product.condition = "new"; //new, used, refurbished
            product.price = 15000;
            product.show_price = 1;
            product.available_for_order = 1;

            ProductFactory pf = new ProductFactory(BaseUrl, Account, Password);
            product = pf.Add(product);

            string t = product.id.ToString();

The id of the product is not created and it returns a 1 which is the id of the product that is already in the database.

Any help would be appreciated.

Johnny
