### ISSUE TITLE
Set own category ID - not autoincrement

### ISSUE THREAD

**Issue by szyn33k** [Bukimedia/PrestaSharp#247]
How can I set own category ID?
I have code like below, and categories add correctly but with autoicrement ID.

When I set off aut_increment in mysql table ps_category in id_category filed i cant add category via API and I get error "service Temporarily Unavailable ". Could somebody help me?

 Regards.

> private static void addCategoryToShop(Category category)
> {
>   Bukimedia.PrestaSharp.Entities.category c = new Bukimedia.PrestaSharp.Entities.category();
>   Bukimedia.PrestaSharp.Entities.AuxEntities.language l = new   Bukimedia.PrestaSharp.Entities.AuxEntities.language();
>   l.id = 1;
>   l.Value = category.Name;
> 
>   c.id = category.ID;
>   c.id_parent = category.ParentID;
> 
>   c.AddName(l);
>   c.active = category.Active;
> 
>   c.AddLinkRewrite(l);
>    
>   CategoryFactory.Add(c);
> }

**Comment by zbroinx** [comment]
I think that is not possible.
