### ISSUE TITLE
ProductSupplier is not on the library

### ISSUE THREAD

**Issue by LuisDavidR** [Bukimedia/PrestaSharp#254]
Hi, first of all thanks for this awesome library!

I have a question, I have the latest Bukimedia.PrestaSharp version installed (v1.157.0) but I don't have the ProductSupplier factory nor the product_supplier entity. What can I do to have access to this?

Thanks.
![productsupplier](https://cloud.githubusercontent.com/assets/25486990/24008035/4c3cd492-0a68-11e7-9c1a-a556882e0118.jpg)

**Comment by markbeazley** [comment]
I think its due to the Nuget package not being updated since 2015, ProductSupplier was added to the library in 2016. If you use library from GitHub it should have the ProductSupllier functionality (I did this by building my own version of the package and publishing it to my local feed.

**Comment by LuisDavidR** [comment]
Ok, I'm going to search how to do this.

Thank you!
