### ISSUE TITLE
Create new order : module ?

### ISSUE THREAD

**Issue by ToineSeiter** [Bukimedia/PrestaSharp#268]
Hello,

I'm trying to create/update orders on a Prestashop via api whithout installing any module on the website.
If I set the module field to empty, Prestashop throw the following error : 
> Validation error: "Property Order->module is empty"
If I put a value in the module like "MySource" it throws the error:
> Validation error: "Property Order->module is not valid"
If I put a value like "Bankwire" in module it throws an exception on the validateOrder().

What is the good way to create an order with good values in **module** and **payment** fields ?

**Comment by amysticool** [comment]
Hello ToineSeiter,

I have the same problem when performing an order, i have an error on module setting name. Did you find a solution to this issue it could help me a lot.

Thanks

**Comment by ToineSeiter** [comment]
Hello Amysticool,

The error was due to something else. After adding a good carrier id, a good cart id, etc. it works on several Prestashop versions. Finally we decided to create a module exposing its own API... Prestashop web service is a nightmare...
