### ISSUE TITLE
Products.GetALL Return null

### ISSUE THREAD

**Issue by pc4service** [Bukimedia/PrestaSharp#275]
Hello,

I have code

string BaseUrl = Convert.ToString(inifile.Read("Prestashop", "Url"));
            string Account = Convert.ToString(inifile.Read("Prestashop", "ApiKey")); ;
            string Password = "";

            ProductFactory PF = new ProductFactory(BaseUrl, Account, Password);
            List<product> products = PF.GetAll();

and return null.
What its going wrong ?

Thanks

**Comment by R0xtar** [comment]
Are you providing URL with the '/api' part ?

**Comment by capricornius** [comment]
I have the same error. a fact, this happens to me when I put the prestashop in mode debug. otherwise, give me internal error full

**Comment by navimel** [comment]
Hi,
If you have a lot of products, and you call .GetAll, the xml response is too big so the connection is expired by timeout.
I experienced the same problem with stock_available

**Comment by R0xtar** [comment]
@navimel I had a try with a 28k products database and it worked well for me.

**Comment by navimel** [comment]
@R0xtar may be your timeout is set high than mine....I've got 26K products....

**Comment by mowcixo** [comment]
It may depend on your server characteristics, anyway, I would recommend you to always paginate the results.
