### ISSUE TITLE
Example to Add new category

### ISSUE THREAD

**Issue by pc4service** [Bukimedia/PrestaSharp#276]
Have you example in C# , who to add new category using PrestaSharp ?

**Comment by LuisFReis** [comment]
`using Bukimedia.PrestaSharp.Factories;
using Bukimedia.PrestaSharp.Entities;

namespace Prestashop
{
    public partial class CategoryPost
    {
        public CategoryPost()
        {
                category category = new category();
                category.AddName(new Bukimedia.PrestaSharp.Entities.AuxEntities.language { id = 1, Value = "Lang 1" });
                category.AddName(new Bukimedia.PrestaSharp.Entities.AuxEntities.language { id = 2, Value = "Lang 2" });
                category.id_parent = 2; // This is the beggining category
                category.AddLinkRewrite(new Bukimedia.PrestaSharp.Entities.AuxEntities.language { id = 1, Value = "test_lang1" });
                category.AddLinkRewrite(new Bukimedia.PrestaSharp.Entities.AuxEntities.language { id = 2, Value = "test_lang2" });
                category.active = 1;
                category.is_root_category = 0;
                category.id_shop_default = 1;

                CategoryFactory Category = new CategoryFactory(PrestashopForm.BaseUrl, PrestashopForm.Account, PrestashopForm.Password);
                Category.Add(category);
         }
   }
}`

However in this case I can insert the the category but it is not enable under the frontstore.
Needs to add it to the top menu in modules configiguration in backoffice.

**Comment by mowcixo** [comment]
Hello @pc4service, the example provided by @LuisFReis should work.
