### ISSUE TITLE
How to show nem Category in Top menu

### ISSUE THREAD

**Issue by LuisFReis** [Bukimedia/PrestaSharp#279]
By default the Prestashop brings two levels of categories:
root (1)
beginning (2)

I can Insert new categories under the "beginning" but they are not enabled in the frontstore.
Under backoffice I need to add them to top menu.

How can I do that thru API (PrestaSharp)?

**Comment by mowcixo** [comment]
Hello @LuisFReis, sorry for the delay.

PrestaSharp is just to make easy the use of PrestaShop webservice, so as PrestaShop webservice doesn't allow to edit module configurations, neither PrestaSharp isn't capable to do that.

This can only be edited through main menu module configuration.

**Comment by JM63** [comment]
Hello

I have the same problem placing categories in the main menu. 
I saw that prestashop and prestasharp have a webservice named "configurations", it will be possible through this webservice to configure the main menu from the categories.

How can i create the main menu from the categories with prestasharp?
