### ISSUE TITLE
Products position in category

### ISSUE THREAD

**Issue by josep2902** [Bukimedia/PrestaSharp#280]
Hi,

I've set an order for the products in a category. When I update a product the position of this product is changed.

For example, having this:

Product 1 -> Position 0
Product 2 -> Position 1
Product 3 -> Position 2
Product 4 -> Position 3

and doing this:

lProduct = lProductsList.Last
lFactoryProduct.Update(lProduct)

Without any change, only updating the same product, this is the result:

Product 1 -> Position 0
Product 2 -> Position 1
Product 4 -> Position 1
Product 3 -> Position 2

Is there something to do for update the product without change its position?

**Comment by LuisDavidR** [comment]
Hi, 

try to set is position to null:

`product.position_in_category = null;`

**Comment by mowcixo** [comment]
Thanks for the answer @LuisDavidR, it should work.
