### ISSUE TITLE
Versión Prestasharp para Prestashop 1.6.1.15

### ISSUE THREAD

**Issue by centenario** [Bukimedia/PrestaSharp#284]
Id like to know if current version (2017-09-21) is right for Prestashop 1.6.1.15

Thanks in advance

**Comment by mowcixo** [comment]
Hello @centenario, we just released the official NuGet release that should work for you. Yo can find it searching by PrestaSharp in nuget repositories, or the release https://github.com/Bukimedia/PrestaSharp/releases/tag/1.0.0

The version you are talking about is an unofficial NuGet package and we don't support it.
