### ISSUE TITLE
ProductFactory.Update TimeOut, .Add Works Fine.

### ISSUE THREAD

**Issue by OscarBanos** [Bukimedia/PrestaSharp#287]
Hi
When I run the command Product Factory.Update (also happens with ProductFactory.Update (ProductFactory.Get (2)) respond with TimeOut but Product.Add works fine and The Web Service has all permissions, some idea?

**Comment by mowcixo** [comment]
Hello @OscarBanos, sorry for the delay.

Have you fixed this problem? If not: what are the changes you're making to the product before calling update?

**Comment by OscarLate** [comment]
Hi,

I'm @OscarBanos, this problem was by MailChimp module. This module was doing calls to some place without response that made timeouts.It seems strange but it only affected WebService and BackOffice in the product section.

 Solution: Uninstall module.

**Comment by mowcixo** [comment]
Thanks @OscarLate for the quick response, clossing issue as it wasn't a PrestaSharp issue.
