### ISSUE TITLE
Not an issue, but a request/suggestion

### ISSUE THREAD

**Issue by Garfius** [Bukimedia/PrestaSharp#289]
I have seen your nice project, and compiled (some tiny modifications needed)

The idea is to use prestaSharp on powerShell scripts, and IT WORKS !!

Load the compiled binaries:

_Add-Type -Path .\RestSharp.dll
Add-Type -Path .\Bukimedia.PrestaSharp.dll_

Set the url and key to variables

_$key = "AKEYIDONTREMEMBERBLABLABLABLABLA"         
$url = "http://www.myAwesomeWeb.com/api"_

Test some commands

_$b = New-Object Bukimedia.PrestaSharp.Factories.StockAvailableFactory($url,$key,"")
$b.GetAll()
$b.Get(12)_

Create a typed object to upload, i copied the one from Get(12) with MODIFIED QUANTITY

_$c = New-Object Bukimedia.PrestaSharp.Entities.stock_available
$c.id = 12
$c.id_product = 15501
$c.id_shop = 1
$c.quantity = 123
$c.id_product_attribute =0
$c.id_shop_group =0_

Post to prestashop

_$b.Update($c)
$b.GetAll()_

And everything works perfect!!

SOOOOOO

Can anyone create a powershell tutorial 'cause scripting matters !!

Thanks, great job!

**Comment by mowcixo** [comment]
Hi @Garfius, it would be great if you could make a pull request over README.md documenting this.
