### ISSUE TITLE
Erro in GetIdsByFilter GenericFactory

### ISSUE THREAD

**Issue by GiorgioConte** [Bukimedia/PrestaSharp#292]
Hi,
when i call the function OrderFactory.GetIdsByFilter, i have this error:

Impossibile eseguire il cast di oggetti di tipo 'WhereSelectListIterator`2[Bukimedia.PrestaSharp.Entities.order,System.Nullable`1[System.Int64]]' sul tipo 'System.Collections.Generic.List`1[System.Int64]'.
in 
GetIdsByFilter on GenericFactory line 120 (return (List<long>)(aux.Select(t => t.id).ToList()))
Can u help me to solve?

**Comment by nico159** [comment]
Had the same error, fixed with proposed pull request https://github.com/Bukimedia/PrestaSharp/pull/293

**Comment by GiorgioConte** [comment]
I've resolved with:
   return (from t in aux select t.id).Cast<long>().ToList();

**Comment by juanchog** [comment]
Fixed with commit https://github.com/Bukimedia/PrestaSharp/commit/023549c2b5a6f4726d0e41c0b24fb652209e51c1
