### ISSUE TITLE
Getting product description

### ISSUE THREAD

**Issue by williamhodges** [Bukimedia/PrestaSharp#296]
How can I get the product description? I've tried everything that I can think of.

**Comment by LuisDavidR** [comment]
Hi,

product.description is a list of languages:

`public List<Entities.AuxEntities.language> description { get; set; }`

because you can have one description for each language.

So to access all the descriptions of that product in all languages, you have to do something like this:

```
foreach (language lang in langfactory.GetAll())
{
     //to add a description to every language
     product.description.Add(new Bukimedia.PrestaSharp.Entities.AuxEntities.language((long)lang.id, "Description You Want"));

     //to read the description
     productDescriptionList.Add(product.description[lang.id]);
}
```

**Comment by williamhodges** [comment]
Thank you!
