### ISSUE TITLE
Problem with product_option

### ISSUE THREAD

**Issue by segarcia** [Bukimedia/PrestaSharp#30]
Hello Eduardo

I was trying to insert new product option with prestasharp library with that values:

Dim Item As New PrestaSharp.Entities.product_option()
Item.id = 0
Item.group_type = "select"
Item.is_color_group = 0
Item.position = 0
Item.name.Add(New Entities.AuxEntities.language("1", "Talla"))
Item.public_name.Add(New Entities.AuxEntities.language("1", "Talla"))
Item = factoria.Add(Item)

And always recieve the same exception error but the record is inserted.
Could you help me with this problem.
I was using 1.5.6.1 Prestasharp versión 

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[97]]></code>
<message><![CDATA[[SQL Error] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3. From AttributeGroupCore->setWsProductOptionValues() Query was : 
            DELETE FROM `ps_attribute`
            WHERE `id_attribute_group` = 7
            AND `id_attribute` NOT IN ()]]></message>
</error>
</errors>
</prestashop>

Thanks
Sergio

**Comment by brickxsoftware** [comment]
Still does not work... Same error, also when it is not the first option.
Any fix on this ?
