### ISSUE TITLE
Link_rewrite is not valid at product update

### ISSUE THREAD

**Issue by polaije** [Bukimedia/PrestaSharp#304]
Hello,
My first test with product creation was successfull but with an update I get the error 
Link_rewrite is not valid

Here is my code:
 ProductFactory ProductFact = new ProductFactory(BaseUrl, Account, Password);
 product ProductToUpdate=new product();
 ProductToUpdate = ProductFact.Get(4551);

ProductToUpdate.active = 0;
            
ProductFact.Update(ProductToUpdate);

And the error :
`<link_rewrite>
	<language>
		<id>2</id>
		<Value>korres-kb-promo-11-amande-cerise-gel-douche-2x250ml</Value>
	</language>
	<language>
		<id>6</id>
		<Value>korres-kb-promo-11-amandel-kers-douchegel-2x250ml</Value>
	</language>
</link_rewrite>
...
<errors>
	<error>
		<code><![CDATA[84]]></code>
		<message><![CDATA[Validation error: \"Property Product->link_rewrite is not valid\"]]></message>
	</error>
</errors>
</prestashop>
HttpStatusCode: BadRequest"}
`

Can you help me with this error.

Thanks,
Jean-Marie

**Comment by polaije** [comment]
For info:
I have the latest prestasharp update and last update Prestashop 1.6.
Here is the request:
`{text/xml=<prestashop>
<product>
  <id>4459</id>
  <id_manufacturer>0</id_manufacturer>
  <id_supplier>0</id_supplier>
  <id_category_default>158</id_category_default>
  <cache_default_attribute>0</cache_default_attribute>
  <id_tax_rules_group>3</id_tax_rules_group>
  <position_in_category>9</position_in_category>
  <type>simple</type>
  <id_shop_default>1</id_shop_default>
  <reference>3413119</reference>
  <supplier_reference></supplier_reference>
  <location></location>
  <width>0.000000</width>
  <height>0.000000</height>
  <depth>0.000000</depth>
  <weight>0.000000</weight>
  <quantity_discount>0</quantity_discount>
  <ean13></ean13>
  <upc></upc>
  <cache_is_pack>0</cache_is_pack>
  <cache_has_attachments>0</cache_has_attachments>
  <is_virtual>0</is_virtual>
  <state>0</state>
  <on_sale>0</on_sale>
  <online_only>0</online_only>
  <ecotax>0.000000</ecotax>
  <minimal_quantity>1</minimal_quantity>
  <price>18.632075</price>
  <wholesale_price>0.000000</wholesale_price>
  <unity></unity>
  <unit_price_ratio>0.000000</unit_price_ratio>
  <additional_shipping_cost>0.00</additional_shipping_cost>
  <customizable>0</customizable>
  <text_fields>0</text_fields>
  <uploadable_files>0</uploadable_files>
  <active>0</active>
  <redirect_type></redirect_type>
  <id_product_redirected>0</id_product_redirected>
  <available_for_order>1</available_for_order>
  <available_date>0000-00-00</available_date>
  <show_condition>0</show_condition>
  <condition>new</condition>
  <show_price>1</show_price>
  <indexed>1</indexed>
  <visibility>both</visibility>
  <advanced_stock_management>0</advanced_stock_management>
  <date_add>2016-04-04 10:42:03</date_add>
  <date_upd>2016-06-02 11:51:03</date_upd>
  <pack_stock_type>3</pack_stock_type>
  <meta_description>
    <language>
      <id>2</id>
      <Value></Value>
    </language>
    <language>
      <id>6</id>
      <Value></Value>
    </language>
  </meta_description>
  <meta_keywords>
    <language>
      <id>2</id>
      <Value></Value>
    </language>
    <language>
      <id>6</id>
      <Value></Value>
    </language>
  </meta_keywords>
  <meta_title>
    <language>
      <id>2</id>
      <Value></Value>
    </language>
    <language>
      <id>6</id>
      <Value></Value>
    </language>
  </meta_title>
  <link_rewrite>
    <language>
      <id>2</id>
      <Value>29-s-pau-d-arco-xxi-caps-30x690mg</Value>
    </language>
    <language>
      <id>6</id>
      <Value>29-s-pau-d-arco-xxi-caps-30x690mg</Value>
    </language>
  </link_rewrite>
  <name>
    **<language>
      <id>2</id>
      <Value>29-S Pau D'Arco Xxi   Caps 30X690Mg</Value>
    </language>
    <language>
      <id>6</id>
      <Value>29-S PAU D'ARCO XXI   CAPS 30X690MG-NL</Value>
    </language>**
  </name>
  <description>
    <language>
      <id>2</id>
      <Value></Value>
    </language>
    <language>
      <id>6</id>
      <Value></Value>
    </language>
  </description>
  <description_short>
    <language>
      <id>2</id>
      <Value></Value>
    </language>
    <language>
      <id>6</id>
      <Value></Value>
    </language>
  </description_short>
  <available_now>
    <language>
      <id>2</id>
      <Value></Value>
    </language>
    <language>
      <id>6</id>
      <Value></Value>
    </language>
  </available_now>
  <available_later>
    <language>
      <id>2</id>
      <Value></Value>
    </language>
    <language>
      <id>6</id>
      <Value></Value>
    </language>
  </available_later>
  <associations>
    <categories>
      <category>
        <id>158</id>
      </category>
    </categories>
    <images />
    <combinations />
    <product_option_values />
    <product_features />
    <tags />
    <stock_availables>
      <stock_available>
        <id>4495</id>
        <id_product_attribute>0</id_product_attribute>
      </stock_available>
    </stock_availables>
    <product_bundle />
    <accessories />
  </associations>
</product>
</prestashop>}`

**Comment by polaije** [comment]
Sorry closed by mistake

**Comment by WilfredChong** [comment]
anyone, I also facing this issue

**Comment by mowcixo** [comment]
Hello @polaije and @WilfredChong, what version of PrestaSharp are you using?

**Comment by WilfredChong** [comment]
I am using prestashop 1.6

**Comment by mowcixo** [comment]
> I am using prestashop 1.6

Hello @WilfredChong, and what version of this library? How you download PrestaSharp? Using nuget?

**Comment by WilfredChong** [comment]
1.6.1.17

**Comment by mowcixo** [comment]
Hello @WilfredChong, I'm asking for this library version, not your PrestaShop version.

How you use this library in your .NET project? you download master directly? using NuGet?

**Comment by WilfredChong** [comment]
I dobwload it directly

**Comment by mowcixo** [comment]
Hello @WilfredChong, It should be fixed now with version 1.0.5. Could you test and let me know?
