### ISSUE TITLE
Products getall() error

### ISSUE THREAD

**Issue by polaije** [Bukimedia/PrestaSharp#305]
Hi,
My first test with Prestasharp was difficult.
First I got an error 0x1F in products getall, I had to filter the response.content to eliminate this error.
Second, the field id_product_redirected that is null, produced a type error, I had to modify the field in product.cs with long? to correct it.

Now the selection of products seems to work but I have a products count less than expected (1650 instead of 3142).
 Here is my code:
`ProductFactory ProductFact = new ProductFactory(BaseUrl, Account, Password);
            List<product> products = ProductFact.GetAll();
`
With the getbyfilter, it is the same, 1 in categorydefault instead of 9.

Do you have answers to my issues ?

Jean-Marie

**Comment by polaije** [comment]
Hi,
Running the application one day later and everything the products count is now ok. Why the difference with yesterday ?

Another issue is the products count by id_category_default. When a product is in several categories, but well in category default, the filter does not select the product.

Jean-Marie

**Comment by mowcixo** [comment]
Hello @polaije, sorry for the delay. It should be fixed now with v1.0.3 we just released.

It probably failed with products that had associations. Let me know if it is fixed in your environment.

**Comment by mowcixo** [comment]
It should be fixed now with version 1.0.5.
