### ISSUE TITLE
Is there a way to add Related Products?

### ISSUE THREAD

**Issue by VictorALopes** [Bukimedia/PrestaSharp#306]
I have a question, not an issue.
Is there any way to add Related Products Id's to one product?

I've searched the 'product' object attributes but didn't found one that sounds suitable for this.

**Comment by mowcixo** [comment]
Hello @VictorALopes, sorry for the delay.

You can add related products to one product by filling its:

```
product.associations.accesories
```

Which is a list of ```AuxEntities.product```, that's basically a class with an ```id``` property.

I recommend you to use our slack group in the future when you want to ask a question or need help: https://join.slack.com/t/prestasharp/shared_invite/enQtNTM2OTI1OTg0NzUyLTY4NDdkZDFmY2EwMGE4MTMzZjk5YzZiMTk3MzUwNzUxNTdhMWEwZjFjNDJiZTIyMjI0MDM0NTcwMzIzNGI0Njc
