### ISSUE TITLE
Check category exist

### ISSUE THREAD

**Issue by MarcoTroise** [Bukimedia/PrestaSharp#307]
Hi all, how can i check if category exist?

**Comment by polaije** [comment]
Hi,
I am now writing an application using web service with external provider and this is my solution:
CategoryFactory categoriesFact = new CategoryFactory(baseurl, account, "");
            Dictionary<string, string> filter = new Dictionary<string, string>();
            filter.Add("id", YouSearchId);
            filter.Add("active", "1");
List<category> categories = categoriesFact.GetByFilter(filter, null, null);
if(categories.Count>0) {console.write "Exist...";}

Good luck,
Jean-Marie

**Comment by mowcixo** [comment]
Thanks for the answer @polaije. Closing the issue.
