### ISSUE TITLE
Update in NuGet

### ISSUE THREAD

**Issue by MindaugasVarkalys** [Bukimedia/PrestaSharp#308]
I use NuGet in my project. However your library hasn't been updated since 2015 there and I cannot use it. Please update your package in NuGet.

By the way, I noticed that your project doesn't work with the latest version of RestSharp. Can you fix that? If it's not possible, please at least change NuGet dependencies accordingly.

**Comment by mowcixo** [comment]
We just released official NuGet package in release https://github.com/Bukimedia/PrestaSharp/releases/tag/1.0.0
