### ISSUE TITLE
Problem with product_option_value

### ISSUE THREAD

**Issue by segarcia** [Bukimedia/PrestaSharp#31]
Hello Eduardo

I was trying to insert new product option value with prestasharp library with that values:

Dim item As New Entities.product_option_value
item.id = 0
item.name = addLanguajes("1", "XL")
item.id_attribute_group = 1
item.position = 0
item.color = ""
item = factoria.Add(item)

The response.StatusCode on Execute method in RestSharpFactory has "created" value but response.Data is null. Execute functión return response.Data and then in then Add method in ProductOptionValueFactory in this line:
"return this.Get((long)aux.id); " throws an exception because aux has null value.

The record in the MySQL database is inserted.
This exception only occurs when is the first value in the product options. If the product option has one o more values then the Add method works fine and response.Data has a correct value.

I was using 1.5.6.1 Prestasharp versión and MySQL version server is 5.6.11

Thanks a lot
Sergio

**Comment by radodr** [comment]
Hello, this help me:
http://stackoverflow.com/questions/19663100/restsharp-has-problems-deserializing-xml-including-byte-order-mark.
Rado.

**Comment by panilo** [comment]
Hi guys I found the problem: 

PS doesn't return position attribute during product_option_values creation, so if you change position type from int to int? in Bukimedia.PrestaSharp.Entities.product_option_value the function works well. 

I use PS 1.6.1.8

Regards,
Pani

**Comment by panilo** [comment]
PS I attach the output generated by POST call 

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product_option_value>
	<id><![CDATA[13]]></id>
	<id_attribute_group xlink:href="http://sandbox.supermonza.com/api/product_options/23"><![CDATA[23]]></id_attribute_group>
	<color></color>
	<position></position>
	<name><language id="1" xlink:href="http://sandbox.supermonza.com/api/languages/1"><![CDATA[Test Option Value ]]></language></name>
</product_option_value>
</prestashop>


As you can see position ha no value
