### ISSUE TITLE
Update product works not on all products !

### ISSUE THREAD

**Issue by polaije** [Bukimedia/PrestaSharp#314]
Hi,
I have written a complete application for retrieving products from a Platform with web services.
Everything works good, like adding product, updating pictures, etc...
The only thing that does not work is product update, for some products and I don't understand why specific product produce the error "link_rewrite is not valid" and the field is correct. 
I have the debug option enabled in Prestashop but no error is showned.

I am in Prestashop 1.6.1.17 and I have updated the code of Prestasharp.

How can I solve this ?

Thanks,
Jean-Marie

**Comment by polaije** [comment]
Hi,

I found the solution, it was the restsharp.cs witch was not up to date.

**Comment by mowcixo** [comment]
Closing as it is resolved.
