### ISSUE TITLE
Entities in PS1.6 to PS1.7

### ISSUE THREAD

**Issue by polaije** [Bukimedia/PrestaSharp#316]
Hi,
Is it possible to use Prestasharp to copy entities from Prestashop 1.6 to Prestashop 1.7 ?

Yhis can be very usefull to upgrade.

Regards,
Jean-Marie

**Comment by polaije** [comment]
When I try to list categories in Ps 1.7 I got this error 
Cannot cast object System.Net.FileWebRequest' in type 'System.Net.HttpWebRequest'. HttpStatusCode: 0

My version of Prestasharp is the one available in nuget.

Thanks to help,
Jean-Marie

**Comment by mowcixo** [comment]
We just released official NuGet package in release https://github.com/Bukimedia/PrestaSharp/releases/tag/1.0.0.

Try with that and let us know if the problem stills @polaije. Thanks.
