### ISSUE TITLE
Compatible con Prestashop 1.7

### ISSUE THREAD

**Issue by IcuScc** [Bukimedia/PrestaSharp#323]
Hi, Prestasharp is 100% compatible with Prestashop 1.7?

Hola, Prestasharp es compatible con Prestashop 1.7?

Gracias :smiley:

**Comment by fu-hsi** [comment]
No.
Changing product price will hide product (active = 0).

**Comment by mowcixo** [comment]
Hello @IcuScc, as far as we tested it is, it may have not implemented fields though. Let us know if you find an error tying to implement it with Prestashop 1.7. Thanks.

**Comment by IcuScc** [comment]
Hi mowcixo. Thanks for your reply.
At the moment the only problem i have had is with the discounts of the orders, but i solve it, goint to read order discounts to mysql database.
