### ISSUE TITLE
Error Create a new Product

### ISSUE THREAD

**Issue by capricornius** [Bukimedia/PrestaSharp#324]
Hello.
Ia have error in Add product. iam using a net core version (Prestasharp.netcore 1.06).
I can't find a property 'low_stock_alert' and is required in Prestashop DB  to insert a product

In Debug mode show this exception:

<prestashop>
<product>
  <id_manufacturer>2</id_manufacturer>
  <id_supplier>0</id_supplier>
  <id_category_default>7</id_category_default>
  <cache_default_attribute>28</cache_default_attribute>
  <id_default_image>18</id_default_image>
  <id_default_combination>28</id_default_combination>
  <id_tax_rules_group>1</id_tax_rules_group>
  <position_in_category>0</position_in_category>
  <type>simple</type>
  <id_shop_default>1</id_shop_default>
  <reference>demo_8</reference>
  <supplier_reference></supplier_reference>
  <location></location>
  <width>0.000000</width>
  <height>0.000000</height>
  <depth>0.000000</depth>
  <weight>0.000000</weight>
  <quantity_discount>0</quantity_discount>
  <ean13></ean13>
  <upc></upc>
  <cache_is_pack>0</cache_is_pack>
  <cache_has_attachments>0</cache_has_attachments>
  <is_virtual>0</is_virtual>
  <state>1</state>
  <on_sale>0</on_sale>
  <online_only>0</online_only>
  <ecotax>0.000000</ecotax>
  <minimal_quantity>1</minimal_quantity>
  <price>12.900000</price>
  <wholesale_price>0.000000</wholesale_price>
  <unity></unity>
  <unit_price_ratio>0.000000</unit_price_ratio>
  <additional_shipping_cost>0.00</additional_shipping_cost>
  <customizable>0</customizable>
  <text_fields>0</text_fields>
  <uploadable_files>0</uploadable_files>
  <active>1</active>
  <redirect_type>404</redirect_type>
  <id_product_redirected>0</id_product_redirected>
  <available_for_order>1</available_for_order>
  <available_date>0000-00-00</available_date>
  <show_condition>0</show_condition>
  <condition>new</condition>
  <show_price>1</show_price>
  <indexed>1</indexed>
  <visibility>both</visibility>
  <advanced_stock_management>0</advanced_stock_management>
  <date_add>2018-04-23 09:52:21</date_add>
  <date_upd>2018-04-23 09:52:21</date_upd>
  <pack_stock_type>3</pack_stock_type>
  <meta_description>
    <language id="1"></language>
  </meta_description>
  <meta_keywords>
    <language id="1"></language>
  </meta_keywords>
  <meta_title>
    <language id="1"></language>
  </meta_title>
  <link_rewrite>
    <language id="1">mountain-fox-notebook</language>
  </link_rewrite>
  <name>
    <language id="1">Mountain fox notebook</language>
  </name>
  <description>
    <language id="1">&lt;p&gt;&lt;span style="font-size:10pt;font-family:Arial;font-style:normal;"&gt;The Mountain fox notebook is the best option to write down your most ingenious ideas. At work, at home or when traveling, its endearing design and manufacturing quality will make you feel like writing! 90 gsm paper / double spiral binding.&lt;/span&gt;&lt;/p&gt;</language>
  </description>
  <description_short>
    <language id="1">&lt;p&gt;&lt;span style="font-size:10pt;font-family:Arial;font-style:normal;"&gt;120 sheets notebook with hard cover made of recycled cardboard. 16x22cm&lt;/span&gt;&lt;/p&gt;</language>
  </description_short>
  <available_now>
    <language id="1"></language>
  </available_now>
  <available_later>
    <language id="1"></language>
  </available_later>
  <associations>
    <categories>
      <category>
        <id>2</id>
      </category>
      <category>
        <id>6</id>
      </category>
      <category>
        <id>7</id>
      </category>
    </categories>
    <images>
      <image>
        <id>18</id>
      </image>
    </images>
    <combinations>
      <combinations>
        <id>28</id>
      </combinations>
      <combinations>
        <id>29</id>
      </combinations>
      <combinations>
        <id>30</id>
      </combinations>
      <combinations>
        <id>31</id>
      </combinations>
    </combinations>
    <product_option_values>
      <product_option_value>
        <id>22</id>
      </product_option_value>
      <product_option_value>
        <id>23</id>
      </product_option_value>
      <product_option_value>
        <id>24</id>
      </product_option_value>
      <product_option_value>
        <id>25</id>
      </product_option_value>
    </product_option_values>
    <product_features />
    <tags />
    <stock_availables>
      <stock_available>
        <id>16</id>
        <id_product_attribute>0</id_product_attribute>
      </stock_available>
      <stock_available>
        <id>47</id>
        <id_product_attribute>28</id_product_attribute>
      </stock_available>
      <stock_available>
        <id>48</id>
        <id_product_attribute>29</id_product_attribute>
      </stock_available>
      <stock_available>
        <id>49</id>
        <id_product_attribute>30</id_product_attribute>
      </stock_available>
      <stock_available>
        <id>50</id>
        <id_product_attribute>31</id_product_attribute>
      </stock_available>
    </stock_availables>
    <product_bundle />
    <accessories />
  </associations>
</product>
</prestashop>

R87UUJPT57VDDEFYRWH44HUY5RDGAQQ

application/json, application/xml, text/json, text/x-json, text/javascript, text/xml, text/xml

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[97]]></code>
<message><![CDATA[[SQL Error] Column 'low_stock_alert' cannot be null. From DbCore->insert() Query was : INSERT INTO `ps_product` (`id_shop_default`, `id_manufacturer`, `id_supplier`, `reference`, `supplier_reference`, `location`, `width`, `height`, `depth`, `weight`, `quantity_discount`, `ean13`, `isbn`, `upc`, `cache_is_pack`, `cache_has_attachments`, `is_virtual`, `state`, `additional_delivery_times`, `id_category_default`, `id_tax_rules_group`, `on_sale`, `online_only`, `ecotax`, `minimal_quantity`, `low_stock_threshold`, `low_stock_alert`, `price`, `wholesale_price`, `unity`, `unit_price_ratio`, `additional_shipping_cost`, `customizable`, `text_fields`, `uploadable_files`, `active`, `redirect_type`, `id_type_redirected`, `available_for_order`, `available_date`, `show_condition`, `condition`, `show_price`, `indexed`, `visibility`, `cache_default_attribute`, `advanced_stock_management`, `date_add`, `date_upd`, `pack_stock_type`) VALUES ('1', '2', '0', 'demo_8', '', '', '0', '0', '0', '0', '0', '', '', '', '0', '0', '0', '1', '0', '7', '1', '0', '0', '0', '1', NULL, NULL, '12.9', '0', '', '0', '0', '0', '0', '0', '1', '404', '0', '1', '0000-00-00', '0', 'new', '1', '1', 'both', '28', '0', '2018-05-20 10:32:20', '2018-05-20 10:32:20', '3')]]></message>
</error>
<error>
<code><![CDATA[97]]></code>
<message><![CDATA[[SQL Error] Column 'low_stock_alert' cannot be null. From ObjectModelCore->add() Query was : INSERT INTO `ps_product` (`id_shop_default`, `id_manufacturer`, `id_supplier`, `reference`, `supplier_reference`, `location`, `width`, `height`, `depth`, `weight`, `quantity_discount`, `ean13`, `isbn`, `upc`, `cache_is_pack`, `cache_has_attachments`, `is_virtual`, `state`, `additional_delivery_times`, `id_category_default`, `id_tax_rules_group`, `on_sale`, `online_only`, `ecotax`, `minimal_quantity`, `low_stock_threshold`, `low_stock_alert`, `price`, `wholesale_price`, `unity`, `unit_price_ratio`, `additional_shipping_cost`, `customizable`, `text_fields`, `uploadable_files`, `active`, `redirect_type`, `id_type_redirected`, `available_for_order`, `available_date`, `show_condition`, `condition`, `show_price`, `indexed`, `visibility`, `cache_default_attribute`, `advanced_stock_management`, `date_add`, `date_upd`, `pack_stock_type`) VALUES ('1', '2', '0', 'demo_8', '', '', '0', '0', '0', '0', '0', '', '', '', '0', '0', '0', '1', '0', '7', '1', '0', '0', '0', '1', NULL, NULL, '12.9', '0', '', '0', '0', '0', '0', '0', '1', '404', '0', '1', '0000-00-00', '0', 'new', '1', '1', 'both', '28', '0', '2018-05-20 10:32:20', '2018-05-20 10:32:20', '3')]]></message>
</error>
<error>
<code><![CDATA[46]]></code>
<message><![CDATA[Unable to save resource]]></message>
</error>
</errors>
</prestashop>
  HttpStatusCode: InternalServerError

all helps is welcome !!

**Comment by mowcixo** [comment]
Hello, we just released the official NuGet release that fixes the related problem. Yo can find it searching by PrestaSharp in nuget repositories, or the release https://github.com/Bukimedia/PrestaSharp/releases/tag/1.0.0

Sorry for the delay and thanks for waiting.
