### ISSUE TITLE
Problem executing PUT 

### ISSUE THREAD

**Issue by ricardomls** [Bukimedia/PrestaSharp#332]
[Prestashop 1.6.1.20 & IIS Server & PHP7]
Hello.
First of all I would like to congrats this project for its excellence.

I'm developing a VB.NET library to handle ERP new products and price/description update.

Creation and image deploy works fine, but when I'm trying to update an object, webservice answers with:

`<?xml version="1.0" encoding="utf-8"?>
<prestashop>
<product>
  <id>2879</id>
  <id_manufacturer>0</id_manufacturer>
  <id_supplier>0</id_supplier>
  <id_category_default>1</id_category_default>
  <New>0</New>
  <cache_default_attribute>0</cache_default_attribute>
  <id_default_image>5407</id_default_image>
  <id_default_combination>1</id_default_combination>
  <id_tax_rules_group>1</id_tax_rules_group>
  <position_in_category>0</position_in_category>
  <type>simple</type>
  <id_shop_default>1</id_shop_default>
  <reference>9997</reference>
  <supplier_reference />
  <location />
  <width>0.000000</width>
  <height>0.000000</height>
  <depth>0.000000</depth>
  <weight>0.000000</weight>
  <quantity_discount>0</quantity_discount>
  <ean13 />
  <upc />
  <cache_is_pack>0</cache_is_pack>
  <cache_has_attachments>0</cache_has_attachments>
  <is_virtual>0</is_virtual>
  <state>0</state>
  <on_sale>0</on_sale>
  <online_only>0</online_only>
  <ecotax>0.000000</ecotax>
  <minimal_quantity>1</minimal_quantity>
  <price>10</price>
  <wholesale_price>0.000000</wholesale_price>
  <unity />
  <unit_price_ratio>0.000000</unit_price_ratio>
  <additional_shipping_cost>0.00</additional_shipping_cost>
  <customizable>0</customizable>
  <text_fields>0</text_fields>
  <uploadable_files>0</uploadable_files>
  <active>1</active>
  <redirect_type />
  <id_product_redirected>0</id_product_redirected>
  <available_for_order>1</available_for_order>
  <available_date>0000-00-00</available_date>
  <show_condition>0</show_condition>
  <condition>new</condition>
  <show_price>1</show_price>
  <indexed>1</indexed>
  <visibility>both</visibility>
  <advanced_stock_management>0</advanced_stock_management>
  <date_add>2018-07-16 12:21:11</date_add>
  <date_upd>2018-07-16 11:58:39</date_upd>
  <pack_stock_type>0</pack_stock_type>
  <meta_description>
    <language id="1" />
  </meta_description>
  <meta_keywords>
    <language id="1" />
  </meta_keywords>
  <meta_title>
    <language id="1" />
  </meta_title>
  <link_rewrite>
    <language id="1">novo-produto-primavera</language>
    <language id="1">novo-produto-primavera</language>
  </link_rewrite>
  <name>
    <language id="1">Novo Produto Primavera</language>
    <language id="1">Novo Produto Primavera</language>
  </name>
  <description>
    <language id="1" />
  </description>
  <description_short>
    <language id="1" />
  </description_short>
  <available_now>
    <language id="1" />
  </available_now>
  <available_later>
    <language id="1" />
  </available_later>
  <associations>
    <categories>
      <category>
        <id>1</id>
      </category>
      <category>
        <id>1</id>
      </category>
    </categories>
    <images>
      <image>
        <id>5407</id>
      </image>
    </images>
    <combinations />
    <product_option_values />
    <product_features />
    <tags />
    <stock_availables>
      <stock_available>
        <id>2879</id>
        <id_product_attribute>0</id_product_attribute>
      </stock_available>
    </stock_availables>
    <product_bundle />
    <accessories />
  </associations>
</product>
</prestashop>`

`﻿<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[127]]></code>
<message><![CDATA[XML error : String could not be parsed as XML
XML length : 0
Original XML : ]]></message>
</error>
</errors>
</prestashop>
  HttpStatusCode: InternalServerError
`

Before the update call I execute this code:

`Public Function UpdateProduto(produto As Produto)

     
        Dim dsearch = New Dictionary(Of String, String)
        Dim product As New Bukimedia.PrestaSharp.Entities.product

        dsearch.Add("reference", produto.reference)
        Dim list_products_web = pf.GetByFilter(dsearch, "", "")

        If list_products_web.Count > 0 Then

            product = New Bukimedia.PrestaSharp.Entities.product

            product = pf.Get(list_products_web(0).id)

            Try
                pf.Update(product)
            Catch ex As Exception
                Return -1
            End Try

        Else

            product = New Bukimedia.PrestaSharp.Entities.product

            preencherProdutoNovo(produto, product)

            Try
                product = pf.Add(product)

                 imgf.AddProductImage(product.id, Path_ + "semimagem.jpg")

            Catch ex As Exception
                Return -1
            End Try

        End If

        Return product.id.ToString()

    End Function`

I'm doing a full set of the object, not editing any property.

Thanks for the help.
CHEERS

**Comment by biovolt** [comment]
Try checking out the code using this commit 066ffbc49be441d894355031bdb21783ffb91254 
and see if this solves our problem

I think it is related to https://github.com/Bukimedia/PrestaSharp/issues/318

**Comment by mowcixo** [comment]
It should be fixed in v1.0.3 release. Please, try it and let me know.
