### ISSUE TITLE
adding new specific prices for prestashop v 1.6 ERROR

### ISSUE THREAD

**Issue by Rabi3k** [Bukimedia/PrestaSharp#333]
im using this code below to add new specific price to an item but the return value is the first specific price in my database and the specific price is not added 
any help? 
or suggestion 

the API key in Webservise is checked for add

SpecificPriceFactory specificPriceFactory = new SpecificPriceFactory(shopURL, GlobalClass.Account, GlobalClass.Password);
           
            specific_price s = new specific_price();
            s.id_product = productID;
            s.id_shop_group = 0;
            s.id_shop = 0;
            s.id_cart = 0;
            s.id_currency = 0;
            s.id_customer = 0;
            s.id_country = 0;
            s.id_group = 4;
            s.id_product_attribute = Product_attribute[0];
            s.id_specific_price_rule = 0;
            s.price = -1;
            s.from_quantity = 1;
            s.reduction = 0;
            s.reduction_tax = 1;
            s.reduction_type = "percentage";
            s.from = "0000-00-00 00:00:00";
            s.to = "0000-00-00 00:00:00";
            var i = specificPriceFactory.Add(s);

**Comment by OscarLate** [comment]
same problem. same problem. did you solve it?

**Comment by mowcixo** [comment]
Hello @Rabi3k, sorry for the delay, did you solve it?

**Comment by mowcixo** [comment]
How about you @OscarLate?
