### ISSUE TITLE
Getting a single product returns null. Everything else works fine.

### ISSUE THREAD

**Issue by johndoe1395** [Bukimedia/PrestaSharp#346]
Hello
Getting product like this makes productFactory null.
Getting eg. a manufacturer in the same way is fine.
I checked the request it makes from the access logs and tested it with Postman and the request is fine, it return's the products XML.

`
ProductFactory productFactory = new ProductFactory("/path/to/api", "mykey", "");
var productFilter = new Dictionary<string, string>()
{
	{ "id", "1" }
};
var prd = productFactory.GetByFilter(productFilter, null, null);
`

**Comment by johndoe1395** [comment]
I solved it. I was using the Nuget package and after cloning this repo and including it in my project, it is working fine. Isn't the nuget package updated? It says v.1.0.0

**Comment by mowcixo** [comment]
I think that's probably fixed in commit d24796d5e31a02f75df1e9e5288977b4ed2fb654 which is not on v1.0.0 we are waiting for some more changes to launch v1.0.1 soon. We will let you know.

Thanks for publishing the issue!

**Comment by johndoe1395** [comment]
Thanks for the quick reply.

**Comment by mowcixo** [comment]
Hello @johndoe1395, we just relased v1.0.2 if you want to return to the nuget package. Thanks!

**Comment by johndoe1395** [comment]
Thanks for letting me know! :)
