### ISSUE TITLE
Error Update Product

### ISSUE THREAD

**Issue by capricornius** [Bukimedia/PrestaSharp#349]
_Source_ Value : Bukimedia.PrestaSharp.Entities.product
_Find_ Value: \<product>
_Replace_ Value: \<prestashop>
\<product>

internal static string ReplaceFirstOccurrence(string Source, string Find, string Replace)
        {
            int Place = Source.IndexOf(Find);
            string result = Source.Remove(Place, Find.Length).Insert(Place, Replace);
            return result;
        }

of course the value of _Place_ == -1 so error is generated because that value (Source) does not contain "\<product>"
((System.ArgumentOutOfRangeException)ex).Message:

StartIndex cannot be less than zero.
Parameter name: startIndex

**Comment by mowcixo** [comment]
Hello @capricornius, what version of the library you have?
