### ISSUE TITLE
Location missing

### ISSUE THREAD

**Issue by insane78** [Bukimedia/PrestaSharp#351]
In lastest release (like in previous i think) is missing the field location in stock_available entity.

Prestashop 1.7.5.1

**Comment by insane78** [comment]
Also field "level_depth" is missing in category entity

**Comment by mowcixo** [comment]
Hello @insane78, thanks for the issue. You're right, we will add them in next release and let you know.

**Comment by insane78** [comment]
Many thanks to you guys for your awesome work

**Comment by mowcixo** [comment]
That's included in new release 1.0.4, already in NuGet. Thanks!
