### ISSUE TITLE
Categories GetAll() duplicates (1.0.3)

### ISSUE THREAD

**Issue by insane78** [Bukimedia/PrestaSharp#352]
Upgrading prestasharp 1.0 to 1.0.3 i noticed that all categories are duplicated.
Looking in debug the collection returned, i see that the duplicates are not identical.
For example i have 2 object with same category id, but one have idparent, name(collection), and other fileds with their values, the other object have this fields null, except for the IDcategory.

I have one shop declared (no multishop) with one language installed (italian).
Prestashop 1.7.5.1

**Comment by insane78** [comment]
![image](https://user-images.githubusercontent.com/49029448/55786842-53061a00-5ab5-11e9-9836-5834a4f96289.png)

**Comment by mowcixo** [comment]
Could you try with new release 1.0.4? There is a bug fix related with that.

**Comment by insane78** [comment]
I noticed about 1.0.4 just after your reply. I tried this new release and seems works like a charm.
Thank you very much.

**Comment by mowcixo** [comment]
Thank you @insane78 :)
