### ISSUE TITLE
date_upd / date_add return null

### ISSUE THREAD

**Issue by itsieber** [Bukimedia/PrestaSharp#353]
When i select with .get the date_upd and date_add are every time null. When i get over webbrowser  i get the XML:

<![CDATA[ 0 ]]>
</id_shop_group>
<date_add>
<![CDATA[ 2005-08-31 00:00:00 ]]>
</date_add>
<date_upd>
<![CDATA[ 2019-04-25 00:59:58 ]]>
</date_upd>

**Comment by mowcixo** [comment]
Hello @itsieber, It should be fixed now with version 1.0.5. Could you test and let me know?

**Comment by itsieber** [comment]
Great thats work now!

**Comment by mowcixo** [comment]
Perfect! Thank you!
