### ISSUE TITLE
Discount cart rules total_discount_tax_excl the value is with tax included

### ISSUE THREAD

**Issue by sanctusmob** [Bukimedia/PrestaSharp#355]
**Prestashop version:**
1.7.5.1
 
I create a cart rule 1 plus 1 in some brand apply a discount 100% to the cheapest product.
When the order is place the field in DB total_discount_tax_excl have the discount with tax.
ex. 
total_discounts --> 39.990000
total_discount_tax_incl --> 39.990000
total_discount_tax_excl --> 39.990000

it should be like this (the product have 24% tax)
total_discounts --> 39.990000
total_discount_tax_incl --> 39.990000
total_discount_tax_excl --> 32.250000

**Comment by mowcixo** [comment]
Hello @sanctusmob, it sounds like a PrestaShop issue, not PrestaSharp one. Could you request it with your browser directly to the PrestaShop api and paste the results?

**Comment by sanctusmob** [comment]
Yea. I post it in wrong repo :). Sorry. 

https://github.com/PrestaShop/PrestaShop/issues/13689
