### ISSUE TITLE
Create customer

### ISSUE THREAD

**Issue by miguelextremanet** [Bukimedia/PrestaSharp#359]
Hello
I need to create new customers from my ERP solution 
I am using this code to create. the customer is created in prestashop successfully created, but I am not able to login using the credential I used. email and password.

            Dim CFactory As Bukimedia.PrestaSharp.Factories.CustomerFactory = New Bukimedia.PrestaSharp.Factories.CustomerFactory(pagina_web_tienda & "/api", API_KEY_PRESTASHOP, "")
            Dim Cliente As Bukimedia.PrestaSharp.Entities.customer = New Bukimedia.PrestaSharp.Entities.customer
            Cliente.passwd = "123345678"
            Cliente.firstname = "jose"
            Cliente.lastname = "pepe"
            Cliente.email = "correo@lectronico.com"
            Cliente.id_shop = 1
            Cliente.id_gender = 1
            Cliente.id_default_group = 1
            Cliente.id_lang = 1
            CFactory.Add(Cliente)

thanks

**Comment by mowcixo** [comment]
Hello @miguelextremanet, that's why you didn't specify the ```active``` property, just add:

```
Cliente.active = 1
```

That's it.

**Comment by miguelextremanet** [comment]
thanks
