### ISSUE TITLE
Error when update products

### ISSUE THREAD

**Issue by wolfmc3** [Bukimedia/PrestaSharp#36]
I'm doing some tests to implement prestasharp in my application to update products.

Prestashop version 1.5.6.1 with demo database
## When I try to update a product I get more lines with this error message:

<?xml version="1.0" encoding="UTF-8"?>

<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">

<errors>

<error>

<message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>

</error>

[omissis...]

<error>

<message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>

</error>

</errors>

</prestashop>

An object reference not set to an instance of an object.

---

If enabled in the configuration error messages, the error message does not appear and the update is successful

CODE:

```
        string BaseUrl = this.url;
        string Account = this.key;
        string Password = "";
        ProductFactory ProductFactory = new ProductFactory(BaseUrl, Account, Password);

        List<PrestaSharp.Entities.product> Articoli = ProductFactory.GetAll();
        PrestaSharp.Entities.product articolo = new PrestaSharp.Entities.product();

        foreach (PrestaSharp.Entities.product tmp in Articoli)
        {
            if (tmp.id == 10) {
                articolo = tmp;
                break;
            }
        }
        articolo.name[0].Value += "Prova\n";
        ProductFactory.Update(articolo);
```

Thanks

**Comment by carlosptt** [comment]
@EduLeonPavon Ineed your help i have a problem whit creatting categories 
<prestashop>
<category>
  <id_parent>2</id_parent>
  <id_shop_default>0</id_shop_default>
  <nleft>0</nleft>
  <nright>0</nright>
  <active>1</active>
  <position>0</position>
  <is_root_category>0</is_root_category>
  <name>
    <language id="1">COCINA</language>
  </name>
  <link_rewrite>
    <language id="1">cocina</language>
  </link_rewrite>
  <description>
    <language id="1">COCINA</language>
  </description>
  <meta_title />
  <meta_description />
  <meta_keywords />
  <associations>
    <categories />
    <products />
  </associations>
</category>
</prestashop>

9QSKFWGFG1YGIN198HNNS2ZF4EY31DP4

application/json, application/xml, text/json, text/x-json, text/javascript, text/xml, text/html

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[84]]></code>
<message><![CDATA[Validation error: "Property Category->name is empty"]]></message>
</error>
</errors>
</prestashop>
  HttpStatusCode: BadRequest

**Comment by carlosptt** [comment]
@EduLeonPavon 
<prestashop>
<category>
  <id_parent>2</id_parent>
  <id_shop_default>0</id_shop_default>
  <nleft>0</nleft>
  <nright>0</nright>
  <active>1</active>
  <position>0</position>
  <is_root_category>0</is_root_category>
  <name>
    <language id="1">COCINA</language>
  </name>
  <link_rewrite>
    <language id="1">cocina</language>
  </link_rewrite>
  <description>
    <language id="1">COCINA</language>
  </description>
  <meta_title />
  <meta_description />
  <meta_keywords />
  <associations>
    <categories />
    <products />
  </associations>
</category>
</prestashop>

9QSKFWGFG1YGIN198HNNS2ZF4EY31DP4

application/json, application/xml, text/json, text/x-json, text/javascript, text/xml, text/html

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[84]]></code>
<message><![CDATA[Validation error: "Property Category->name is empty"]]></message>
</error>
</errors>
</prestashop>
  HttpStatusCode: BadRequest
