### ISSUE TITLE
how to know, which of the images of the product is the cover. 

### ISSUE THREAD

**Issue by MpmSys** [Bukimedia/PrestaSharp#360]
how to know, which of the images of the product is the cover. 
I can access the images but I don't see any parameter that tells me which one is the highlight on the cover

**Comment by PHonorato** [comment]
I made this way.

Dim ImageFactory As ImageFactory = New ImageFactory(PrestashopURL, PrestashopKey, "")
Dim ProductFactory As ProductFactory = New ProductFactory(PrestashopURL, PrestashopKey, "")
Dim Imagem_cover As Long

Imagem_cover = ImageFactory.AddProductImage(CLng(id_ArtCatMar), fileName)

Dim Product As Bukimedia.PrestaSharp.Entities.product = ProductFactory.[Get](id_ArtCatMar)
Product.id_default_image = Imagem_cover
ProductFactory.Update(Product)
