### ISSUE TITLE
Actualizar un producto, recibo la siguiente Excepción no controlada por el usuario Referencia a objeto no establecida como instancia de un objeto. SOLUCIONADO

### ISSUE THREAD

**Issue by John-R-P** [Bukimedia/PrestaSharp#363]
Al intentar actualizar un articulo, recibo System.NullReferenceException: 'Referencia a objeto no establecida como instancia de un objeto.' root fue null.
Quisiera solicitar ayuda al respecto.
He descargado el repositorio en mi proyecto para poder depurar la incidencia y lo que consigo es un error en en roor.Element, tal como se ve en la imagen, no se descifrar el porque se se genera la Excepción.
![imagen1](https://user-images.githubusercontent.com/52909213/61201331-70fe9e80-a6e4-11e9-8708-0471961a1188.png)
![imagen2](https://user-images.githubusercontent.com/52909213/61201337-75c35280-a6e4-11e9-9ee2-931a08235e1c.png)

**Comment by makuki** [comment]
Revisa si con la clave del servcio web usada, tienes permiso para actualizar productos.
Desde el backoffice, busca servicio web y comprueba los check marcados en cada tabla a gestionar.

**Comment by makuki** [comment]
Pues no se que puede ser, pero si ROOT es null, es raro que todo funcione.
Puedes meter un control de errores (try cath) para interceptar el error e ignorarle.
También podrías añadir una comprobación de null sobre el objeto root en esa misma parte del código, aunque lo lógico seria no tocar nada ahí.
Supongo que antes de actualizarlo, lo lees, cambias lo que quieras y luego haces el update.
Yo me inclinaria a pensar que el UPDATE lo estás haciendo sobre un elmento que no has leido. Ya se que dirás que 'claro que he hecho eso', pero a veces, nos liamos y es una tonteria.
Voy a probar a hacer un update de artículo y te cuento (de momento solo leo y actualizo pedidos y poco mas)

**Comment by makuki** [comment]
Este código a mi me funciona sin problemas:
Busco el artículo con ID 14494 y le cambio el precio sin error ni nada.

```
        Dim P As New Bukimedia.PrestaSharp.Factories.ProductFactory(frmConfig.GetWSUrl, frmConfig.GetWSLoginUser, frmConfig.GetWSKey)
        Dim A As List(Of Bukimedia.PrestaSharp.Entities.product)
        Dim F As New Dictionary(Of String, String)
        F.Add("id", 14494)
        A = P.GetByFilter(F, "", "")
        A(0).price = 3.51
        P.Update(A(0))
```

Yo me inclinaria a que tienes algún problema en el código, pero no consigo reproducirlo
Por ejemplo, esto falla, pero en otro punto:

```

        Dim b As Bukimedia.PrestaSharp.Entities.product


        P.Update(b)
```

**Comment by John-R-P** [comment]
Después de seguir tus consejos, crea una nueva solución, y utilice el código de ejemplo que me diste y funciono correctamente, con esta prueba, inserte el código de ejemplo en mi proyecto, y se ejecuto la excepción, comparando los dos proyectos, el que funciona tiene integrado PrestaSharp como paquete NuGet, y el proyecto que no funciona, tiene integrado PrestaSharp como proyecto que descargue de GitHub.
Solución elimine el proyecto Prestasharp, y inserte Prestasharp como paquete NuGet, y se soluciono la Excepción. Al insertar PrestasSharp en una solución  como un proyecto, nos puede dar problemas?
**Quiero agradecer el apoyo recibido para solucionar esta incidencia**

**Comment by makuki** [comment]
No entiendo bien, por desconocimiento, la diferencia entre tenerlo como paque NuGet o como proyecto independiente de una solución.

Yo lo tengo como un proyecto, dentro de una solución, y funciona.

Supongo que la diferencia básica es que a ti, te saltarán actualizaciones del paquete NuGet, mientra que yo, debo buscar actualizaciones, cuando yo decida (es decir, nunca!!!! Si todo funciona).

Así que supongo que el proyecto que usabas, tendrá algún BUG o algo por el estilo.

 

Si tienes el PROYECTO independiente, si quieres me lo mandas, e intento buscar la diferencia respecto al mio, o te mando yo el mio… o directamente lo das por solucionado y a otro tema.

 

Encantando de poder ayudarte, es lo mínimo que puedo hacer, cuando a mi tanto me han ayudado.

 

De: John-R-P <notifications@github.com> 
Enviado el: viernes, 19 de julio de 2019 12:45
Para: Bukimedia/PrestaSharp <PrestaSharp@noreply.github.com>
CC: Roberto <nts@netsistemas.com>; Comment <comment@noreply.github.com>
Asunto: Re: [Bukimedia/PrestaSharp] Actualizar un producto, recibo la siguiente Excepción no controlada por el usuario Referencia a objeto no establecida como instancia de un objeto.' (#363)

 

Después de seguir tus consejos, crea una nueva solución, y utilice el código de ejemplo que me diste y funciono correctamente, con esta prueba, inserte el código de ejemplo en mi proyecto, y se ejecuto la excepción, comparando los dos proyectos, el que funciona tiene integrado PrestaSharp como paquete NuGet, y el proyecto que no funciona, tiene integrado PrestaSharp como proyecto que descargue de GitHub.
Solución elimine el proyecto Prestasharp, y inserte Prestasharp como paquete NuGet, y se soluciono la Excepción. Al insertar PrestasSharp en una solución como un proyecto, nos puede dar problemas?
Quiero agradecer el apoyo recibido para solucionar esta incidencia

**Comment by mowcixo** [comment]
La gran diferencia entre usar una solución y el paquete NuGet es que con el paquete NuGet te aseguras de estar siempre actualizado, con una solución a veces no tienes la trazabilidad necesaria para saber en qué estado está el código que tienes descargado. Siempre es recomendable usar el paquete NuGet sin ninguna duda.

Cierro el issue por estar solucionado.

Gracias @John-R-P y @makuki
