### ISSUE TITLE
How sort  order_state

### ISSUE THREAD

**Issue by makuki** [Bukimedia/PrestaSharp#364]
¿Como usar el metodo sort de la entidad order_State?
Quiero ordenar los estados, sin usar GetByFilter

 Dim PSStates As New Bukimedia.PrestaSharp.Factories.OrderStateFactory(frmConfig.GetWSUrl, frmConfig.GetWSLoginUser, frmConfig.GetWSKey)
        Dim States As New List(Of Bukimedia.PrestaSharp.Entities.order_state)

        States = PSStates.GetAll
        States.Sort()
'**************
States = PSStates.GetByFilter(Nothing, "id_desc", "")
'esto funciona, pero no quiero usarlo, pues me gustaría conectar el funcionamiento de sort
    '**************

**Comment by makuki** [comment]
¿Como usar el metodo sort de la entidad order_State?
Quiero ordenar los estados, sin usar GetByFilter

 Dim PSStates As New Bukimedia.PrestaSharp.Factories.OrderStateFactory(frmConfig.GetWSUrl, frmConfig.GetWSLoginUser, frmConfig.GetWSKey)
        Dim States As New List(Of Bukimedia.PrestaSharp.Entities.order_state)


        States = PSStates.GetAll
        States.Sort()

'esto funciona, pero no quiero usarlo, pues me gustaría conectar el funcionamiento de sort
        States = PSStates.GetByFilter(Nothing, "id_desc", "")

**Comment by oromand** [comment]
Sorting has to be made thanks to Linq.
One basic example may be: 

```
ProductFactory factory= new ProductFactory(TestUrl, TestApiKey, null);

var orderedProducts = factory.GetAll().OrderByDescending(d => d.id);
```

**Comment by makuki** [comment]
whit past filter empty, and add sorted.
The performande was similar.

Usa el metodo de filtro sin miedo. No pases filtro y solo ordena. La rapidez será  igual si es lo que te preocupa.

**Comment by makuki** [comment]
Gracias. Se que por rendimiento es igual, pero queria conocer esta función orderbydescending.
thanks. the isue are equal filter or GetAll, but now a know this method.
