### ISSUE TITLE
bukimedia prestasharp with framework 4.5

### ISSUE THREAD

**Issue by DSJOAQUIN** [Bukimedia/PrestaSharp#374]
Hi!

I have a proyect which use netframework 4.5. I want conect to prestashop using bukimedia prestasharp but when I try to install get the follow error: "for install bukimedia prestasharp you need framework 4.5.2.

In this site: https://www.nuget.org/packages/PrestaSharp you can see all version but all of them need .NETFramework 4.5.2.

Could i install bukimedia with .netframework 4.5?

Thanks!

**Comment by oromand** [comment]
It would be better to upgrade your project to 4.5.2.
Attempt to lower it to 4.5 would break the RestSharp library compatibility.
