### ISSUE TITLE
Method Get return nothing for all entities

### ISSUE THREAD

**Issue by blasgs** [Bukimedia/PrestaSharp#40]
Hello

I've tried this code for retrieving a manufacturer by ID, but it always returns null no matter what entity I try:

Dim mManufacturerFactory As New PrestaSharp.Factories.ManufacturerFactory(oConfiguracion.URLServicio, oConfiguracion.IDToken, "")
Dim mManufacturer As PrestaSharp.Entities.manufacturer
mManufacturer = mManufacturerFactory.Get(4)

Having a look inside the method Get of the Factory, I've seen that the request is sent, but in this method response.data is null.

protected T Execute<T>(RestRequest Request) where T : new()
        {
            var client = new RestClient();
            client.BaseUrl = this.BaseUrl;
            client.Authenticator = new HttpBasicAuthenticator(this.Account, this.Password);
            Request.AddParameter("Account", this.Account, ParameterType.UrlSegment); // used on every request
            var response = client.Execute<T>(Request);
            if (response.StatusCode == HttpStatusCode.InternalServerError
                || response.StatusCode == HttpStatusCode.BadRequest
                || response.StatusCode == HttpStatusCode.MethodNotAllowed
                || response.StatusCode == 0)
            {
                var Exception = new ApplicationException(response.Content + " " + response.ErrorMessage, response.ErrorException);
                throw Exception;
            }
            return response.Data;
        }

Here you have a screen capture of the response's inspection. There is an error, but I can figure out what the problem is. Here is the translation: data at the root level is invalid line 1 position 1.

I've traced the traffic with Fiddler and the response message apparently doesn't have any mistake.

![captura](https://f.cloud.github.com/assets/6583592/2075318/ec04d76c-8d8a-11e3-8515-2bfbc59e713f.JPG)

Thank you
Blas

**Comment by mmserafim** [comment]
Hi.

I have the same problem with prestashop 1.6.1.5.

Request.Data is always null, for all entities.

Can anyone help?
Thanks
