### ISSUE TITLE
RestSharp error

### ISSUE THREAD

**Issue by MKI-Miro** [Bukimedia/PrestaSharp#401]
*Please consider making a Pull Request if you are capable of doing so.*

*If your problem is how to implement anything with PrestaSharp or make a question,
please, refer to our Slack# group with this request link: 
https://join.slack.com/t/prestasharp/shared_invite/enQtNTM2OTI1OTg0NzUyLTY4NDdkZDFmY2EwMGE4MTMzZjk5YzZiMTk3MzUwNzUxNTdhMWEwZjFjNDJiZTIyMjI0MDM0NTcwMzIzNGI0Njc*

**Library Version:**

1.1.0

**NuGet Package Url:**

https://www.nuget.org/packages/PrestaSharp/1.1.0
 
**Prestashop version:**
 
1.7.x
 
**Describe the Bug:**

A clear description of what is the bug is.

System.IO.FileLoadException: 'Could not load file or assembly 'RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)'

**To Reproduce:**
var categoryFactory = new CategoryFactory(BaseUrl, Account, Password);
var category = categoryFactory.GetAll()

**Expected Behavior:**

Is this project dead? or is it possible that this bug will be fixed?

Thanks!

**Comment by oromand** [comment]
Hello, 

This problem may arise if your original project has another version of RestSharp referenced. I published the version 1.2.2 of PrestaSharp.Extended, a forked version of PrestaSharp, that allows using the latest version of RestSharp. Could you give it a try ?

**Comment by MKI-Miro** [comment]
Yes I can try it. I will inform you
