### ISSUE TITLE
Prestashop v1.7.6.5 - error - reference null

### ISSUE THREAD

**Issue by crevecoeurj** [Bukimedia/PrestaSharp#403]
Hi,

On Website with version 1.7.6.5, the last version of prestasharp send an error with Create "Product, order...etc)
The same body with postman works.

Does anyone meet the problem ?

**Comment by oromand** [comment]
I do, 
I figured out a fresh copy of the sources wouldn't behave the same ??

**Comment by oromand** [comment]
@crevecoeurj : I publish a forked version attempting to fix those stability issues. Could you give it a try ? The nuget is named Bukimedia.Extended.

**Comment by crevecoeurj** [comment]
Great news, i test that soon as possible.
Thanks

**Comment by infosteo** [comment]
Same for me, GetAll Method for products always gets null.

**Comment by EduLeonPavon** [comment]
Hi guys, thanks to @oromand now you can try to fix this issue with the last version of PrestaSharp.

**Comment by infosteo** [comment]
Thank you, but where can I find the latest version?

**Comment by oromand** [comment]
> Same for me, GetAll Method for products always gets null.
> Current Prestasharp version in 1.2.6 (fork).

Is it possible to have some sort of reproductible case ? postman example or so  ?

**Comment by infosteo** [comment]
I debugged the project with source code and I found:

Status Code:OK
Content type: text/html; charset=utf-8
Error message: Prestashop failed to serve XML response instead got text: <!doctype html>
<html lang="it">
etc. (full html web page)

responseuri: https://myprestashopsite.whatever/index.php?url=products&display=full&date=1&ws_key=mykey

Maybe something has changed on my webserver but I can't understand what.
Is it possible in this case to get an exception?

Thank you

**Comment by oromand** [comment]
I was thinking to have some reference of the response to evaluate the return code and the error in case of trouble. Haven't made my mind though.
What does the HTML page says ? Is it some prestashop content ? or some API error ?

**Comment by crevecoeurj** [comment]
Hi oromand,

I test in  1.7.6.7 and  1.7.6.5 and i t works . (Add manufacturer et GetAll ) of products

I suggest, your find a good new name for your fork  and everybody  switch on :-)

**Comment by infosteo** [comment]
> I was thinking to have some reference of the response to evaluate the return code and the error in case of trouble. Haven't made my mind though.
> What does the HTML page says ? Is it some prestashop content ? or some API error ?

The response.content is the complete html page I get if I put the responseuri on a web browser.
My prestashop version in 1.7.6.4

**Comment by infosteo** [comment]
This is the response I get via Soap UI (Postman too).
![pic04](https://user-images.githubusercontent.com/8542687/89636014-398f0100-d8a8-11ea-89ce-30639817a969.PNG)

**Comment by infosteo** [comment]
Via Chrome I get a XML response.

![pic05](https://user-images.githubusercontent.com/8542687/89636716-5a0b8b00-d8a9-11ea-8b5b-a453f2a10262.PNG)

**Comment by infosteo** [comment]
I have noticed that 
https://irrigazioneperfetta.com/api/products/?display=full

turns into 
AbsoluteUri = "https://irrigazioneperfetta.com/index.php?url=products%2F&display=full&output_format=JSON"
after .GetResponse()
why?

**Comment by infosteo** [comment]
Finally I've solved the problem: Prestashop needs "Friendly urls". See Attach.
![117590483_10157640012813284_8926029641709409234_n](https://user-images.githubusercontent.com/8542687/89903936-952ef680-dbe8-11ea-9164-ec4c457b4970.jpg)
