### ISSUE TITLE
id_product_redirected bug

### ISSUE THREAD

**Issue by arturyn97** [Bukimedia/PrestaSharp#406]
Hello,
I think there is a bug with id_product_redirected. It is always 0 and even i can't update it using prestasharp.
![imagen](https://user-images.githubusercontent.com/61704158/88790088-e7f3c180-d197-11ea-8dba-ce612df6a98a.png)
![imagen](https://user-images.githubusercontent.com/61704158/88790164-0954ad80-d198-11ea-813f-bc19f08a9381.png)

**Comment by oromand** [comment]
Related to #383

**Comment by oromand** [comment]
This should be fixed with version 1.2.7 just published
