### ISSUE TITLE
Exception when adding order

### ISSUE THREAD

**Issue by enesbehlul** [Bukimedia/PrestaSharp#408]
I am using prestasharp v1.2.8 and prestashop v1.7.6.8

trying to add order to order factory by using default pre created products

No problem with,

1. creating user,
2. creating address for user,
3. creating cart,
4. creating order only if ID of the product in the cart is 1 (Hummingbird printed t-shirt)

when i try to add new order with a different product, prestasharp returns exception (different product is also a default product)

debug mode exception : Object reference not set to an instance of an object. null reference exception
debug off exception : Prestashop failed to serve XML response instead got text:  HttpStatusCode: InternalServerError Bukimedia.PrestaSharp.PrestaSharpException"

**Comment by oromand** [comment]
I believe you had some sort of similar code while creating your order. In case not, this is a working sample of mine. It's true that current version of prestasharp isn't of much help when dealing with error.

```
var order = await orderFactory.AddAsync(new order()
                {
                    id_cart = cart.id,
                    id_address_delivery = cart.id_address_delivery,
                    id_address_invoice = cart.id_address_invoice,
                    id_currency = euroCurrency.id,
                    id_customer = cart.id_customer,
                    id_lang = languageFr.id,
                    id_carrier = defaultCarrier.id,

                    total_paid = input.TotalTTC,
                    total_products_wt = input.TotalTTC,
                    total_shipping_tax_incl = input.TotalShippingTTC,

                    payment = "TPE",
                    module = "ps_wirepayment",
                    //state
                });
```

**Comment by enesbehlul** [comment]
@oromand  i tried this way but i got same result. thanks anyway
