### ISSUE TITLE
AddList function dont return list of object added

### ISSUE THREAD

**Issue by mnieblab** [Bukimedia/PrestaSharp#409]
Hello

When is used the addList function to add objects (products, categories, manufacturers, etc.) dont return the list of object added. 
Is very important know minimallythe ids of elements add recently.
This is the correctly functionament or the result is wron??

Thank you

**Comment by oromand** [comment]
Hello, 

No it doesn't sound normal.
I made a quick test, and it appear the `HandleListDerivative` method in the Deserializer is the culprit.

The return of prestashop is correct, just the deserialization doesn't do the job.

**Comment by oromand** [comment]
Hey @mnieblab 

I would push the release 1.2.9 on nuget. It fixes the problem you described. Can you give it a try ?

**Comment by mnieblab** [comment]
Now it´s OK
Thank you very much @oromand!!!

**Comment by oromand** [comment]
Great
