### ISSUE TITLE
Como actualizar el campo ALT de una imagen

### ISSUE THREAD

**Issue by MpmSys** [Bukimedia/PrestaSharp#412]
Como puedo actualizar el campo ALT de las imágenes (campo legend de la tabla ps_image_lang). No encuentro como acceder y actualizar el campo

**Comment by Ros4111** [comment]
Hola. Siento no poder ayudarte porque estoy empezando. Por si me puedes guiar un poco. Este modulo podría servirme para añadir o actualizar los productos de Prestashop?
Estoy empezando a diseñar una base de datos local para despues volcarlo todo en Prestashop porque me parece mucho más cómodo que la interface web. Programo en VB 6 y estoy intentando actualizarme.
Mil gracias por tu ayuda

**Comment by oromand** [comment]
@MpmSys, this is not currently supported by prestasharp. In fact I digged inside the code and it appear Prestashop hasn't implemented it in its web services. Prestasharp is just a wrapper around what exists, and this feature doesn't.

@Ros4111 Prestasharp would help you creating and synchronizing product, categories and related object by code. Code is written in c# but the nuget can be used in any .net project.

**Comment by MpmSys** [comment]
@oromand Thanks for your coment.

**Comment by MpmSys** [comment]
@Ros4111 Este módulo de Prestasharp es ideal para este tipo de gestiones. Yo tambien vengo de VB6 y me pase a NET. Con esta herramienta estoy gestionando una sincronizacion tanto de stocks, precios como de nuevos productos desde una base local al Prestashop para mantener los sistemas. Si te parece y para no sobrecargar este chat te dejo mi email. info@mpm.systems 
Saludo
