### ISSUE TITLE
Update a combination, it disappears from the carts

### ISSUE THREAD

**Issue by fabiovannini** [Bukimedia/PrestaSharp#416]
#### Describe the bug

When you read a combination via webservice and update it without any changes (same dto), if this combination is in any Customer cart, it disappear from cart (always). The combination is updated right. Any error is trigged by webservice. Any message displayed to the customer.

#### Expected behavior

The combination must be remain in the cart (respecting business rules and domain logics)

#### Steps to Reproduce

1) Create a product
2) Create some combinations
3) Insert a combination in the cart on public side
4) Read this combination with web service 
5) Update read combination from web service (same read dto unchanged)
6) This combination left the cart (ALWAYS)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2.34
* PrestSharp version: 1.2.9

#### Sample code

`PrestashopCombination = new CombinationFactory(PrestashopApiBaseUrl, PrestashopAccount, PrestashopPassword);

var combinations = PrestashopCombination.GetByFilter(new Dictionary<string, string>()
{
// READ ALL OR ONE COMBINATION FOR TEST
}, null, null);

foreach (var productCombination in productCombinations) {
PrestashopCombination.Update(productCombination);
}`

**Comment by oromand** [comment]
Thanks for reporting this.
It would need deeper investigation, but most likely, if the API doesn't fail, it has to see with PS way of working; 
The Prestasharp library in itself it just a C# wrapper around PS standard endpoints.

**Comment by fabiovannini** [comment]
Thank you oromand, sorry for the inconvenience. 

I opened an official ticket on Prestashop, it seems to be a problem on the Prestashop core:
[https://github.com/PrestaShop/PrestaShop/issues/23061](https://github.com/PrestaShop/PrestaShop/issues/23061)

I close the ticket.
