### ISSUE TITLE
Prestasharp with VB.net

### ISSUE THREAD

**Issue by joomy78** [Bukimedia/PrestaSharp#436]
Hello,
is it possible to use prestasharp with vb.net?
I installed it via nuget without problem

I followed the basic instructions:
https://github.com/Bukimedia/PrestaSharp

I tried initialization like this:
    Dim manufacturerFactory As ManufacturerFactory = New ManufacturerFactory (baseUrl, account, password)

however, visual studio informs me that ManufacturerFactory is not defined

can you help me solve this problem?
thank you

**Comment by OscarLate** [comment]
Sorry for the delay but yes, you can.

```
        Dim manufacturerFactory As ManufacturerFactory = New ManufacturerFactory(BaseUrl, Account, Password)
        Dim manu As New manufacturer
        manu.name = proveedor
        manu.active = 1
        Return manufacturerFactory.Add(manu).id
```
This works,
