### ISSUE TITLE
ERROR TO INSERT THE PRODUCT

### ISSUE THREAD

**Issue by franciscomarquez1972** [Bukimedia/PrestaSharp#440]
We have a problem when add a product in REST services

i send this....

application/xml: <prestashop>
<product>
  <id_manufacturer>4</id_manufacturer>
  <id_supplier>1</id_supplier>
  <id_category_default>2</id_category_default>
  <cache_default_attribute>0</cache_default_attribute>
  <id_default_image>3</id_default_image>
  <id_default_combination>0</id_default_combination>
  <id_tax_rules_group>1</id_tax_rules_group>
  <type>simple</type>
  <id_shop_default>1</id_shop_default>
  <reference>1002</reference>
  <supplier_reference>demo_6_70</supplier_reference>
  <location></location>
  <width>0.000000</width>
  <height>0.000000</height>
  <depth>0.000000</depth>
  <weight>0.300000</weight>
  <quantity_discount>0</quantity_discount>
  <ean13>8470000002</ean13>
  <upc></upc>
  <isbn></isbn>
  <mpn></mpn>
  <cache_is_pack>0</cache_is_pack>
  <cache_has_attachments>0</cache_has_attachments>
  <is_virtual>0</is_virtual>
  <additional_delivery_times>1</additional_delivery_times>
  <delivery_in_stock>
    <language id="1"></language>
  </delivery_in_stock>
  <delivery_out_stock>
    <language id="1"></language>
  </delivery_out_stock>
  <state>1</state>
  <on_sale>0</on_sale>
  <online_only>0</online_only>
  <ecotax>0.000000</ecotax>
  <minimal_quantity>1</minimal_quantity>
  <low_stock_alert>0</low_stock_alert>
  <price>100.0000</price>
  <wholesale_price>0.000000</wholesale_price>
  <unity></unity>
  <unit_price_ratio>0.000000</unit_price_ratio>
  <additional_shipping_cost>0.000000</additional_shipping_cost>
  <customizable>0</customizable>
  <text_fields>0</text_fields>
  <uploadable_files>0</uploadable_files>
  <active>1</active>
  <redirect_type>301-category</redirect_type>
  <id_type_redirected>0</id_type_redirected>
  <available_for_order>1</available_for_order>
  <available_date>0000-00-00</available_date>
  <show_condition>0</show_condition>
  <condition>new</condition>
  <show_price>1</show_price>
  <indexed>1</indexed>
  <visibility>both</visibility>
  <advanced_stock_management>0</advanced_stock_management>
  <date_add>2022-04-25 11:39:18</date_add>
  <date_upd>2022-05-04 11:46:10</date_upd>
  <pack_stock_type>3</pack_stock_type>
  <meta_description>
    <language id="1"></language>
  </meta_description>
  <meta_keywords>
    <language id="1"></language>
  </meta_keywords>
  <meta_title>
    <language id="1"></language>
  </meta_title>
  <link_rewrite>
    <language id="1">the-best-is-yet-to-come-framed-poster</language>
  </link_rewrite>
  <name>
    <language id="1">ARTICULO-PRO-AZUL-20...</language>
  </name>
  <description>
    <language id="1">Y esta es la descripcion larga del articulo ARTICULO-PRO-AZUL-20... ARTICULO-PRO-AZUL-20... ARTICULO-PRO-AZUL-20...ARTICULO-PRO-AZUL-20...ARTICULO-PRO-AZUL-20... Descripcion larga</language>
  </description>
  <description_short>
    <language id="1">Esta es la descripcion corta del articulo ARTICULO-PRO-AZUL-20...</language>
  </description_short>
  <available_now>
    <language id="1"></language>
  </available_now>
  <available_later>
    <language id="1"></language>
  </available_later>
  <associations>
    <categories>
      <category>
        <id>2</id>
      </category>
      <category>
        <id>31</id>
      </category>
    </categories>
    <images>
      <image>
        <id>3</id>
      </image>
    </images>
    <combinations />
    <product_option_values />
    <product_features>
      <product_feature>
        <id>1</id>
        <id_feature_value>6</id_feature_value>
      </product_feature>
    </product_features>
    <tags />
    <stock_availables>
      <stock_available>
        <id>3</id>
        <id_product_attribute>0</id_product_attribute>
      </stock_available>
      <stock_available>
        <id>32</id>
        <id_product_attribute>13</id_product_attribute>
      </stock_available>
      <stock_available>
        <id>33</id>
        <id_product_attribute>14</id_product_attribute>
      </stock_available>
      <stock_available>
        <id>34</id>
        <id_product_attribute>15</id_product_attribute>
      </stock_available>
    </stock_availables>
    <product_bundle />
    <accessories />
  </associations>
</product>
</prestashop>
ws_key: LRU7ZXT7J6XB1TI6EPUKJ7NWG81EKQXJ

**Library Version:**

1.0.0

**NuGet Package Url:**

PrestaSharp 1.2.9
 
**Prestashop version:**
 
1.7.8.5

 
**Describe the Bug:**

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[5]]></code>
<message><![CDATA[[PHP Notice #8] Trying to access array offset on value of type bool (/var/www/html/classes/Product.php, line 7170)]]></message>
</error>
</errors>
</prestashop>
  HttpStatusCode: InternalServerError

**To Reproduce:**
1. 
2. 
3. 

**Expected Behavior:**

when i append de product....tho code is here

        /// <summary>
        /// Add a list of entities.
        /// </summary>
        /// <param name="Entities"></param>
        /// <returns></returns>
        public List<T> AddList(List<T> Entities)
        {
            List<PrestaSharp.Entities.PrestaShopEntity> EntitiesToAdd = new List<PrestaSharp.Entities.PrestaShopEntity>();
            foreach (T Entity in Entities)
            {
                Entity.id = null;
                EntitiesToAdd.Add(Entity);
            }
            RestRequest request = this.RequestForAdd(pluralEntityName, EntitiesToAdd);
            return this.Execute<List<T>>(request);
        }

**Comment by franciscomarquez1972** [comment]
el mensaje de error es este PHP Notice #8] Trying to access array offset on value of type bool (/var/www/html/classes/Product.php, line 7170)

**Comment by franciscomarquez1972** [comment]
I found the problem, it is in the setter of the Product class in the id_default_image field.

NO OK >>  public long? id_default_image { get; set;}
OK >> public long? id_default_image { get; }

Thanks

**Comment by copperstyle01** [comment]
Hello, i proceeded with that solution but in my case it didn't work.

What i did to solve this issue was add the _if not result return false_ to the class Product.php on the path public_html/Classes/product.php.

`public function getCoverWs()
{
    $result = $this->getCover($this->id);
    if (!$result) {
        return false;
    }
    return $result['id_image'];
}`


Hope this helps somebody in the future too


> I found the problem, it is in the setter of the Product class in the id_default_image field.
> 
> NO OK >> public long? id_default_image { get; set;} OK >> public long? id_default_image { get; }
> 
> Thanks
