### ISSUE TITLE
Read cart contents

### ISSUE THREAD

**Issue by DanRimer** [Bukimedia/PrestaSharp#459]
Hi
Is there a way of reading the contents of a cart? I can see the carts but can't work out how to open them. 

I can do it for orders just not carts!

thanks

dan

**Comment by jesiiu** [comment]
Hi,
I just check it, if you use CartFactory and get specific cart you have content of it in assossiations field, it give you id_product and id_product_attribute which is combination of main product :)

**Comment by DanRimer** [comment]
@jesiiu Thank you so much. I didn't think of looking in the associations field!

Problem solved :-)

**Comment by jesiiu** [comment]
No problem :)
