### ISSUE TITLE
Prestasharp and Blazor

### ISSUE THREAD

**Issue by totti240282** [Bukimedia/PrestaSharp#460]
yesterday I was using this library on Blazor wasm and unfortunately I realized that it is incompatible with the httpclient object.

**Comment by jesiiu** [comment]
Hi,
What do you want to achieve using blazor with prestasharp?

**Comment by jesiiu** [comment]
I don't think prestasharp is designed to work directly with blazor, you would have to fetch the information separately through the controller and use model -> view to return it in your application

**Comment by totti240282** [comment]
Si al momento ho utilizzato una Web api.

**Comment by LameuleFR** [comment]
We use Prestasharp daily with Blazor at my daily job and it work great ! :)
I close this post as it's not an issue
