### ISSUE TITLE
Getfilter product not found

### ISSUE THREAD

**Issue by DrZamo** [Bukimedia/PrestaSharp#461]
Hi.
I use prestashop 1.7.8.8
i use  prestasharp vb.net 1.2.6
i use restasharp 106.11.4

Il getbyfilter product not result currect value

Exemple:
I have a reference  "123" in prestashop.

       
        Dim prodottifactory As New Factories.ProductFactory(My.Settings.sitoapips, My.Settings.CHIAVE, "")
        Dim objFiltro = New Dictionary(Of String, String)
        objFiltro.Add("reference", "123")
        Dim products As New List(Of Entities.product)
        products = prodottifactory.GetByFilter(objFiltro, Nothing, 1)

Product not return value.
The referente "123" is true!

if change parameter in debug:
Exemple         products = prodottifactory.GetByFilter(objFiltro, "id_ASC", 1)
Product is true

The problem is the memory cache?
Help Me please

**Comment by jesiiu** [comment]
Hi, it is reference of main product or product variant ?

**Comment by jesiiu** [comment]
Depending on where you have the field completed you need to use the right connection, I mean the right Factory, for variants there is a separate one so maybe that's why it doesn't find the given reference, additionally I would set GetByFilter(objFiltro, Nothing, Nothing)

**Comment by DrZamo** [comment]
another broken example:
function that deletes products without images
GetByFilter always finds 1100 products.
If I change the filter in debug, it updates the list.
Example:         products = prodottifactory.GetByFilter(objFiltro, "id_DESC", Nothing)

Functioon clearnoimage()
        Dim prodottifactory As New Factories.ProductFactory(My.Settings.sitoapips, My.Settings.chiave, "")
        Dim objFiltro = New Dictionary(Of String, String)
        Dim products As New List(Of Entities.product)
        products = prodottifactory.GetByFilter(objFiltro, Nothing, Nothing)
        For a = 0 To products. Count - 1
            If products(a).associations.images.Count = 0 Or products(a).associations.categories.Count = 0 Then
                Try
                    prodottifactory.Delete(products(a))
                Catch ex As Exception
                    RichTextBox1.Text = ex.Message & " " & products(a).reference & vbNewLine & RichTextBox1.Text
                End Try
                RichTextBox1.Text = "delete " & products(a).reference & vbNewLine & RichTextBox1.Text
                My.Application.DoEvents()
            End If
        Next
    End Sub

I am going crazy

**Comment by jesiiu** [comment]
I think there is issue in VB Library, you should use c# and you will have no problems with this library, i tested all options in my program and everything work well, add get and delete.

**Comment by DrZamo** [comment]
ok i'll do the test

**Comment by DrZamo** [comment]
is possible configuration php, cache or cnd?

**Comment by jesiiu** [comment]
> is possible configuration php, cache or cnd?

Im not sure what you mean by configuration php with prestasharp

**Comment by DrZamo** [comment]
I fixed it by disabling dynamic cache.
if .htaccess
<IfModule mod_headers.c>
Header set Cache-Control "private"
</IfModule>
