### ISSUE TITLE
CombinationFactory return always null

### ISSUE THREAD

**Issue by MarcoITDev** [Bukimedia/PrestaSharp#480]
*Please consider making a Pull Request if you are capable of doing so.*

*If your problem is how to implement anything with PrestaSharp or make a question,
please, refer to our Slack# group with this request link: 
https://join.slack.com/t/prestasharp/shared_invite/enQtNTM2OTI1OTg0NzUyLTY4NDdkZDFmY2EwMGE4MTMzZjk5YzZiMTk3MzUwNzUxNTdhMWEwZjFjNDJiZTIyMjI0MDM0NTcwMzIzNGI0Njc*

**Library Version:**

1.2.9

**NuGet Package Url:**

https://www.nuget.org/packages/PrestaSharp/1.x.x
 
**Prestashop version:**
 
1.7.7.8
 
**Describe the Bug:**

When calling CombinationFactory GetByFilter but also GetAll the object returned is always null.

**To Reproduce:**
Dim CombinationsFactory As New CombinationFactory(BaseUrl, Account, Password)
Dim Cerca_combination As List(Of combination)

Dim DeleteDtn As New Dictionary(Of String, String)
DeleteDtn.Clear()
DeleteDtn.Add("reference", sPSCODART)

Try
     Cerca_combination = CombinationsFactory.GetByFilter(DisableDtn, Nothing, Nothing)
Catch ex As Exception
End Try

When calling .Count an error undefined

Msgbox (Cerca_combination.Count)

**Comment by totti240282** [comment]
Strange I always use it without problems in c#

**Comment by MarcoITDev** [comment]
Not a bug

**Comment by MarcoITDev** [comment]
Close
