### ISSUE TITLE
Where associate carrier with product ?

### ISSUE THREAD

**Issue by megonzalez** [Bukimedia/PrestaSharp#55]
Hi, where define a shipping (Carrier) associated with a product with prestasharp / web services ?

In Prestahop: Product -> Shipping -> Selected Carrier (Producto -> Transporte -> Transportistas Selecionados)

Regards

**Comment by edinhojorge** [comment]
Just for those who are looking for same the info, the association exists, but sadly not for webservices. Please check prefix_product_carriers table:

    CREATE TABLE `ps_product_carrier` (
      `id_product` int(10) unsigned NOT NULL,
      `id_carrier_reference` int(10) unsigned NOT NULL,
      `id_shop` int(10) unsigned NOT NULL,
      PRIMARY KEY (`id_product`,`id_carrier_reference`,`id_shop`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Regards

**Comment by auveele** [comment]
I'm using the 1.7 version of Prestashop.
Is this solved in the newest version?

I think this is very important, because I import the product through the webservice.

Thanks in advance.

**Comment by RRENOU** [comment]
1/ Create in your module the file /override/classes/webservice/WebserviceSpecificManagementProductCarrier.php

```php
<?php
/**
 * Created by PhpStorm.
 * User: administrateur
 * Date: 04/09/2017
 * Time: 13:57
 */
class WebserviceSpecificManagementProductCarrier implements WebserviceSpecificManagementInterface
{
    /** @var WebserviceOutputBuilder */
    protected $objOutput;
    protected $output;

    /** @var WebserviceRequest */
    protected $wsObject;

    /**
     * @param WebserviceOutputBuilderCore $obj
     * @return WebserviceSpecificManagementInterface
     */
    public function setObjectOutput(WebserviceOutputBuilderCore $obj)
    {
        $this->objOutput = $obj;
        return $this;
    }

    public function getObjectOutput()
    {
        return $this->objOutput;
    }

    public function setWsObject(WebserviceRequestCore $obj)
    {
        $this->wsObject = $obj;
        return $this;
    }

    public function getWsObject()
    {
        return $this->wsObject;
    }

    /**
     * This must be return a string with specific values as WebserviceRequest expects.
     *
     * @return string
     */
    public function getContent()
    {
        return $this->objOutput->getObjectRender()->overrideContent($this->output);
    }

    public function manage()
    {
        if(!isset($_POST['id_product']) ||!isset($_POST['ids_carrier_reference']))
        {
            throw new WebserviceException('You have to set the \'id_product\' and \'ids_carrier_reference\' parameters to use this web service', array(100, 400));
        }

        $id_product = Tools::getValue('id_product');
        $ids_carrier_reference = Tools::getValue('ids_carrier_reference', []);
        if(!is_array($ids_carrier_reference)){
            $ids_carrier_reference=explode(',', $ids_carrier_reference);
        }
        $id_shop = Tools::getValue('id_shop', 1);

        if(!Product::existsInDatabase($id_product, 'product')){
            throw new WebserviceException('Product with id equals to '.$id_product.' doesn\'t exist.', array(100, 400));
        }

        $this->setCarriers($id_product, $ids_carrier_reference, $id_shop);

        return array('success' => 'true');
    }

    /**
     * Sets carriers assigned to the product
     */
    private function setCarriers($id_product, $carrier_list, $id_shop)
    {
        $data = array();

        foreach ($carrier_list as $carrier) {
            $data[] = array(
                'id_product' => (int)$id_product,
                'id_carrier_reference' => (int)$carrier,
                'id_shop' => (int)$id_shop
            );
        }
        Db::getInstance()->execute(
            'DELETE FROM `'._DB_PREFIX_.'product_carrier`
			WHERE id_product = '.(int)$id_product.'
			AND id_shop = '.(int)$id_shop
        );

        $unique_array = array();
        foreach ($data as $sub_array) {
            if (!in_array($sub_array, $unique_array)) {
                $unique_array[] = $sub_array;
            }
        }

        if (count($unique_array)) {
            Db::getInstance()->insert('product_carrier', $unique_array, false, true, Db::INSERT_IGNORE);
        }
    }

}
```

2/ Register your module to hook `addWebserviceResources`
In `install()` method :
```php
       ...
       if (!parent::install()
            //|| !$this->registerHook('displayAdminProductsExtra')
            //|| !$this->registerHook('actionProductSave')
            || !$this->registerHook('addWebserviceResources')
            || !$this->registerHook('displayAdminProductsMainStepLeftColumnMiddle')
        )
        ...
```
Create following method :
```php
    public function hookAddWebserviceResources($params){
        return array(
            'product_carrier' => array('description' => 'Attach carriers to a product', 'specific_management' => true, 'forbidden_method' => array('GET', 'PUT', 'DELETE'))
        );
    }
```

NB : Do not forget to give rights on newly created webservice in admin section.

That's it.

Best regards.

**Comment by fredoche1810** [comment]
Hello,
Thanks for your code. It seems you find the solution to add this feature to the webservice.
Can you please give me more explanation where to add which code ?
I created the php WebserviceSpecificManagementProductCarrier.php but I don't understand where to put the next steps.
Thanks in advance
Best regards,

**Comment by RRENOU** [comment]
Hello @fredoche1810,

The first file has to be placed in /override/classes/webservice/WebserviceSpecificManagementProductCarrier.php like you did if I understand right.

The second step has to be wrote in you main module file (/modules/<name_of_your_module>/<name_of_your_module>.php).
https://devdocs.prestashop.com/1.7/modules/concepts/hooks/

Best regards.

**Comment by fredoche1810** [comment]
Hello @RRENOU,
So yes I created the file to override the webservice class.
But I don't have any module... I use prestasharp to read and update throw the webservice.
So my goal is to add the function to prestasharp to update a limited carrier for a product. 
First step is to add the information in the api no ? That's the override you made or not ?
Best regards,

**Comment by RRENOU** [comment]
Hello @fredoche1810 ,
If you don't have any module, you can override the default WebserviceRequest.php by creating a file in /override/classes/webservice/Webservicerequest.php containing following code : 
```php
class WebserviceRequest extends WebserviceRequestCore
{
    public static function getResources()
    {
        $resources=parent::getResources();
        $resources['product_carrier'] = array('description' => 'Attach carriers to a product', 'specific_management' => true, 'forbidden_method' => array('GET', 'PUT', 'DELETE'));
        ksort($resources);
        return $resources;
    }
}
```

Now with the files /override/classes/webservice/WebserviceSpecificManagementProductCarrier.php and  /override/classes/webservice/Webservicerequest.php, you'll be able to call the endpoint <prestashop_url>/api/product_carrier when you access webservice listing page on Prestashop.

```xml
<product_carrier xlink:href="<prestashop_url>/api/product_carrier" get="false" put="false" post="true" delete="false" head="true">
<description xlink:href="<prestashop_url>/api/product_carrier" get="false" put="false" post="true" delete="false" head="true"> Attach carriers to a product</description>
</product_carrier>
```

Hope it will help you to do what you want ;) 
Regards

**Comment by fredoche1810** [comment]
Hello @RRENOU,
That's working until there. I have the same result as you.
When I open the link, I have the following error : Method GET is not allowed for the resource product_carrier
It seems correct because GET, PUT and DELETE are on false (forbidden_method)
So why do you set them as forbidden in your code ?
How can I read the information (without GET)  and how can I insert or remove something without (PUT or DELETE) ?
Thanks in advance

**Comment by RRENOU** [comment]
Hello @fredoche1810 ,
I developed this to fit our need and we just attach a carrier on a product and don't have to update, retrieve or delete this association. However you can allow any method you want to use if it fits to your needs ;)
If you set all to true, you'll be able to call API with all methods like any other endpoint.

**Comment by mowcixo** [comment]
Hi there, we would recommend you to discuss these types of questions in our new Slack group: https://prestasharp.slack.com/

If you want to join, use this link: https://join.slack.com/t/prestasharp/shared_invite/enQtNTEwMjQ3NDA0MTM0LTJlOGFiYmZiMzZkZjQxNjJjNDg0NzRlNWZlNTc2NWY0NTI1ZmM2YTdmMjk4NjYxM2YyNjc2MTZjOTNlNzZjYTY

**Comment by elprogramador** [comment]
there is a solution to associate a product with a carrier
https://josellovell.com/en/prestashop/associate-carrier-to-prestashop/
