### ISSUE TITLE
Problem inserting product

### ISSUE THREAD

**Issue by jpineirocontrolp** [Bukimedia/PrestaSharp#56]
Hi,
I update to prestashop 1.6. 
When I add new product, if Price is with two decimals get an error, without decimals insert product ok.
when i update product accept two decimals

**Comment by flauteps** [comment]
Hi I have the same problem as commitspl
i need help

**Comment by carlosptt** [comment]
As you changed the namspace, for it to work for you I have the same problem and I do not give with error

**Comment by carlosptt** [comment]
@flauteps @commitspl @EduLeonPavon I need help urgent
