### ISSUE TITLE
Changing order status properly

### ISSUE THREAD

**Issue by SebastianSienicki** [Bukimedia/PrestaSharp#71]
If someone want's to change order states remotely must do it by adding order_histories API.
There wasn't one and i develop it.

Entity
order_history.cs

> using RestSharp.Serializers;
> using System;
> using System.Collections.Generic;
> using System.Linq;
> using System.Text;
> using System.Threading.Tasks;
> using System.Xml.Serialization;
> namespace Bukimedia.PrestaSharp.Entities
> {
>     [XmlType(Namespace = "Bukimedia/PrestaSharp/Entities")]
>     public class order_history : PrestaShopEntity
>     {
>          public long? id { get; set; }
>          public long? id_order_state { get; set; }
>          public long? id_order { get; set; }
>          public long? id_employee { get; set; }
>          public string date_add { get; set; }
>     }
> }

FilterEntities
order_history.cs

> using System;
> using System.Collections.Generic;
> using System.Linq;
> using System.Text;
> using System.Threading.Tasks;
> using System.Xml.Serialization;
> namespace Bukimedia.PrestaSharp.Entities.FilterEntities
> {
>     [XmlType(Namespace = "Bukimedia/PrestaSharp/Entities/FilterEntities")]
>     public class order_history : GenericFilterEntity
>     {
>     }
> }

Factory
OrderHistoryFactory.cs

> using RestSharp;
> using System;
> using System.Collections.Generic;
> using System.Linq;
> using System.Text;
> using System.Threading.Tasks;
> using System.Xml.Serialization;
> namespace Bukimedia.PrestaSharp.Factories
> {
>     public class OrderHistoryFactory : RestSharpFactory
>     {
>         public OrderHistoryFactory(string BaseUrl, string Account, string SecretKey)
>             : base(BaseUrl, Account, SecretKey)
>         {
>         }
>         public Entities.order_history Get(long OrderHistoryId)
>         {
>             RestRequest request = this.RequestForGet("order_histories", OrderHistoryId, "order_history");
>             return this.Execute<Entities.order_history>(request);
>         }
>         public Entities.order_history Add(Entities.order_history OrderHistory)
>         {
>             long? idAux = OrderHistory.id;
>             OrderHistory.id = null;
>             List<PrestaSharp.Entities.PrestaShopEntity> Entities = new List<PrestaSharp.Entities.PrestaShopEntity>();
>             Entities.Add(OrderHistory);
>             RestRequest request = this.RequestForAddOrderHistory("order_histories", Entities);
>             Entities.order_history aux = this.Execute<Entities.order_history>(request);
>             OrderHistory.id = idAux;
>             return this.Get((long)aux.id);
>         }
>         public void Update(Entities.order_history OrderHistory)
>         {
>             RestRequest request = this.RequestForUpdate("order_histories", OrderHistory.id, OrderHistory);
>             this.Execute<Entities.order_history>(request);
>         }
>         public void Delete(long OrderHistoryId)
>         {
>             RestRequest request = this.RequestForDelete("order_histories", OrderHistoryId);
>             this.Execute<Entities.order_history>(request);
>         }
>         public void Delete(Entities.order_history OrderHistory)
>         {
>             this.Delete((long)OrderHistory.id);
>         }
>         public List<long> GetIds()
>         {
>             RestRequest request = this.RequestForGet("order_histories", null, "prestashop");
>             return this.ExecuteForGetIds<List<long>>(request, "order_history");
>         }
>         public List<Entities.order_history> GetByFilter(Dictionary<string, string> Filter, string Sort, string Limit)
>         {
>             RestRequest request = this.RequestForFilter("order_histories", "full", Filter, Sort, Limit, "order_histories");
>             return this.ExecuteForFilter<List<Entities.order_history>>(request);
>         }
>         public List<long> GetIdsByFilter(Dictionary<string, string> Filter, string Sort, string Limit)
>         {
>             RestRequest request = this.RequestForFilter("order_histories", "[id]", Filter, Sort, Limit, "order_histories");
>             List<PrestaSharp.Entities.FilterEntities.order_history> aux = this.Execute<List<PrestaSharp.Entities.FilterEntities.order_history>>(request);
>             return (List<long>)(from t in aux select t.id).ToList<long>();
>         }
>         public List<Entities.order_history> GetAll()
>         {
>             return this.GetByFilter(null, null, null);
>         }
>         public List<Entities.order_history> AddList(List<Entities.order_history> OrderHistoryies)
>         {
>             List<PrestaSharp.Entities.PrestaShopEntity> Entities = new List<PrestaSharp.Entities.PrestaShopEntity>();
>             foreach (Entities.order_history OrderHistory in OrderHistoryies)
>             {
>                 OrderHistory.id = null;
>                 Entities.Add(OrderHistory);
>             }
>             RestRequest request = this.RequestForAdd("order_histories", Entities);
>             return this.Execute<List<Entities.order_history>>(request);
>         }
>     }
> }

And if you wont to send e-mail notifications on changing order status you should to add request parameter

> request.AddParameter("sendemail", 1);

to RestRequest i did it by create another function in RestSharpFactory

> ```
>    protected RestRequest RequestForAddOrderHistory(string Resource, List<Entities.PrestaShopEntity> Entities)
>     {
>         var request = new RestRequest();
>         request.Resource = Resource;
>         request.Method = Method.POST;
>         request.RequestFormat = DataFormat.Xml;
>         //Hack implementation in PrestaSharpSerializer to serialize PrestaSharp.Entities.AuxEntities.language
>         request.XmlSerializer = new Serializers.PrestaSharpSerializer();
>         string serialized = "";
>         foreach (Entities.PrestaShopEntity Entity in Entities)
>         {
>             serialized += ((Serializers.PrestaSharpSerializer)request.XmlSerializer).PrestaSharpSerialize(Entity);
>         }
>         serialized = "<prestashop>\n" + serialized + "\n</prestashop>";
>         request.AddParameter("xml", serialized);
>         request.AddParameter("sendemail", 1);
>         return request;
>     }
> ```

**Comment by joparsa77** [comment]
Hi @EduLeonPavon 

I've tried this solution but the order_history add request inovcation is returning me the following error:

![image](https://cloud.githubusercontent.com/assets/7669669/5852485/e73da27a-a217-11e4-8f94-7c730fd9b9df.png)

I even tried to send the 'sendemail' parameter as an URL segment (code commented), but it didn't work.
My prestashop version is 1.6.0.9.
The code of RequestForAddOrderHistory function in my project is (notice some namespaces are renamed, but this is not a problem):

        protected RestRequest RequestForAddOrderHistory(string Resource, List<Model.PrestaShop.Entities.PrestaShopEntity> Entities)
        {
            /*
			Parameter paramSendEmail = new Parameter();
            paramSendEmail.Type = ParameterType.UrlSegment;
            paramSendEmail.Name = "SendEmailParam";
            paramSendEmail.Value = "sendemail=1"
			*/

            var request = new RestRequest();
            request.Resource = Resource;
            //request.Resource = Resource + "{SendEmailParam}";
            request.Method = Method.POST;
            request.RequestFormat = DataFormat.Xml;
            request.XmlSerializer = new PrestaShopSerializer();
            string serialized = "";
            foreach (Model.PrestaShop.Entities.PrestaShopEntity Entity in Entities)
            {
                serialized += ((PrestaShopSerializer)request.XmlSerializer).PrestaSharpSerialize(Entity);
            }
            serialized = "<prestashop>\n" + serialized + "\n</prestashop>";
            request.AddParameter("xml", serialized);
            request.AddParameter("sendemail", 1);

            //request.AddParameter(paramSendEmail);
            return request;
        }

Thanks in advance!
