### ISSUE TITLE
Is it possible to filter with associations properties ?

### ISSUE THREAD

**Issue by scherer-michael** [Bukimedia/PrestaSharp#82]
Hello,
I just had a brief question.
As told in the title, is it possible to filter an entity through the properties in the association attribute for example in a combination entity ?
In a project, I try to find a combination that has a specific product id and a specific attribute id.
And for the moment I am searching like the following
![2si-lmps-mntv2 - microsoft visual studio_2014-09-24_16-12-38](https://cloud.githubusercontent.com/assets/3429552/4389400/ec4d0fac-43f4-11e4-9775-d0603ab7ffe4.jpg)
But if there is a better way to do something like this, can someone give me a short sample to understand how it works ?

Thank you in advance !
Cordialy,
Psyko

**Comment by fredoche1810** [comment]
Hello @Psykoangel,
I tried to apply your solution but I always have an exception.
The value couldn't be null. Name of the parameter : source
What's your code before var combinations ?
Thanks,

**Comment by Psykoangel** [comment]
Hi @fredoche1810 
I'm sorry, but I don't really understand your problem here.
Since it's been about a few years I did not touch this project, I am maybe a little bit outdated.
However, I will try my best : Which exception are you receiving ?
What are you trying to do ?
Regards !

**Comment by fredoche1810** [comment]
Hello @Psykoangel,
I'm trying to find the combination ID (or Combination complete) for a product (to update it) when I have the Product_option_value.ID
When I search as you propose you receive an error 
Value cannot be null.
Parameter name: source
StackTree :
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
Thanks,

**Comment by Psykoangel** [comment]
@fredoche1810 
The exception you are receiving, is LINQ related  : The list on which you are using Where/Any/First/etc. is empty.
I would check your lists' content first (the combinations list you received from combinationFactory for example).
Regards.

**Comment by fredoche1810** [comment]
@Psykoangel 
You're right. The problem is the simple function CombinationFactory.GetAll() return null
When I test like this MyProduct.associations.combinations.Count() I've got 2 as answer.
I think there is a bug with the Combination factory.
