### ISSUE TITLE
Reading Product Options and Features

### ISSUE THREAD

**Issue by iang0ld** [Bukimedia/PrestaSharp#88]
I am reading these are get a null response in the RestSharp Factory?  Have these been tested?  Are they working?

**Comment by quases** [comment]
Hi,
I need to know how to list the features values of a product, I have done several tests and list the products, features and values of the features but I can not get the features values of a specific product. I have tried using the filters but there is no field that you can filter the values of the features values or features of a specific product.
Thank you.

**Comment by mulflar** [comment]
You can get the product features retrieving a product, It has a AuxEntities.AssociationsProduct associations object, who contains a List<product_feature> product_features

**Comment by quases** [comment]
@mulflar. Thank you very much, it was very simple, imagine that the solution could not be complicated, but I could not find it. It's my first experience asking somewhere on the internet and thanks to you to been very helpful

**Comment by NearEarthObject** [comment]
Hi Everybody,
I am just starting working with this library, but I remain more than confuse with AuxEntities associations.
For Instance : 
I get all the customers from Prestashop DataBase

CustomerFactory PF = new CustomerFactory(BaseUrl, Account, Password);
Dictionary<string, string> dtn = new Dictionary<string, string>();
List<customer> customers = PF.GetAll();
Running like a charm...
Then I need to lookup result to select different customer class field 
foreach (customer customer in customers)
{
Console.Writeline(customer.firstname)
Console.Writeline(customer.lastname)
etc etc... Working like a charm.
}

- when the loop arrive to "associations" witch is lead by default to group class
- Console.WriteLine("customer.associations.groups) return :
- System.Collections.Generic.List`1[myprogramName.Entities.AuxEntities.group]

So i get a List who logically should be a List<group> if I refer to AssociationsCustomer :
yet It contain nothing except id who is id_default_group.

How can I manipulate the code to simply get id_default_group name as associate fields ?

Any help would be welcome
