### ISSUE TITLE
Product creation

### ISSUE THREAD

**Issue by totti240282** [Bukimedia/PrestaSharp#93]
good Morning,
where can I find a complete example to add products on my store ?

Thanks.

**Comment by InformaticaCreativa** [comment]
I'm sorry for re-open this topic. 
I'm trying to upload a product using the above code written by EduLeonPavon but the response is "Internal error. To see this error please display the PHP errors.
Sended data are:
<prestashop>
<product>
  <id_supplier>1</id_supplier>
  <id_manufacturer>32</id_manufacturer>
  <id_category_default>2</id_category_default>
  <id_tax_rules_group>53</id_tax_rules_group>
  <id_shop_default>8</id_shop_default>
  <on_sale>0</on_sale>
  <online_only>0</online_only>
  <ean13>8001234569865</ean13>
  <upc></upc>
  <ecotax>0</ecotax>
  <minimal_quantity>0</minimal_quantity>
  <price>9.8</price>
  <wholesale_price>0</wholesale_price>
  <unity>PZ</unity>
  <unit_price_ratio>1</unit_price_ratio>
  <additional_shipping_cost>0</additional_shipping_cost>
  <reference></reference>
  <supplier_reference>Diamont</supplier_reference>
  <location></location>
  <width>0</width>
  <height>0</height>
  <depth>0</depth>
  <weight>0</weight>
  <quantity_discount>0</quantity_discount>
  <customizable>0</customizable>
  <uploadable_files>4</uploadable_files>
  <text_fields>3</text_fields>
  <active>1</active>
  <redirect_type></redirect_type>
  <id_product_redirected>0</id_product_redirected>
  <available_for_order>1</available_for_order>
  <condition></condition>
  <show_price>1</show_price>
  <indexed>1</indexed>
  <visibility>1</visibility>
  <cache_is_pack>0</cache_is_pack>
  <cache_has_attachments>0</cache_has_attachments>
  <is_virtual>0</is_virtual>
  <cache_default_attribute>0</cache_default_attribute>
  <advanced_stock_management>0</advanced_stock_management>
  <meta_description>
    <language id="6">Articolo 1 prova</language>
  </meta_description>
  <meta_keywords>
    <language id="6">001</language>
  </meta_keywords>
  <meta_title>
    <language id="6">001</language>
  </meta_title>
  <link_rewrite>
    <language id="6">articolo-1-prova</language>
  </link_rewrite>
  <name>
    <language id="1">001</language>
  </name>
  <description>
    <language id="6">Articolo 1 prova</language>
  </description>
  <description_short>
    <language id="6"></language>
  </description_short>
  <available_now />
  <available_later />
  <associations>
    <categories>
      <category>
        <id>2</id>
      </category>
    </categories>
    <images />
    <combinations />
    <product_option_values />
    <product_features />
    <tags />
    <stock_availables />
    <product_bundle />
    <accessories />
  </associations>
</product>
</prestashop>

What's wrong? 
Thank you in advance.

**Comment by EduLeonPavon** [comment]
Hello @InformaticaCreativa 
Please, enable display php errors. You can find this guide https://github.com/Bukimedia/PrestaSharp/blob/master/Enable%20display%20errors%20in%20Prestashop.txt
Regards.

**Comment by InformaticaCreativa** [comment]
Thank you for support.
I resolved my problems.

Regards.

**Comment by EduLeonPavon** [comment]
Thanks to you.

**Comment by polaije** [comment]
Hello,
I have used your code to add a product but I have a lot of missing functions:
Functions.FormatPrestaShopPrice,
GetPrestaSharpProductIdFromPrestaShopByRef,
 GetValueFromLanguage,
ShopsController.GetPrestaSharpShopIdFromProduct,
CategoriesController.GetPrestaSharpDefaultCategoryFromSendProduct
etc...
Do I miss Something in my references ?

Thanks for helping me,
Jean-Marie
